#!/usr/bin/env python3
"""Prohibited mutations of the payment-event ledger, run against its OFFLINE structural pins
(test/payment-event-ledger-structure.test.mjs). The database half has its own harness (test/payment_event_ledger_pg/run.sh runs
every mutation of the SQL against the real Postgres suite); this one answers a different question: does every PIN go red when the
thing it guards is broken?

    python3 test/payment_event_ledger_mutants.py                  # every mutation, then the coverage check
    python3 test/payment_event_ledger_mutants.py name [name ...]

For each mutation it edits files IN PLACE, runs the structural test, and ALWAYS restores the originals (even on error or ^C), then
re-runs the unmutated test and compares every touched file byte for byte. An anchor that does not match the stated number of times is
a harness failure, never a pass. Exit 0 only if (1) every mutation turned the test red, and (2) EVERY pin of the test was the pin
that went red for at least one mutation. A pin that no mutation has ever turned red is a pin nobody has shown can fail, and is
reported as UNCOVERED. (Manual, like follow_report_mutants.py: CI runs the test, not this loop.)

A mutation is a list of (file, old, new[, count]). `count` defaults to 1, and None means "every occurrence, at least one". `old` None
with a file that does not exist creates it (and removes it afterwards); with a file that does exist it replaces the whole file.
The SQL mutations named in test/payment_event_ledger_pg/mutate.py are reused as they are, by name.
"""
import importlib.util
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEST = 'test/payment-event-ledger-structure.test.mjs'
SQL = 'docs/payment-event-ledger.sql'
SUITE = 'test/payment_event_ledger_pg/suite.sql'
MUTP = 'test/payment_event_ledger_pg/mutate.py'
RUN = 'test/payment_event_ledger_pg/run.sh'
FIX = 'test/payment_event_ledger_pg/fixture.sql'
WF = '.github/workflows/payment-event-ledger-suite.yml'
DOC = 'docs/development-activity-paid-continuation-2026-10-01.md'
STATUS = 'docs/development-activity-status-2026-09-30.md'

_spec = importlib.util.spec_from_file_location('ledger_mutate', ROOT / MUTP)
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)


def from_sql(name):
    """the named mutation of the SQL, exactly as the database harness applies it"""
    return [(SQL, old, new, count) for (old, new, count) in _mod.MUTATIONS[name]]


M = {}
# ---- the located controls: if the thing is gone, the pin must notice -----------------------------------------------------------------------------
M['fixture_gutted'] = [(FIX, None, '-- gutted\n')]                                                                         # 0, 11e
M['function_renamed'] = [(SQL, 'create or replace function public.payment_event_latest_id(', 'create or replace function public.payment_event_latest(', 1)]   # 0b
M['unterminated_quote_in_code'] = [(SQL, '-- drop function if exists public.payment_event_immutable();\n-- ROLLBACK-END\n', "-- drop function if exists public.payment_event_immutable();\n-- ROLLBACK-END\nselect 'unterminated;\n", 1)]            # 0c (at the end of the file: nothing later can close it)
M['string_blanker_broken'] = [(TEST, "const blankStrings = (s) => s.replace(/'(?:[^']|'')*'/g, \"''\");", 'const blankStrings = (s) => s;', 1)]           # 0d (the pins\' own scanner)
M['scan_matches_nothing'] = [(TEST, ".filter((f) => /\\.(sql|js|mjs|ts|html|py|sh|yml|json)$/.test(f));", ".filter((f) => /\\.nomatch$/.test(f));", 1)]      # 9-control
# ---- what can be stored ------------------------------------------------------------------------------------------------------------------------------
M['email_column_added'] = from_sql('email_column_added')                                                                  # 1, 1b, 1c
M['allowlist_widened_to_email'] = from_sql('allowlist_widened_to_email')                                                  # 1c
M['mapped_status_a_plain_default'] = [(SQL, 'generated always as (public.payment_event_map_status(processor, processor_status)) stored', "default 'unknown'", 1)]   # 1d
M['identity_by_default'] = [(SQL, 'bigint      generated always as identity primary key', 'bigint      generated by default as identity primary key', 1)]       # 1e
# ---- one writer, nothing else touched ----------------------------------------------------------------------------------------------------------------
M['second_insert_outside_the_recorder'] = [(SQL, 'grant select on public.payment_event to service_role;',
    "grant select on public.payment_event to service_role;\ninsert into public.payment_event (processor, idempotency_key, subscription_ref, event_name, occurred_at, livemode) values ('x', 'x', 'x', 'x', now(), true);", 1)]   # 2
M['update_statement_added'] = [(SQL, 'grant select on public.payment_event to service_role;', "grant select on public.payment_event to service_role;\nupdate public.payment_event set livemode = true;", 1)]   # 2b
M['alter_someone_elses_table'] = [(SQL, 'grant select on public.payment_event to service_role;', "grant select on public.payment_event to service_role;\nalter table public.subscriptions enable row level security;", 1)]   # 2c, 3, 3b
M['foreign_key_to_subscriptions'] = from_sql('foreign_key_to_subscriptions')                                              # 2d
M['recorder_writes_subscriptions'] = from_sql('recorder_writes_subscriptions')                                            # 3
M['reads_another_report_table'] = [(SQL, 'grant select on public.payment_event to service_role;', "grant select on public.payment_event to service_role;\nselect count(*) from public.report_snapshot;", 1)]   # 3b
M['schedules_a_job'] = [(SQL, 'grant select on public.payment_event to service_role;', "grant select on public.payment_event to service_role;\nselect cron.schedule('x', '* * * * *', 'select 1');", 1)]   # 3c
# ---- definer rights, lock-down, append-only --------------------------------------------------------------------------------------------------------
M['recorder_not_security_definer'] = from_sql('recorder_not_security_definer')                                            # 4
M['latest_search_path_unpinned'] = [(SQL, 'language sql stable\nset search_path = public, pg_temp\nas $$\n  select e.event_id', 'language sql stable\nas $$\n  select e.event_id', 1)]   # 4b
M['no_rls'] = from_sql('no_rls')                                                                                          # 4c
M['anon_can_read'] = from_sql('anon_can_read')                                                                            # 4d
M['functions_unlocked'] = from_sql('functions_unlocked')                                                                  # 4e
M['sequence_left_open'] = from_sql('sequence_left_open')                                                                  # 4f
M['no_append_only_trigger'] = from_sql('no_append_only_trigger')                                                          # 5
# ---- one ordering rule, one idempotency rule, one mapping ---------------------------------------------------------------------------------------------
M['ordering_by_arrival'] = from_sql('ordering_by_arrival')                                                                # 6
M['a_second_order_by'] = [(SQL, '  select e.event_id\n    from public.payment_event e', '  select e.event_id\n    from (select * from public.payment_event order by event_id) e', 1)]   # 6
M['no_unique_idempotency_key'] = from_sql('no_unique_idempotency_key')                                                    # 6b
M['key_reuse_not_detected'] = from_sql('key_reuse_not_detected')                                                          # 6c
M['unknown_status_mapped_to_active'] = from_sql('unknown_status_mapped_to_active')                                        # 6d
M['cancelled_not_mapped'] = from_sql('cancelled_not_mapped')                                                              # 6e
M['mapped_vocabulary_not_closed'] = [(SQL, "'canceled', 'unknown'))", "'canceled', 'unknown', 'refunded'))", 1)]            # 6e
M['race_no_subscription_lock'] = from_sql('race_no_subscription_lock')                                                    # 6f
M['lock_after_the_insert'] = [(SQL, "  perform pg_advisory_xact_lock(hashtextextended('payment_event|' || v_proc || '|' || v_live::text || '|' || v_sub, 0));\n", '', 1),
                              (SQL, "  return query select v_outcome", "  perform pg_advisory_xact_lock(hashtextextended('payment_event|' || v_proc || '|' || v_live::text || '|' || v_sub, 0));\n  return query select v_outcome", 1)]   # 6f
M['latest_ignores_the_mode'] = from_sql('latest_ignores_the_mode')                                                        # 6g
# ---- what the recorder accepts ---------------------------------------------------------------------------------------------------------------------------
M['unknown_key_ignored_not_refused'] = from_sql('unknown_key_ignored_not_refused')                                        # 7
M['opaque_allows_an_at_sign'] = from_sql('opaque_allows_an_at_sign')                                                      # 7b
M['opaque_allows_a_space'] = from_sql('opaque_allows_a_space')                                                            # 7b
M['zoneless_time_accepted'] = from_sql('zoneless_time_accepted')                                                          # 7c
M['caller_chooses_the_time'] = [(SQL, 'create or replace function public.payment_event_record(p_event jsonb)', 'create or replace function public.payment_event_record(p_event jsonb, p_at timestamptz default null)', 1)]   # 7d
M['refusal_message_leaks_the_value'] = from_sql('refusal_message_leaks_the_value')                                        # 7e
# ---- the file is additive, idempotent, rolls back, and says what it is ---------------------------------------------------------------------------------
M['rollback_leaves_a_function'] = from_sql('rollback_leaves_a_function')                                                  # 8
M['rollback_drops_the_functions_first'] = from_sql('rollback_drops_the_functions_first')                                  # 8
M['bare_create_table'] = [(SQL, 'create table if not exists public.payment_event (', 'create table public.payment_event (', 1)]   # 8b
M['header_claims_applied'] = [(SQL, 'SQL OF RECORD. NOT APPLIED. Nothing calls it.', 'SQL OF RECORD. APPLIED. Nothing calls it.', 1)]   # 8c
# ---- no caller, no webhook, no second ledger ------------------------------------------------------------------------------------------------------------------
M['a_caller_appears'] = [('scripts/run-unit-tests.mjs', '#!/usr/bin/env node', '#!/usr/bin/env node\n// payment_event_record( is called from here', 1)]   # 9
M['webhook_copied_into_this_repo'] = [('supabase/functions/lemonsqueezy-webhook/index.ts', None, '// a copy of the webhook\n')]   # 9b
M['map_ignores_the_processor'] = from_sql('map_ignores_the_processor')                                                    # 9c, 6d
# ---- a check, not a job ----------------------------------------------------------------------------------------------------------------------------------------------
M['workflow_gains_a_schedule'] = [(WF, 'on:\n  pull_request:', "on:\n  schedule:\n    - cron: '17 3 * * *'\n  pull_request:", 1)]   # 10
M['workflow_database_not_disposable'] = [(WF, 'POSTGRES_DB: payment_event_disposable', 'POSTGRES_DB: payment_event', 1)]   # 10b
M['workflow_path_dropped'] = [(WF, "      - 'docs/payment-event-ledger.sql'\n", '', 1)]                                    # 10c
# ---- the suite, its mutations and its harness are real and wired ---------------------------------------------------------------------------------------
M['suite_checks_removed'] = [(SUITE, "select pg_temp._ck('D06", "select pg_temp._skip('D06", None)]                         # 11
M['mutation_name_duplicated'] = [(MUTP, "    'no_rls': [", "    'no_unique_idempotency_key': [", 1)]                              # 11b, 11c
M['audit_mutation_renamed'] = [(MUTP, "    'ordering_by_arrival': [", "    'ordering_by_arrival_x': [", 1)]                # 11c
M['harness_accepts_a_real_database'] = [(RUN, '*disposable*) ;;', '*) ;;', 1)]                                              # 11d
M['trap_only_warns'] = [(FIX, "raise exception 'TRAP: public.subscriptions was touched (% refused)', tg_op;", "raise notice 'TRAP: public.subscriptions was touched (% refused)', tg_op;", 1)]   # 11e
M['suite_roles_not_set_up'] = [(SUITE, 'alter role service_role bypassrls;', 'select 1;', 1)]                                 # 11f
# ---- the contract and the status file ------------------------------------------------------------------------------------------------------------------------------
M['doc_no_concurrency_check'] = [(DOC, '**Concurrency check — verdict: GENUINE GAP**', '**Verdict — GENUINE GAP**', 1)]       # 12
M['doc_no_unverified'] = [(DOC, 'UNVERIFIED', 'unchecked', None)]                                                              # 12b
M['doc_no_ingest_decision'] = [(DOC, 'homesignal-ingest', 'the other repo', None)]                                              # 12c
M['doc_invents_a_price'] = [(DOC, '**None is stated as copy anywhere.**', '**None is stated as copy anywhere.** The price is $99/month.', 1)]   # 12d
M['status_strikes_order_m'] = [(STATUS, '- M. Paid continuation path — **open. Step M0', '- ~~M. Paid continuation path~~ — **done. Step M0', 1)]   # 12e
M['status_strikes_order_n'] = [(STATUS, '- N. End-to-end launch gate — open.', '- ~~N. End-to-end launch gate~~ — done.', 1)]   # 12f
# ---- no secret, no model name --------------------------------------------------------------------------------------------------------------------------------------------
M['secret_in_the_sql'] = [(SQL, '-- ADDITIVE ONLY. Creates one table', '-- whsec_abcdefgh12345678\n-- ADDITIVE ONLY. Creates one table', 1)]   # 13
M['model_name_in_the_doc'] = [(DOC, '## 12. What this unit does not do', '## 12. What this unit does not do (sonnet)', 1)]   # 13b

PIN = re.compile(r'^(PASS|FAIL) — ([0-9]+[a-z]*(?:-control)?):')


def run_test():
    r = subprocess.run(['node', str(ROOT / TEST)], cwd=ROOT, capture_output=True, text=True)
    pins = {}
    for line in r.stdout.splitlines():
        m = PIN.match(line)
        if m:
            pins[m.group(2)] = m.group(1)
    return r.returncode, pins


def apply(mut, originals, created):
    """edit the tree; returns None on success or a message on a harness fault"""
    for item in mut:
        file, old, new = item[0], item[1], item[2]
        count = item[3] if len(item) > 3 else 1
        p = ROOT / file
        if old is None:
            if p.exists():
                originals.setdefault(file, p.read_text())
            else:
                d = p.parent
                missing = []
                while not d.exists():
                    missing.append(d)
                    d = d.parent
                p.parent.mkdir(parents=True, exist_ok=True)
                created.append((p, missing))
            p.write_text(new)
            continue
        originals.setdefault(file, p.read_text())
        text = p.read_text()
        found = text.count(old)
        if (count is None and found < 1) or (count is not None and found != count):
            return 'anchor matched %d time(s) in %s, expected %s' % (found, file, 'at least 1' if count is None else count)
        if old == new:
            return 'mutation changes nothing in %s' % file
        p.write_text(text.replace(old, new))
    return None


def restore(originals, created):
    for file, text in originals.items():
        (ROOT / file).write_text(text)
    for p, missing in created:
        if p.exists():
            p.unlink()
        for d in missing:
            if d.exists() and not any(d.iterdir()):
                d.rmdir()


def main():
    only = [a for a in sys.argv[1:] if not a.startswith('--')]
    unknown = [a for a in only if a not in M]
    if unknown:
        print('HARNESS — unknown mutation(s): ' + ', '.join(unknown))
        return 2
    rc, base = run_test()
    if rc != 0 or not base or any(v != 'PASS' for v in base.values()):
        print('HARNESS — the unmutated tree does not pass the structural test (%d pins read)' % len(base))
        return 2
    names = [k for k in M if not only or k in only]
    survived, harness, covered = [], [], set()
    for name in names:
        originals, created = {}, []
        try:
            fault = apply(M[name], originals, created)
            if fault:
                print('HARNESS  %-38s %s' % (name, fault))
                harness.append(name)
                continue
            rc, pins = run_test()
            red = sorted(k for k, v in pins.items() if v == 'FAIL')
            if rc != 0 and red:
                covered.update(red)
                print('killed   %-38s by %s' % (name, ', '.join(red[:8]) + (' …' if len(red) > 8 else '')))
            elif rc != 0:
                covered.add('(crash)')
                print('killed   %-38s by a crash before any pin printed' % name)
            else:
                print('SURVIVED %s' % name)
                survived.append(name)
        finally:
            restore(originals, created)
    rc, after = run_test()
    if rc != 0:
        print('HARNESS — the tree does not pass after restoring')
        return 2
    leftover = subprocess.run(['git', 'status', '--porcelain', '--', 'supabase/functions/lemonsqueezy-webhook'], cwd=ROOT, capture_output=True, text=True).stdout.strip()
    if leftover or (ROOT / 'supabase/functions/lemonsqueezy-webhook').exists():
        print('HARNESS — a created file was not removed: ' + leftover)
        return 2
    uncovered = sorted(set(base) - covered, key=lambda s: (int(re.match(r'\d+', s).group()), s))
    ran = len(names) - len(harness)
    print('\n%d mutations run, %d killed, %d survived, %d harness faults; %d of %d pins were turned red by at least one mutation'
          % (ran, ran - len(survived), len(survived), len(harness), len(set(base) & covered), len(base)))
    if survived:
        print('SURVIVORS: ' + ', '.join(survived))
    if uncovered and not only:
        print('UNCOVERED PINS (no mutation has ever turned them red): ' + ', '.join(uncovered))
    return 1 if (survived or harness or (uncovered and not only)) else 0


if __name__ == '__main__':
    sys.exit(main())
