// ZIP-GEOGRAPHY INVARIANT for the generated canonical ZIP documents.
//
// A ZIP page represents the WHOLE ZIP geography. It is not an address, not HOME, not a
// centroid, not a radius and not a nearest-point view. That was certified in 6d9ce37 as a
// design property; this file makes it a CONTROL, because nothing at runtime would notice
// it breaking — a fabricated "0.0 mi" renders exactly as convincingly as a real distance.
//
// Two frozen controls from the founder's list:
//   I — anonymous / no-point ZIP page: the generator is handed no address, no session and
//       no home object, and must still produce a complete document.
//   J — radius/point leakage negative control: the fixture's densest page must contain no
//       coordinate, distance or centroid string anywhere in its bytes.
//
// The generator is executed, not re-implemented: these assertions read the SHIPPED file and
// the bytes it actually writes.
import { execFileSync } from 'node:child_process';
import { readFileSync, rmSync, mkdtempSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const GEN = join(root, 'scripts', 'gen_zip_pages.py');
const FIX = join(root, 'test', 'fixtures', 'zip-pages.json');
let pass = 0, fail = 0;
const ok = (c, m) => { if (c) { pass++; console.log('PASS —', m); } else { fail++; console.error('FAIL —', m); } };

// ---- the generator's own source: eligibility may not depend on a point ------------------
const gen = readFileSync(GEN, 'utf8');
const code = gen
  .split('\n').filter((l) => !l.trimStart().startsWith('#')).join('\n')  // prose may NAME them
  .replace(/"""[\s\S]*?"""/g, '');                                       // nor may a docstring
for (const banned of ['zip_centroids', 'distance_mi', 'withDistance', 'homeFor', 'app_projects',
                      'centroid', 'radius', 'nearest', 'geo_lat', 'geo_lng', 'ST_Distance']) {
  ok(!code.includes(banned), `generator code contains no "${banned}"`);
}
ok(!/\b_lat\b/.test(code) && !/\b_lng\b/.test(code), 'generator code contains no _lat/_lng');
// ...and the applicability it DOES use is set membership + the jurisdiction chain.
ok(/zip_codes/.test(gen), 'applicability uses communities.zip_codes (ZIP set membership)');
ok(/parent_id/.test(gen), 'applicability walks the parent_id jurisdiction chain');
ok(/app_changes/.test(gen), 'Alerts placements are read from app_changes, keyed by ZIP');

// ---- control I: a document renders with no address, no home, no session -----------------
const out = mkdtempSync(join(tmpdir(), 'zp-np-'));
execFileSync('python3', [GEN, '--fixture', FIX, '--out', out, '--now', '2026-09-04T00:00:00'],
  { encoding: 'utf8', env: { ...process.env, HOME_ADDRESS: '', HS_HOME: '' } });
const docs = readdirSync(join(out, 'community'));
ok(docs.length === 5, `control I — every canonical ZIP rendered with no address supplied (${docs.length})`);
const anon = readFileSync(join(out, 'community', '01001', 'index.html'), 'utf8');
ok(/<h1>01001 · /.test(anon), 'control I — the anonymous document still carries its ZIP identity');
ok(/<section class="zsec"><h2>Local news<\/h2><ul>/.test(anon),
   'control I — the anonymous document still carries real Alerts items');

// ---- control J: no point/radius leakage in ANY generated byte ---------------------------
const LEAK = [/\d+(\.\d+)?\s*mi\b/, /distance_mi/, /data-home/, /centroid/i, /\blat(itude)?"\s*:/i,
              /\blng"\s*:/i, /radius/i, /"home"/, /nearest/i];
let leaks = 0;
for (const z of docs) {
  const html = readFileSync(join(out, 'community', z, 'index.html'), 'utf8');
  for (const re of LEAK) if (re.test(html)) { leaks++; console.error(`  leak in ${z}: ${re}`); }
}
ok(leaks === 0, 'control J — no distance / HOME / centroid / radius string in any generated document');
rmSync(out, { recursive: true, force: true });

console.log(`\n${pass} passed, ${fail} failed`);
if (fail) process.exit(1);
