// GENERATED by scripts/gen-brand-origins.mjs from docs/brand/brand-contract.v1.json. DO NOT EDIT.
// Regenerate: node scripts/gen-brand-origins.mjs   Verified by: test/brand-origins.test.mjs
//
// Browser origins the backend recognises (supported, NOT activated): the origin of every identity in the
// brand contract, plus the legacy www host. Order: current identity, its legacy host(s), future identity.
export const BRAND_CONTRACT_SHA256 = '5fb1a9c320f296297e1e43fd593f4ba2cd3757d2d9dc3c3b9128205e97cfaec3';
export const BROWSER_ORIGINS: readonly string[] = [
  'https://homesignal.net',
  'https://www.homesignal.net',
  'https://jodytracks.com',
];
