#!/usr/bin/env python3
"""Generate docs/dc-atlas-admission-apply.sql FROM the DDL of record -- never retyped (claims rule 7).

STAGE 10 of Atlas coordinate validation: ADMIT Atlas. The apply carries exactly the two statements
the admission changes -- dc_derived_address_admitted and its comment -- sliced out of
docs/dc-step3d-derived-location.sql by #1324's own dollar-quote-aware splitter (imported, not copied).

Inside ONE transaction:
  1. a FAIL-CLOSED drift guard: the live switch must still be Phase A's (md5(prosrc) measured on
     production 2026-09-26 18:16 UTC, and Atlas must read NOT admitted, Epoch admitted), or nothing
     is applied;
  2. the two statements;
  3. an in-transaction post-condition: Atlas admitted, Epoch admitted, nothing else admitted.
It adds no table, alters no table, and touches no view, resolver or the Map 1 reader: Map 1 moves only
when the next hourly resolver runs (stage 11 compares that with the stage 8 dry run).
Run: python3 test/dc_atlas_validation_pg/build_admission.py [--check]
"""
import hashlib, importlib.util, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / 'docs/dc-atlas-admission-apply.sql'
_spec = importlib.util.spec_from_file_location('epoch_apply', ROOT / 'test/dc_epoch_geography_pg/build_apply.py')
_epoch = importlib.util.module_from_spec(_spec); _spec.loader.exec_module(_epoch)

# md5(prosrc) of the live switch, read on production 2026-09-26 18:16 UTC (Phase A's Epoch-only body).
PHASE_A_PROSRC_MD5 = 'cd968b64ada7adaee18a4dc8be0c4a4b'


def build():
    stmts = _epoch.pick('docs/dc-step3d-derived-location.sql', [
        'create or replace function public.dc_derived_address_admitted(',
        'comment on function public.dc_derived_address_admitted(',
    ])
    assert len(stmts) == 2, stmts
    guard = "\n".join([
        "do $guard$",
        "begin",
        "  if (select md5(p.prosrc) from pg_proc p join pg_namespace n on n.oid = p.pronamespace",
        "       where n.nspname = 'public' and p.proname = 'dc_derived_address_admitted') is distinct from",
        f"     '{PHASE_A_PROSRC_MD5}'",
        "     or public.dc_derived_address_admitted('compute_atlas', 'facilities')",
        "     or not public.dc_derived_address_admitted('epoch_ai', 'data_centers') then",
        "    raise exception 'DRIFT: the live admission switch is not Phase A''s (Epoch only). Nothing applied.';",
        "  end if;",
        "end $guard$;"])
    post = "\n".join([
        "do $post$",
        "begin",
        "  if not public.dc_derived_address_admitted('compute_atlas', 'facilities')",
        "     or not public.dc_derived_address_admitted('epoch_ai', 'data_centers')",
        "     or public.dc_derived_address_admitted('compute_atlas', 'other')",
        "     or public.dc_derived_address_admitted('some_new_source', 'facilities') then",
        "    raise exception 'POST-CONDITION: the switch does not admit exactly Epoch data_centers and Atlas facilities. Rolled back.';",
        "  end if;",
        "end $post$;"])
    parts = ['-- GENERATED by test/dc_atlas_validation_pg/build_admission.py from the DDL of record. Do not edit.',
             '-- STAGE 10: admit Atlas (compute_atlas/facilities) in the derived-address admission switch.',
             '-- One transaction: drift guard, the switch and its comment, in-transaction post-condition.',
             'begin;', guard,
             '-- ===== STEP 3D  docs/dc-step3d-derived-location.sql (the admission switch) =====']
    parts.extend(stmts)
    parts.extend([post, 'commit;'])
    return '\n\n'.join(parts) + '\n'


if __name__ == '__main__':
    text = build()
    if '--check' in sys.argv:
        ok = OUT.exists() and OUT.read_text() == text
        print('admission apply file is current' if ok else 'admission apply file is STALE: regenerate it')
        sys.exit(0 if ok else 1)
    OUT.write_text(text)
    print(f'wrote {OUT.relative_to(ROOT)} ({len(text)} bytes, sha256 {hashlib.sha256(text.encode()).hexdigest()})')
