#!/usr/bin/env python3
"""Generate the STAGE 10 admission artifacts FROM the DDL of record -- never retyped (claims rule 7).

  docs/dc-atlas-admission-apply.sql     ADMIT Atlas (applied to production 2026-09-26 18:48 UTC)
  docs/dc-atlas-admission-rollback.sql  WITHDRAW it again (tested, never applied)

The apply carries exactly the two statements the admission changes -- dc_derived_address_admitted and
its comment -- sliced out of docs/dc-step3d-derived-location.sql by #1324's own dollar-quote-aware
splitter (imported, not copied). Inside ONE transaction:
  1. a FAIL-CLOSED drift guard: the live switch must still be Phase A's (md5(prosrc) measured on
     production 2026-09-26 18:16 UTC, and Atlas must read NOT admitted, Epoch admitted), or nothing
     is applied;
  2. the two statements;
  3. an in-transaction post-condition: Atlas admitted, Epoch admitted, nothing else admitted.

The rollback is the same shape in reverse. Its switch body is Phase A's deployed text, taken from
test/dc_atlas_validation_pg/build_apply.py's PHASE_A_REGION (itself extracted from git and pinned by the
Phase A artifact's sha256), so it too is never retyped. Its guard requires the live switch to be the
admitted one (md5 computed here from the DDL of record, and read on production 2026-09-26: 31cb6c9e...);
its post-condition requires Atlas NOT admitted, Epoch admitted, and the body byte-identical to Phase A's.

Neither adds, alters or drops a table, view, resolver or the Map 1 reader: Map 1 moves only when the
next hourly resolver run re-decides geography.
Run: python3 test/dc_atlas_validation_pg/build_admission.py [--check]
"""
import hashlib, importlib.util, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / 'docs/dc-atlas-admission-apply.sql'
OUT_ROLLBACK = ROOT / 'docs/dc-atlas-admission-rollback.sql'


def _load(name, rel):
    spec = importlib.util.spec_from_file_location(name, ROOT / rel)
    mod = importlib.util.module_from_spec(spec); spec.loader.exec_module(mod)
    return mod


_epoch = _load('epoch_apply', 'test/dc_epoch_geography_pg/build_apply.py')
_phase_a = _load('atlas_phase_a_apply', 'test/dc_atlas_validation_pg/build_apply.py')

# md5(prosrc) of the live switch, read on production 2026-09-26 18:16 UTC (Phase A's Epoch-only body).
PHASE_A_PROSRC_MD5 = 'cd968b64ada7adaee18a4dc8be0c4a4b'
ADMISSION_FN = 'create or replace function public.dc_derived_address_admitted('
ADMISSION_COMMENT = 'comment on function public.dc_derived_address_admitted('


def prosrc_md5(stmt):
    m = re.search(r'\bas \$\$(.*?)\$\$;', stmt, re.S)
    assert m, 'admission statement shape changed'
    return hashlib.md5(m.group(1).encode()).hexdigest()


def admission_statements():
    stmts = _epoch.pick('docs/dc-step3d-derived-location.sql', [ADMISSION_FN, ADMISSION_COMMENT])
    assert len(stmts) == 2, stmts
    return stmts


def phase_a_function():
    region = _phase_a.PHASE_A_REGION
    fn = region[region.index(ADMISSION_FN):].rstrip('\n')
    assert prosrc_md5(fn) == PHASE_A_PROSRC_MD5, 'Phase A switch text no longer fingerprints to production'
    return fn


def guard(name, want_md5, atlas_now, message):
    return "\n".join([
        f"do ${name}$",
        "begin",
        "  if (select md5(p.prosrc) from pg_proc p join pg_namespace n on n.oid = p.pronamespace",
        "       where n.nspname = 'public' and p.proname = 'dc_derived_address_admitted') is distinct from",
        f"     '{want_md5}'",
        f"     or {'not ' if atlas_now else ''}public.dc_derived_address_admitted('compute_atlas', 'facilities')",
        "     or not public.dc_derived_address_admitted('epoch_ai', 'data_centers') then",
        f"    raise exception '{message}';",
        "  end if;",
        f"end ${name}$;"])


def post(atlas_after, extra=None):
    lines = ["do $post$",
             "begin",
             f"  if {'not ' if atlas_after else ''}public.dc_derived_address_admitted('compute_atlas', 'facilities')",
             "     or not public.dc_derived_address_admitted('epoch_ai', 'data_centers')",
             "     or public.dc_derived_address_admitted('compute_atlas', 'other')",
             "     or public.dc_derived_address_admitted('some_new_source', 'facilities')"]
    # the apply's text is DEPLOYED (sha256 pinned in the apply script): its "then" stays on the last line
    if extra:
        lines += [extra, "  then"]
    else:
        lines[-1] += " then"
    want = 'exactly Epoch data_centers and Atlas facilities' if atlas_after else 'exactly Epoch data_centers (Phase A)'
    lines += [f"    raise exception 'POST-CONDITION: the switch does not admit {want}. Rolled back.';",
              "  end if;",
              "end $post$;"]
    return "\n".join(lines)


def build():
    stmts = admission_statements()
    parts = ['-- GENERATED by test/dc_atlas_validation_pg/build_admission.py from the DDL of record. Do not edit.',
             '-- STAGE 10: admit Atlas (compute_atlas/facilities) in the derived-address admission switch.',
             '-- One transaction: drift guard, the switch and its comment, in-transaction post-condition.',
             'begin;',
             guard('guard', PHASE_A_PROSRC_MD5, False,
                   "DRIFT: the live admission switch is not Phase A''s (Epoch only). Nothing applied."),
             '-- ===== STEP 3D  docs/dc-step3d-derived-location.sql (the admission switch) =====']
    parts.extend(stmts)
    parts.extend([post(True), 'commit;'])
    return '\n\n'.join(parts) + '\n'


def build_rollback():
    fn, comment = admission_statements()
    admitted_md5 = prosrc_md5(fn)
    parts = ['-- GENERATED by test/dc_atlas_validation_pg/build_admission.py. Do not edit.',
             '-- STAGE 10 ROLLBACK: withdraw Atlas (compute_atlas/facilities) from the admission switch,',
             "-- restoring Phase A's deployed Epoch-only body. Tested offline; applied only by",
             '-- dc-atlas-admission-apply.yml with confirm=ROLLBACK-ATLAS-STAGE-10.',
             '-- One transaction: drift guard, the Phase A switch and its comment, in-transaction post-condition.',
             'begin;',
             guard('guard', admitted_md5, True,
                   'DRIFT: the live admission switch is not the stage 10 admitted one. Nothing rolled back.'),
             "-- ===== the switch as Phase A deployed it (build_apply.py PHASE_A_REGION) =====",
             phase_a_function(),
             comment,
             post(False, "     or (select md5(p.prosrc) from pg_proc p join pg_namespace n on n.oid = p.pronamespace\n"
                         "          where n.nspname = 'public' and p.proname = 'dc_derived_address_admitted')\n"
                         f"        is distinct from '{PHASE_A_PROSRC_MD5}'"),
             'commit;']
    return '\n\n'.join(parts) + '\n'


# ⛔ FROZEN 2026-09-26: the apply was APPLIED to production (run 36263746674) from main@c198216.
# The DDL of record kept moving (C3c admitted openstreetmap in the same switch), so regenerating
# would rewrite history into an artifact nobody applied. --check verifies the FROZEN bytes only;
# the offline proof runs pinned to c198216 (.github/workflows/dc-atlas-admission-apply.yml).
FROZEN = {OUT: '2c2c8571c7ac8167210e66eb9d72a0ddff82843d972526e5951d97d8e2a3341c',
          OUT_ROLLBACK: 'a440713b3ede8fef49495c9a60cc2c509660c33babc1d2c72cdffa0969e9a2e8'}


if __name__ == '__main__':
    if '--check' in sys.argv and '--regenerate-at-applied-commit' not in sys.argv:
        bad = [o.name for o, want in FROZEN.items()
               if not o.exists() or hashlib.sha256(o.read_bytes()).hexdigest() != want]
        print('admission apply + rollback files are the frozen applied artifacts' if not bad
              else f'NOT the frozen applied artifacts: {bad}')
        sys.exit(1 if bad else 0)
    if '--regenerate-at-applied-commit' not in sys.argv:
        raise SystemExit('REFUSED: the stage 10 artifacts are frozen (applied to production); they are never regenerated')
    outs = ((OUT, build()), (OUT_ROLLBACK, build_rollback()))
    if '--check' in sys.argv:
        stale = [o.name for o, t in outs if not (o.exists() and o.read_text() == t)]
        print('admission apply + rollback files are current' if not stale else f'STALE: regenerate {stale}')
        sys.exit(1 if stale else 0)
    for o, t in outs:
        o.write_text(t)
        print(f'wrote {o.relative_to(ROOT)} ({len(t)} bytes, sha256 {hashlib.sha256(t.encode()).hexdigest()})')
