#!/usr/bin/env python3
"""The public origin of the CURRENT brand identity, read from the brand contract (docs/brand/brand-contract.v1.json).

Jody migration, Step 7 plumbing. page_semantics.py, gen_zip_pages.py, gen_sitemap.py and indexnow.py used to hard-code
https://homesignal.net; they now ask this module, so the origin has ONE source (the contract) and moving the public brand is a
contract change, not a four-file edit. While the contract's current_identity is `homesignal` this returns exactly the string
that was hard-coded before, so every generated byte is unchanged (pinned by test/brand-host.test.mjs).
Stdlib only. Fails loudly on an unreadable or malformed contract: a build must never fall back to a guessed host.
"""
from __future__ import annotations

import json
from pathlib import Path
from urllib.parse import urlsplit

CONTRACT = Path(__file__).resolve().parent.parent / "docs" / "brand" / "brand-contract.v1.json"


def origin(contract_path: Path = CONTRACT) -> str:
    c = json.loads(Path(contract_path).read_text(encoding="utf-8"))
    ident = c["identities"][c["current_identity"]]
    o = ident["origin"].rstrip("/")
    u = urlsplit(o)
    if u.scheme != "https" or not u.netloc or u.path or u.query or u.fragment or ident.get("state") != "active":
        raise SystemExit(f"ERROR: brand contract identity {c['current_identity']!r} is not an active https origin: {ident!r}")
    return o


def host(contract_path: Path = CONTRACT) -> str:
    return urlsplit(origin(contract_path)).netloc


if __name__ == "__main__":
    print(origin())
