#!/usr/bin/env python3
"""Build the zero-cost redirect site that will answer on homesignal.net after cutover (Jody migration, Step 5).

Output (a plain static folder - deployable to Netlify Free by drag-and-drop or from a repo base directory):
  _redirects                    the rules (Netlify syntax); ONE catch-all 301 to the Jody origin, preceded by the
                                files that must keep answering on the OLD host
  netlify.toml                  publish dir only - nothing else is configured
  .well-known/did.json          the Bluesky feed-generator DID (did:web:homesignal.net is IMMUTABLE and must keep
                                resolving on homesignal.net) - copied byte-for-byte from the repo, never retyped
  google<token>.html            the old domain's Search Console ownership file(s) - same
  robots.txt                    permissive, NO Sitemap line, so crawlers may follow the redirects

Every destination origin comes from the brand contract. Stdlib only. Run with --check to prove the folder on disk equals
a fresh build (so nothing is hand-edited).
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTRACT = ROOT / "docs" / "brand" / "brand-contract.v1.json"

ROBOTS = "User-agent: *\nAllow: /\n"
TOML = '[build]\n  publish = "."\n'


def target_origin() -> str:
    c = json.loads(CONTRACT.read_text(encoding="utf-8"))
    return c["identities"][c["future_identity"]]["origin"].rstrip("/")


def keep_files() -> list[str]:
    """Paths that must keep answering 200 on the old host. Derived, not listed by hand."""
    out = [".well-known/did.json"]
    out += sorted(p.name for p in ROOT.glob("google*.html") if re.fullmatch(r"google[0-9a-f]+\.html", p.name))
    return out


def rules(origin: str) -> str:
    lines = ["# GENERATED by scripts/build_redirect_site.py - do not edit.",
             "# Files that must keep answering on the old host come FIRST (200!); everything else is a permanent",
             "# redirect to the same path on the Jody origin. Query strings are preserved by the host; a #fragment is",
             "# kept by the browser across a 301."]
    for f in keep_files() + ["robots.txt"]:
        lines.append(f"/{f}  /{f}  200!")
    lines.append(f"/*  {origin}/:splat  301!")
    return "\n".join(lines) + "\n"


def build(out: Path) -> dict[str, bytes]:
    files: dict[str, bytes] = {}
    for f in keep_files():
        files[f] = (ROOT / f).read_bytes()
    files["robots.txt"] = ROBOTS.encode()
    files["netlify.toml"] = TOML.encode()
    files["_redirects"] = rules(target_origin()).encode()
    return files


def write(out: Path, files: dict[str, bytes]) -> None:
    if out.exists():
        shutil.rmtree(out)
    for rel, data in files.items():
        p = out / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(data)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--out", required=True)
    ap.add_argument("--check", action="store_true", help="fail unless --out already equals a fresh build")
    a = ap.parse_args(argv)
    out = Path(a.out)
    files = build(out)
    if a.check:
        for rel, data in files.items():
            p = out / rel
            if not p.is_file() or p.read_bytes() != data:
                print(f"DRIFT: {rel}", file=sys.stderr)
                return 1
        extra = {p.relative_to(out).as_posix() for p in out.rglob("*") if p.is_file()} - set(files)
        if extra:
            print(f"DRIFT: unexpected files {sorted(extra)}", file=sys.stderr)
            return 1
        print("redirect site matches a fresh build")
        return 0
    write(out, files)
    print(json.dumps({"files": {k: hashlib.sha256(v).hexdigest()[:12] for k, v in sorted(files.items())},
                      "target": target_origin()}, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
