#!/usr/bin/env python3
"""Generate sitemap.xml from the live `communities` table — zero-touch SEO at scale.

Every community is a real, indexable dynamic page (community.html?community=<slug>).
Hand-listing 12k+ URLs is impossible, so this reads the DB (public anon key + RLS read)
and emits one <url> per community, plus the static/legacy pages. Run on a schedule so
the sitemap grows automatically as communities are added — never a per-community edit.

Uses only the public anon key (same one shipped in community.html); no secrets.
"""
import json
import sys
import html
import urllib.parse
import urllib.request

SUPA = "https://qwnnmljucajnexpxdgxr.supabase.co"
ANON = ("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3"
        "bm5tbGp1Y2FqbmV4cHhkZ3hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA0MTAyOTgsImV4cCI6"
        "MjA5NTk4NjI5OH0.prpXB6lSIhWMAsdkkaxAfkvEodbojfUUyN4L4JbQE1U")
BASE = "https://homesignal.net"
# The two frozen launch pages have bespoke HTML; point their slug at that, not the dynamic page.
LEGACY = {"box-elder": "/box-elder.html", "eagle-mountain": "/eagle-mountain.html"}
STATIC = [("/", "weekly", "1.0"), ("/how-it-works.html", "monthly", "0.7"),
          ("/about.html", "monthly", "0.6"), ("/contact.html", "monthly", "0.5"),
          ("/privacy.html", "yearly", "0.3"), ("/terms.html", "yearly", "0.3")]
STEP = 1000


def fetch_slugs():
    slugs, off = [], 0
    while True:
        url = (f"{SUPA}/rest/v1/communities?select=slug&slug=not.is.null"
               f"&order=slug.asc&limit={STEP}&offset={off}")
        req = urllib.request.Request(url, headers={"apikey": ANON, "Authorization": f"Bearer {ANON}"})
        with urllib.request.urlopen(req, timeout=90) as r:
            page = json.loads(r.read().decode("utf-8"))
        slugs += [x["slug"] for x in page if x.get("slug")]
        if len(page) < STEP:
            break
        off += STEP
    return slugs


def fetch_dev_zips():
    """Every cached development ZIP page (homesignalmap.html?zip=<zip>). Zero-touch: as the
    development-tracker batch caches more ZIPs into development_reports, they appear here with
    no edit. Public anon read (RLS: public select on development_reports)."""
    zips, off = [], 0
    while True:
        url = (f"{SUPA}/rest/v1/development_reports?select=zip&order=zip.asc"
               f"&limit={STEP}&offset={off}")
        req = urllib.request.Request(url, headers={"apikey": ANON, "Authorization": f"Bearer {ANON}"})
        with urllib.request.urlopen(req, timeout=90) as r:
            page = json.loads(r.read().decode("utf-8"))
        zips += [x["zip"] for x in page if x.get("zip")]
        if len(page) < STEP:
            break
        off += STEP
    return zips


def url_el(loc, freq, pri):
    return (f"  <url>\n    <loc>{html.escape(loc)}</loc>\n"
            f"    <changefreq>{freq}</changefreq>\n    <priority>{pri}</priority>\n  </url>")


def main():
    slugs = fetch_slugs()
    if not slugs:
        print("ERROR: fetched 0 slugs — refusing to overwrite sitemap.xml")
        sys.exit(1)
    dev_zips = fetch_dev_zips()  # development-tracker ZIP pages (may be empty; that's fine)
    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             '<!-- GENERATED by scripts/gen_sitemap.py from the communities + development_reports',
             '     tables — do NOT hand-edit.',
             f'     {len(slugs)} communities + {len(dev_zips)} development ZIP pages + '
             f'{len(STATIC)} static pages. Regenerated on a schedule. -->',
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for loc, freq, pri in STATIC:
        lines.append(url_el(BASE + loc, freq, pri))
    for slug in slugs:
        if slug in LEGACY:
            lines.append(url_el(BASE + LEGACY[slug], "daily", "0.9"))
        else:
            lines.append(url_el(f"{BASE}/community.html?community={urllib.parse.quote(slug)}", "daily", "0.8"))
    for z in dev_zips:
        lines.append(url_el(f"{BASE}/homesignalmap.html?zip={urllib.parse.quote(z)}", "daily", "0.8"))
    lines.append("</urlset>")
    with open("sitemap.xml", "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    total = len(slugs) + len(dev_zips) + len(STATIC)
    print(f"wrote sitemap.xml: {len(slugs)} community + {len(dev_zips)} development + "
          f"{len(STATIC)} static = {total} total")
    if total > 45000:
        print("WARNING: approaching the 50,000-URL sitemap limit — split into a sitemap index soon.")


if __name__ == "__main__":
    main()
