#!/usr/bin/env python3
"""Generate sitemap.xml — INDEX ONLY UTAH for now (new-layout go-live).

The whole site now uses the new layout, but only Utah community pages have accurate,
sourced data, so ONLY Utah is advertised to search (the rest of the country stays a
real, reachable page but noindexed until its data is accurate — see robots + the
per-page noindex in community.html). This reads the live DB (public anon key + RLS read)
and emits one <url> per **Utah** community (community.html?community=<slug>) plus the
Utah development-tracker ZIP pages and the static pages. Zero-touch: as Utah communities
are added they appear here automatically; when a new state's data is made accurate,
widen INDEX_STATES below — no other edit.

Uses only the public anon key (same one shipped in community.html); no secrets.
"""
import json
import sys
import html
import urllib.parse
import urllib.request

SUPA = "https://qwnnmljucajnexpxdgxr.supabase.co"
ANON = ("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3"
        "bm5tbGp1Y2FqbmV4cHhkZ3hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA0MTAyOTgsImV4cCI6"
        "MjA5NTk4NjI5OH0.prpXB6lSIhWMAsdkkaxAfkvEodbojfUUyN4L4JbQE1U")
BASE = "https://homesignal.net"
# States whose community pages are accurate enough to advertise to search. Widen as
# per-state data accuracy lands (e.g. add "TX" once Travis is signed off). Utah only today.
INDEX_STATES = ["UT"]
STATIC = [("/", "weekly", "1.0"), ("/how-it-works.html", "monthly", "0.7"),
          ("/about.html", "monthly", "0.6"), ("/contact.html", "monthly", "0.5"),
          ("/privacy.html", "yearly", "0.3")]
STEP = 1000


def fetch_utah():
    """Utah communities: their slugs (for community?community=<slug> URLs) and the set of
    Utah ZIPs (to keep the development-tracker sitemap Utah-only too)."""
    slugs, zips, off = [], set(), 0
    state_filter = "in.(" + ",".join(INDEX_STATES) + ")"
    while True:
        url = (f"{SUPA}/rest/v1/communities?select=slug,zip_codes&state={state_filter}"
               f"&order=slug.asc.nullslast&limit={STEP}&offset={off}")
        req = urllib.request.Request(url, headers={"apikey": ANON, "Authorization": f"Bearer {ANON}"})
        with urllib.request.urlopen(req, timeout=90) as r:
            page = json.loads(r.read().decode("utf-8"))
        for x in page:
            if x.get("slug"):
                slugs.append(x["slug"])
            for z in (x.get("zip_codes") or []):
                zips.add(z)
        if len(page) < STEP:
            break
        off += STEP
    return slugs, zips


def fetch_dev_zips():
    """Every cached development ZIP page (homesignalmap.html?zip=<zip>). Zero-touch: as the
    development-tracker batch caches more ZIPs into development_reports, they appear here with
    no edit. Public anon read (RLS: public select on development_reports)."""
    zips, off = [], 0
    while True:
        url = (f"{SUPA}/rest/v1/development_reports?select=zip&order=zip.asc"
               f"&limit={STEP}&offset={off}")
        req = urllib.request.Request(url, headers={"apikey": ANON, "Authorization": f"Bearer {ANON}"})
        with urllib.request.urlopen(req, timeout=90) as r:
            page = json.loads(r.read().decode("utf-8"))
        zips += [x["zip"] for x in page if x.get("zip")]
        if len(page) < STEP:
            break
        off += STEP
    return zips


def url_el(loc, freq, pri):
    return (f"  <url>\n    <loc>{html.escape(loc)}</loc>\n"
            f"    <changefreq>{freq}</changefreq>\n    <priority>{pri}</priority>\n  </url>")


def main():
    slugs, ut_zips = fetch_utah()
    if not slugs:
        print("ERROR: fetched 0 Utah slugs — refusing to overwrite sitemap.xml")
        sys.exit(1)
    # development-tracker ZIP pages, Utah-only (index only Utah). 78617/other non-UT dev ZIPs
    # are real pages but stay out of the sitemap until their state is advertised.
    dev_zips = [z for z in fetch_dev_zips() if z in ut_zips]
    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             '<!-- GENERATED by scripts/gen_sitemap.py — INDEX ONLY UTAH (new-layout go-live).',
             '     Utah community + development pages only; the rest of the country is a real,',
             '     reachable page but noindexed until its data is accurate. do NOT hand-edit.',
             f'     {len(slugs)} Utah communities + {len(dev_zips)} Utah development ZIP pages + '
             f'{len(STATIC)} static pages. Regenerated on a schedule. -->',
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for loc, freq, pri in STATIC:
        lines.append(url_el(BASE + loc, freq, pri))
    for slug in slugs:
        lines.append(url_el(f"{BASE}/community.html?community={urllib.parse.quote(slug)}", "daily", "0.8"))
    for z in dev_zips:
        lines.append(url_el(f"{BASE}/homesignalmap.html?zip={urllib.parse.quote(z)}", "daily", "0.8"))
    lines.append("</urlset>")
    with open("sitemap.xml", "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    total = len(slugs) + len(dev_zips) + len(STATIC)
    print(f"wrote sitemap.xml (Utah-only): {len(slugs)} community + {len(dev_zips)} development + "
          f"{len(STATIC)} static = {total} total")
    if total > 45000:
        print("WARNING: approaching the 50,000-URL sitemap limit — split into a sitemap index soon.")


if __name__ == "__main__":
    main()
