#!/usr/bin/env python3
"""Generate sitemap.xml — INDEX ONLY the states in INDEX_STATES (UT + TX today).

The whole site uses the new layout; a state is advertised to search only once its
community pages carry accurate, sourced data (the rest of the country stays a real,
reachable page but noindexed until its data is accurate — see robots + the per-page
noindex in community.html). This reads the live DB (public anon key + RLS read) and
emits one <url> per PASS ZIP page (community.html?zip=<zip> — the new-layout page is
?zip=-keyed; the old ?community=<slug> URLs are no longer emitted because the new page
resolves only ?zip=) plus the matching development-tracker ZIP pages and the static
pages. Only data_quality='pass' ZIPs are advertised — coverage-coming pages are
noindexed, so putting them in the sitemap would contradict their robots value.
Zero-touch: new pass ZIPs appear automatically; to advertise a new state, widen
INDEX_STATES below — no other edit.

Uses only the public anon key (same one shipped in community.html); no secrets.
"""
import json
import sys
import html
import urllib.parse
import urllib.request

SUPA = "https://qwnnmljucajnexpxdgxr.supabase.co"
ANON = ("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3"
        "bm5tbGp1Y2FqbmV4cHhkZ3hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA0MTAyOTgsImV4cCI6"
        "MjA5NTk4NjI5OH0.prpXB6lSIhWMAsdkkaxAfkvEodbojfUUyN4L4JbQE1U")
BASE = "https://homesignal.net"
# States whose community pages are accurate enough to advertise to search. Widen as
# per-state data accuracy lands. TX added 2026-07-13 (statewide batch signed off).
INDEX_STATES = ["UT", "TX"]
STATIC = [("/", "weekly", "1.0"), ("/how-it-works.html", "monthly", "0.7"),
          ("/about.html", "monthly", "0.6"), ("/contact.html", "monthly", "0.5"),
          ("/privacy.html", "yearly", "0.3")]
STEP = 1000


def fetch_index_zips():
    """The advertised set: every PASS ZIP page in an INDEX_STATES state, straight from
    app_community_meta (the same table the page's data-quality gate reads). Only pass
    pages flip robots to index, so only pass pages belong in the sitemap."""
    zips, off = set(), 0
    state_filter = "in.(" + ",".join(INDEX_STATES) + ")"
    while True:
        url = (f"{SUPA}/rest/v1/app_community_meta?select=zip&state={state_filter}"
               f"&data_quality=eq.pass&order=zip.asc&limit={STEP}&offset={off}")
        req = urllib.request.Request(url, headers={"apikey": ANON, "Authorization": f"Bearer {ANON}"})
        with urllib.request.urlopen(req, timeout=90) as r:
            page = json.loads(r.read().decode("utf-8"))
        for x in page:
            if x.get("zip"):
                zips.add(x["zip"])
        if len(page) < STEP:
            break
        off += STEP
    return zips


def fetch_dev_zips():
    """Every cached development ZIP page (homesignalmap.html?zip=<zip>). Zero-touch: as the
    development-tracker batch caches more ZIPs into development_reports, they appear here with
    no edit. Public anon read (RLS: public select on development_reports)."""
    zips, off = [], 0
    while True:
        url = (f"{SUPA}/rest/v1/development_reports?select=zip&order=zip.asc"
               f"&limit={STEP}&offset={off}")
        req = urllib.request.Request(url, headers={"apikey": ANON, "Authorization": f"Bearer {ANON}"})
        with urllib.request.urlopen(req, timeout=90) as r:
            page = json.loads(r.read().decode("utf-8"))
        zips += [x["zip"] for x in page if x.get("zip")]
        if len(page) < STEP:
            break
        off += STEP
    return zips


def url_el(loc, freq, pri):
    return (f"  <url>\n    <loc>{html.escape(loc)}</loc>\n"
            f"    <changefreq>{freq}</changefreq>\n    <priority>{pri}</priority>\n  </url>")


def main():
    index_zips = fetch_index_zips()
    if not index_zips:
        print("ERROR: fetched 0 pass ZIPs — refusing to overwrite sitemap.xml")
        sys.exit(1)
    # development-tracker ZIP pages for the same advertised set. Other cached dev ZIPs
    # are real pages but stay out of the sitemap until their state is advertised.
    dev_zips = [z for z in fetch_dev_zips() if z in index_zips]
    comm_zips = sorted(index_zips)
    states = "+".join(INDEX_STATES)
    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             f'<!-- GENERATED by scripts/gen_sitemap.py — INDEX ONLY {states} (pass pages).',
             '     Community + development ZIP pages for advertised states only; the rest of the',
             '     country is a real, reachable page but noindexed until its data is accurate.',
             f'     do NOT hand-edit. {len(comm_zips)} community ZIP pages + {len(dev_zips)} '
             f'development ZIP pages + {len(STATIC)} static pages. Regenerated on a schedule. -->',
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for loc, freq, pri in STATIC:
        lines.append(url_el(BASE + loc, freq, pri))
    for z in comm_zips:
        lines.append(url_el(f"{BASE}/community.html?zip={urllib.parse.quote(z)}", "daily", "0.8"))
    for z in dev_zips:
        lines.append(url_el(f"{BASE}/homesignalmap.html?zip={urllib.parse.quote(z)}", "daily", "0.8"))
    lines.append("</urlset>")
    with open("sitemap.xml", "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    total = len(comm_zips) + len(dev_zips) + len(STATIC)
    print(f"wrote sitemap.xml ({states}): {len(comm_zips)} community + {len(dev_zips)} development + "
          f"{len(STATIC)} static = {total} total")
    if total > 45000:
        print("WARNING: approaching the 50,000-URL sitemap limit — split into a sitemap index soon.")


if __name__ == "__main__":
    main()
