#!/usr/bin/env python3
"""Emit docs/geo-reconciler-install.sql — the reconciler as DEFINITIONS ONLY.

WHY THIS EXISTS. docs/geo-source-scoped-reconcile.sql cannot be used as a passive
installer and is not a definitions file. Verified at dedb7db:

  * it carries FOUR bare, top-level resident-geography DML statements -
    `delete from geo.zip_authoritative_membership`, `insert into` the same,
    and the identical pair for geo.zip_authoritative_marker - so "installing"
    it would MUTATE the very planes this workstream must not touch;
  * those statements are parameterised with psql bind placeholders (`:keys`,
    `:run`) which are not valid SQL in any driver - the file cannot execute as
    written even if that were wanted;
  * it calls `geo.n5_expected_marker(:keys)`, and THAT FUNCTION IS DEFINED
    NOWHERE IN THE REPOSITORY. `git grep n5_expected_marker` at dedb7db returns
    only call sites, never a definition. The file defines exactly one function,
    geo.n5_expected_membership.

So the reconciler has never existed as an installable artifact. The canonical
implementation is scripts/n5_reconcile_sql.py (STAGES + render), whose only
consumer until now was scripts/geo_steady_state_fixture.py, which wraps the
rendered stages into a function IN A FIXTURE SCHEMA. This generator does the same
wrapping against PROD_RELS so the production object exists as a reviewable
definition.

DEFINING A FUNCTION DOES NOT RUN IT. The DML lives inside the body and executes
only when something calls geo.n5_reconcile(...). Nothing does: the worker is OFF,
the scheduler is OFF, and no handoff calls it - the handoffs only enqueue.

stdlib only. Writes SQL to stdout; never connects to anything.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import n5_reconcile_sql as R  # noqa: E402

# The same rule parameters the accepted fixture pins.
RULE = {"MIN_LINE_M": 250.0, "MIN_AREA_M2": 1000.0, "D_M": 1000.0, "DTAG": 1000}


def build():
    rendered = {}
    for name, stage in R.STAGES:
        sql = R.render(stage, "_keys", "_run", rels=R.PROD_RELS, rule_params=RULE)
        left = R.unresolved_placeholders(sql)
        if left:
            raise SystemExit(f"STOP: stage {name} left placeholders unresolved: {left}")
        rendered[name] = sql

    stage1 = rendered["geometry"]
    rest = "\n".join(rendered[n] for n, _ in R.STAGES if n != "geometry")

    return f"""-- ============================================================================
-- SOURCE-KEY RECONCILER — EXECUTABLE DEFINITIONS ONLY. PARKED, NOT APPLIED.
--
-- GENERATED by scripts/gen_geo_reconciler_install.py from the canonical
-- implementation in scripts/n5_reconcile_sql.py. Do not hand-edit: regenerate.
--
-- ⛔ THIS REPLACES docs/geo-source-scoped-reconcile.sql IN THE INSTALL MANIFEST.
-- That file is NOT a definitions file and must never be applied as one:
--   (a) it carries four BARE, TOP-LEVEL resident-geography DML statements
--       against geo.zip_authoritative_membership and geo.zip_authoritative_marker,
--       so applying it would mutate the planes this workstream must not touch;
--   (b) they are parameterised with psql bind placeholders (:keys, :run), which
--       are not valid SQL in any driver, so it cannot execute as written; and
--   (c) it calls geo.n5_expected_marker(:keys), WHICH IS DEFINED NOWHERE IN THE
--       REPOSITORY - it defines only geo.n5_expected_membership.
-- Measured at dedb7db 2026-09-20. Keep that file as the design record; install this.
--
-- 🔑 DEFINING IS NOT RUNNING. Every DML statement below sits INSIDE a function
-- body. Creating the function compiles it and executes none of it. Reconciliation
-- happens only when something CALLS geo.n5_reconcile(_keys, _run), and after a
-- passive install nothing does: the lifecycle handoffs only ENQUEUE, no worker
-- exists, and no cron job references it. Installation therefore performs ZERO
-- reconciliation executions and touches ZERO resident geography.
--
-- BOUNDED BY CONSTRUCTION: _keys is the sole bound and appears in every stage, so
-- a caller cannot widen the blast radius by editing one stage. A NULL or empty
-- _keys does nothing.
--
-- STAGE ORDER IS LOAD-BEARING: geometry -> boundary -> membership -> markers.
-- Markers are reconciled AFTER membership because the marker build reads
-- membership. The order below is the order in scripts/n5_reconcile_sql.py::STAGES
-- and is not re-typed here.
--
-- OWNERSHIP / GRANTS / EXECUTION ROLE
--   owner:      postgres (the role applying the migration)
--   grants:     none. `revoke all ... from public` below is deliberate - no anon
--               or authenticated role may invoke the reconciler. The future worker
--               runs as the service role, which bypasses RLS.
--   RLS:        this function writes geo.* planes; it must be called by a role
--               that can, i.e. the owner or service_role. It is intentionally NOT
--               security definer: a definer-rights reconciler callable from
--               PostgREST would be a privilege-escalation surface.
-- ============================================================================

begin;

create or replace function geo.n5_reconcile_stage1(_keys text[], _run text)
returns void
language plpgsql
set search_path = pg_catalog, public, pg_temp
as $s1$
begin
{stage1}
end $s1$;
revoke all on function geo.n5_reconcile_stage1(text[], text) from public;

create or replace function geo.n5_reconcile(_keys text[], _run text)
returns void
language plpgsql
set search_path = pg_catalog, public, pg_temp
as $rec$
begin
  if _keys is null or cardinality(_keys) = 0 then return; end if;
  perform geo.n5_reconcile_stage1(_keys, _run);
{rest}
end $rec$;
revoke all on function geo.n5_reconcile(text[], text) from public;

comment on function geo.n5_reconcile(text[], text) is
  'Source-key scoped reconciler. Bounded by _keys, which appears in every stage. '
  'Generated from scripts/n5_reconcile_sql.py by scripts/gen_geo_reconciler_install.py; '
  'regenerate rather than hand-edit. Defining this function executes nothing - '
  'reconciliation happens only when it is called, and after a passive install '
  'nothing calls it.';

do $post$
begin
  -- The cron read is WRAPPED so a missing or unreadable catalog warns rather than
  -- rolling back a correct install - the same shape CLAUDE.md records for the
  -- coverage-state window migration. An unevaluated check must SAY it was
  -- unevaluated; it must never pass silently.
  begin
    if (select count(*) from cron.job where jobname ~* 'geo|reconcil|n5') <> 0 then
      raise exception 'A geography cron job exists. The scheduler must remain OFF.';
    end if;
  exception
    when insufficient_privilege or undefined_table or invalid_schema_name then
      raise warning 'SCHEDULER CHECK NOT EVALUATED: cron catalog unreadable (%). '
                    'Confirm the scheduler is OFF by hand before approving.', sqlerrm;
  end;
  begin
    if (select count(*) from pg_trigger t
         where t.tgrelid = 'public.app_projects'::regclass and not t.tgisinternal) <> 0 then
      raise exception 'A trigger appeared on public.app_projects. None is authorised.';
    end if;
  exception
    when insufficient_privilege or undefined_table then
      raise warning 'TRIGGER CHECK NOT EVALUATED: public.app_projects unreadable (%). '
                    'Confirm no trigger exists by hand before approving.', sqlerrm;
  end;
end $post$;

commit;
"""


if __name__ == "__main__":
    sys.stdout.write(build())
