#!/usr/bin/env python3
"""Single source of truth for the lifecycle-handoff splice.

Every downstream artifact - the read-only verifier, the rollback, and the
isolated fixture - is GENERATED from docs/geo-lifecycle-handoff-install.sql by
this module. Nothing retypes an anchor. That is rule 7 ("never transcribe a list
into a migration; compute the set or generate the SQL from the source of truth")
applied to the one artifact where a single mistyped byte silently edits the
national materializer.

stdlib only. Never connects to anything.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
INSTALL = os.environ.get("GEO_HANDOFF_INSTALL") or os.path.join(
    HERE, "..", "docs", "geo-lifecycle-handoff-install.sql")

# label between single quotes, then $f$find$f$, then $r$repl$r$
_TRIPLE = re.compile(
    r"^\s*'((?:[^']|'')+)',\s*\n\$f\$(.*?)\$f\$,\s*\n\$r\$(.*?)\$r\$",
    re.S | re.M,
)


def triples(path=INSTALL):
    src = open(path, encoding="utf-8").read()
    i = src.index("_pairs := array[")
    j = src.index("\n  ];", i)
    body = src[i:j]
    out = [(m.group(1), m.group(2), m.group(3)) for m in _TRIPLE.finditer(body)]
    if len(out) != 6:
        raise SystemExit(f"STOP: expected 6 anchor triples, parsed {len(out)}")
    for label, find, repl in out:
        if not find or not repl:
            raise SystemExit(f"STOP: empty anchor in {label!r}")
        if find == repl:
            raise SystemExit(f"STOP: no-op anchor in {label!r}")
    return out


def _lit(s):
    """Dollar-quote a literal with a tag that cannot occur inside it."""
    for tag in ("$q$", "$qq$", "$qqq$", "$z9$"):
        if tag not in s:
            return tag + s + tag
    raise SystemExit("STOP: no safe dollar-quote tag")


def verify_sql(expect_before):
    """READ-ONLY. Applies the splice in a SELECT and returns fingerprints only.

    Applies NOTHING. Used against production to prove, before any approval, that
    every anchor is unique and the transformation is exactly reversible.
    """
    t = triples()
    steps = ["select pg_get_functiondef('public.app_refresh_zip(text)'::regprocedure) as t0"]
    # forward
    for n, (_, find, repl) in enumerate(t):
        steps.append(
            f"s{n} as (select t{n} , replace(t{n}, {_lit(find)}, {_lit(repl)}) as t{n+1} from "
            + (f"s{n-1}" if n else "src") + ")"
        )
    ctes = ["src as (" + steps[0] + ")"] + steps[1:]
    N = len(t)
    # reverse, off the final forward text
    back = f"t{N}"
    for n in range(N - 1, -1, -1):
        back = f"replace({back}, {_lit(t[n][2])}, {_lit(t[n][1])})"
    counts = ",\n  ".join(
        "(length(t0) - length(replace(t0, {f}, ''))) / length({f}) as anchor_{n}_in_original".format(
            f=_lit(t[n][1]), n=n)
        for n in range(N)
    )
    return (
        "with " + ",\n".join(ctes) + f"\nselect\n"
        f"  md5(t0) as md5_before,\n"
        f"  '{expect_before}' as md5_expected_before,\n"
        f"  md5(t0) = '{expect_before}' as precondition_ok,\n"
        f"  md5(t{N}) as md5_after_expected,\n"
        f"  length(t0) as len_before, length(t{N}) as len_after,\n"
        f"  md5({back}) = md5(t0) as excision_reconstructs_original,\n"
        f"  (length(t{N}) - length(replace(t{N}, 'geo.enqueue_work', ''))) / length('geo.enqueue_work') as handoff_count,\n"
        f"  position('get diagnostics _stale = row_count;' in t{N}) = 0 as get_diagnostics_replaced,\n"
        f"  {counts}\n"
        f"from s{N-1};"
    )


def rollback_sql(expect_before, expect_after):
    t = triples()
    rev = "\n".join(
        f"  _out := replace(_out, {_lit(repl)}, {_lit(find)});"
        for _, find, repl in reversed(t)
    )
    return f"""-- GENERATED by scripts/geo_handoff_splice.py from
-- docs/geo-lifecycle-handoff-install.sql. Do not hand-edit: regenerate.
--
-- ROLLBACK for the lifecycle-handoff splice. Reverses every replacement and
-- asserts the result is md5-identical to the pre-install body, so a rollback
-- can never leave a third, half-reverted version behind.
--
-- It refuses to run unless the live body is EXACTLY the post-install one. If
-- another session amended app_refresh_zip after the install, this file is not
-- safe and the reversal must be re-derived against the new body.
begin;
do $rb$
declare _out text; _before text;
begin
  _out := pg_get_functiondef('public.app_refresh_zip(text)'::regprocedure);
  _before := md5(_out);
  if _before <> '{expect_after}' then
    raise exception 'ROLLBACK PRECONDITION FAIL: live md5 is %, expected the post-install %. '
                    'Re-derive the reversal against the current body.', _before, '{expect_after}';
  end if;
{rev}
  if md5(_out) <> '{expect_before}' then
    raise exception 'ROLLBACK DID NOT RECONSTRUCT THE ORIGINAL: got %, expected %.',
      md5(_out), '{expect_before}';
  end if;
  execute _out;
  if md5(pg_get_functiondef('public.app_refresh_zip(text)'::regprocedure)) <> '{expect_before}' then
    raise exception 'ROLLBACK POST-CHECK FAILED.';
  end if;
  raise notice 'app_refresh_zip rolled back to %', '{expect_before}';
end $rb$;
commit;

-- The passive core is NOT dropped here. geo.n5_reconcile_queue and
-- geo.enqueue_work are inert once the handoffs are gone: nothing calls the
-- function and nothing reads the table. Dropping them is a separate, deliberate
-- act - see docs/geo-lifecycle-handoff-rollback-core.sql.
"""


if __name__ == "__main__":
    what = sys.argv[1] if len(sys.argv) > 1 else "triples"
    if what == "triples":
        for label, find, repl in triples():
            print(f"--- {label}\n  find {len(find):5d}B  repl {len(repl):5d}B")
    elif what == "verify":
        sys.stdout.write(verify_sql(sys.argv[2]))
    elif what == "rollback":
        sys.stdout.write(rollback_sql(sys.argv[2], sys.argv[3]))
