-- ============================================================================
-- app_refresh_zip(_zip) — the reproducible materializer (APPLIED to prod).
-- Rebuilds app_projects / app_changes / app_community_meta for ONE ZIP from REAL
-- sources already in the DB — the get-address-report engine's `development_reports`
-- (TDLR/TABS building permits + EPA/TCEQ facilities, every row with a record_url)
-- and the CivicClerk `meetings` for the Travis County root — quality-gated.
--
--   * projects/changes: only records with a non-empty record_url are written
--     (anti-fabrication: no source_ref → not written).
--   * data_quality = 'pass' only when the ZIP produced ≥1 sourced project;
--     otherwise 'coverage_coming' (the app renders a coverage-coming state, never blank).
--   * Idempotent: deletes+reinserts that ZIP each run.
--
-- Run for one ZIP:      select public.app_refresh_zip('78617');
-- Run for all Travis:   select z.zip, public.app_refresh_zip(z.zip)
--                       from (select distinct unnest(zip_codes) zip from public.communities
--                             where county='Travis' and state='TX') z;
--
-- The homesignal-ingest workflow calls this per ZIP AFTER the get-address-report
-- engine (pg_net, Postgres egress) refreshes that ZIP's development_report — so a
-- ZIP only "passes" once real permit/facility records exist for it.
--
-- The full function body is the applied migration `app_refresh_zip_materializer`
-- (see supabase migration history) and docs/phase1-app-schema.sql for the tables.
-- ============================================================================
-- (function definition mirrored in the migration; see project migration
--  `app_refresh_zip_materializer`. Kept here as the DDL-of-record pointer.)

-- UPDATE 2026-07-13: app_refresh_zip is now COUNTY-GENERIC (uses each ZIP's real
-- county name, not a hardcoded one) and accepts source links in EITHER `record_url`
-- (TX TDLR/TABS permits) OR `url` (Utah PMN planning notices). Applied via migrations
-- app_refresh_zip_county_generic + app_refresh_zip_url_or_record_url.
--
-- UPDATE 2026-07-13 (b): added a REAL-FACILITY FALLBACK + a CIVIC bucket so a ZIP with
-- no per-ZIP permit feed still passes on its actual EPA records instead of showing
-- "coverage coming." Applied via migration app_refresh_zip_facilities_and_civic:
--   * app_projects: if a ZIP produced 0 development-permit projects, fall back to the
--     development_report's EPA FRS/ECHO FACILITIES (relevance NOT IN ('development',
--     'civic'), a real link + a non-empty label required) written status='Operating',
--     developer='EPA FRS · registry <id>', source_ref = the echo.epa.gov record URL.
--     Facilities carry no `relevance` tag, so the earlier `relevance='facility'` filter
--     wrongly matched 0 — the fix filters by exclusion + requires a link.
--   * app_changes: PMN civic notices (relevance='civic') now surface as category
--     'Government & civic'.
-- data_quality still = 'pass' ONLY when the ZIP produced >=1 sourced project (permit OR
-- real facility); genuinely-empty ZIPs stay 'coverage_coming' — never blank, never faked.
--
-- Re-ran for all 137 development_reports ZIPs → ALL 136 modeled UTAH ZIPs now PASS on
-- real sourced records (DB-verified): Box Elder 18, Cache 19, Davis 14, Salt Lake 36,
-- Tooele 8, Utah 27, Weber 14 = 136/136 pass, 0 coverage_coming. 1,632 UT app_projects,
-- 0 missing a source_ref (anti-fabrication clean). Salt Lake (was coverage_coming —
-- meetings only, no per-ZIP permit feed) flipped to pass on its real EPA FRS facilities
-- (e.g. 84101: Grain Craft, Energy Solutions, Bulk Cement Terminal — each an
-- echo.epa.gov detailed-facility-report link). Data-only — /app/ reads app_* generically,
-- no deploy.
--
-- UPDATE 2026-07-13 (c): record_kind split + auto-sync cron. Applied via migrations
-- app_refresh_zip_record_kind_split and app_content_refresh_cron:
--   * app_projects gains `record_kind` ('development' | 'facility'); app_refresh_zip now
--     ALWAYS materializes the report's EPA/ECHO facilities as record_kind='facility'
--     (status 'Operating'), separate from development permits/planning (record_kind=
--     'development'). data.js splits projects() (development-only) from facilities().
--   * app_refresh_all() loops app_refresh_zip over every development_reports ZIP.
--   * pg_cron job 'app-content-refresh' runs app_refresh_all() daily at 09:20 UTC — 12 min
--     AFTER dev_refresh_collect (09:08) — so app_* never drifts from the live engine cache.
--     (Found drift: the nightly dev_refresh had aged out concluded hearings >90d, so app_*
--     was showing more development than the engine had — Cache 5→1, Davis 6→2, Utah 11→4 on
--     resync. All 136 UT ZIPs still PASS on the facility floor.)
--
-- UPDATE 2026-07-13 (d): AUDIT FIXES — point-only projects, real statuses, derived meta.
-- Applied via migrations app_refresh_zip_point_projects_honest_meta +
-- app_refresh_zip_recency_order_keep_approved:
--   * record_kind='development' ONLY for parcel-precise sites (scope='point' — ArcGIS/TABS
--     permits & petitions). Jurisdiction-wide PMN notices/agendas ("Public Hearing",
--     "Planning Commission Meeting Agenda …") are NOT projects — they materialize into
--     app_changes as category 'Planning & zoning' (real records, civic rendering). Kills
--     the junk project names + the ×N-per-county-ZIP duplication the audit found.
--   * status comes from the engine's bucket/decided — 'Proposed'/'Approved'/'Active'/
--     'Operating'/'Decided'; unknown -> 'On file'. NEVER defaulted (the audit found all
--     1,284 rows stamped 'Proposed', including 32 genuinely-Approved SLC petitions and
--     items titled "…Meeting Cancelled"). Projects ordered by recency (a proposed-first
--     sort + cap starved every Approved record out; verified fixed: UT 376 Proposed +
--     32 Approved, TX 78617 23/21/4 Proposed/Approved/Operating).
--   * component_scores pct = the real record count capped at 100 (was hardcoded 82/55/45,
--     which made the derived "Community score" 61 on every page); civic_activity derived
--     from the upcoming-meeting count (was the literal 'Active').
--   * data_quality gate counts projects + facilities + sourced notices/meetings, so
--     notice-only ZIPs keep their pass (verified: 136/136 UT still pass).
--
-- UPDATE 2026-07-13 (e): DEL VALLE AUDIT — count consistency + sample-home honesty.
-- Applied via migration app_meta_scores_match_page_concepts:
--   * component_scores keys/labels now describe the SAME concepts the pages render,
--     with TRUE (uncapped) counts: 'development projects' = parcel-precise dev records
--     in the cache (78617: 427; Box Elder 84302: honestly 0), 'planning & civic notices'
--     = the ZIP's sourced notice/meeting rows, 'regulated facilities' = the cache's
--     facility count. Pages read the label as the true total and caption their capped
--     lists "latest N shown" (78617 previously showed tile=48 vs bar label=427).
--   * Front-end pair (same commit): demo sample homes are stamped sample:true in
--     lib/data.js, and community.html refuses to measure real records from the
--     fictional Del Valle demo address even on its own ZIP; 'Operating' projects
--     join the active card group so built/operating permits can be carded.

-- ---------------------------------------------------------------------------
-- Applied 2026-07-14 via migration `app_meta_indexable_substance_gate`
-- (founder-approved PLAN.md §11 threshold c — the nationwide index policy):
--   * app_community_meta gains `indexable boolean not null default false`.
--   * app_refresh_zip stamps it from the TRUE uncapped totals:
--       indexable := (pass) AND (_ndp > 0 OR _nfc >= 3)
--     i.e. >=1 parcel-precise development record OR >=3 facility records.
--     Empty / coverage_coming rows are always false. This is the ONE place the
--     threshold lives; community.html, homesignalmap.html, gen_sitemap.py and
--     both CI verifiers only read the flag.
--   * Backfilled with select public.app_refresh_all();  (942 rows; flag counts
--     at apply time: UT 106 / TX 647 / CO 131 / NM 2 = 886 of 932 pass pages.)
-- REVERT: re-apply the pre-2026-07-14 app_refresh_zip body (this file's history)
-- and git-revert the nationwide-substance-gate PR; the column is additive and
-- may remain (ignored by state-scoped readers).

-- ---------------------------------------------------------------------------
-- Applied 2026-07-17 via migrations `app_projects_facility_entity_columns` +
-- `app_refresh_zip_facility_entity` (the regulated-facilities-as-entities build,
-- docs/regulated-facilities-entity-spec):
--   * app_projects gains `registry_id text` (the FRS business key) and
--     `facility_env jsonb` — the engine's geo-matched environmental record carried
--     verbatim from development_reports.sites onto each record_kind='facility' row:
--       { link_type, epa?: { in_violation[], snc?, quarters_nc?, inspections?,
--         action_year?, penalty_count?, current_as_of,
--         permits?[{npdes_id,statute,status,type}],        -- engine v21
--         permit_status?, compliance_tracking_on? },        -- engine v21
--         tceq?: { name, status, programs[] }, tceq_rn?, tceq_url? }
--     Built with jsonb_strip_nulls so absent stays absent; NULL when the cached site
--     carries no env at all (pre-v19 rows) and on every record_kind='development' row.
--   * The facility insert in app_refresh_zip is the ONLY changed statement; everything
--     else is byte-identical to the app_meta_indexable_substance_gate body.
--   * Readers: lib/data.js facilities() passes the columns through untouched;
--     lib/templates.js HS.fac.interpret/signals/links renders the §5 interpretation
--     (dossier = development.html?id=<uuid> branching on record_kind='facility';
--     sidebar = maps.html "Regulated facilities · nearby"). permit_status is absent
--     until the v21 engine deploy + re-cache reaches a ZIP — the UI renders the
--     honest "permit status not yet confirmed" state, never a guess (spec §8).
-- REVERT: drop the two columns (additive; readers null-check) and re-apply the
-- prior function body from this file's history.
