-- GENERATED by test/dc_atlas_validation_pg/build_admission.py. Do not edit.

-- STAGE 10 ROLLBACK: withdraw Atlas (compute_atlas/facilities) from the admission switch,

-- restoring Phase A's deployed Epoch-only body. Tested offline; applied only by

-- dc-atlas-admission-apply.yml with confirm=ROLLBACK-ATLAS-STAGE-10.

-- One transaction: drift guard, the Phase A switch and its comment, in-transaction post-condition.

begin;

do $guard$
begin
  if (select md5(p.prosrc) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
       where n.nspname = 'public' and p.proname = 'dc_derived_address_admitted') is distinct from
     '31cb6c9e7481311ab33042a8845c9276'
     or not public.dc_derived_address_admitted('compute_atlas', 'facilities')
     or not public.dc_derived_address_admitted('epoch_ai', 'data_centers') then
    raise exception 'DRIFT: the live admission switch is not the stage 10 admitted one. Nothing rolled back.';
  end if;
end $guard$;

-- ===== the switch as Phase A deployed it (build_apply.py PHASE_A_REGION) =====

create or replace function public.dc_derived_address_admitted(p_source_key text, p_distribution_key text)
returns boolean
language sql
immutable
set search_path to 'public', 'pg_temp'
as $$ select (p_source_key, p_distribution_key) in (('epoch_ai', 'data_centers')) $$;

comment on function public.dc_derived_address_admitted(text, text) is
'STEP 3D. Deployment gate: whether an extraction''s derivations may reach geography and identity.
Binary admission of a reviewed extraction, never a rank. See the header of this section.';

do $post$
begin
  if public.dc_derived_address_admitted('compute_atlas', 'facilities')
     or not public.dc_derived_address_admitted('epoch_ai', 'data_centers')
     or public.dc_derived_address_admitted('compute_atlas', 'other')
     or public.dc_derived_address_admitted('some_new_source', 'facilities')
     or (select md5(p.prosrc) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
          where n.nspname = 'public' and p.proname = 'dc_derived_address_admitted')
        is distinct from 'cd968b64ada7adaee18a4dc8be0c4a4b'
  then
    raise exception 'POST-CONDITION: the switch does not admit exactly Epoch data_centers (Phase A). Rolled back.';
  end if;
end $post$;

commit;
