-- GENERATED by test/dc_atlas_validation_pg/build_apply.py from the DDL of record. Do not edit.

-- PHASE A of Atlas coordinate validation: evidence acquisition only. Atlas is NOT admitted.

-- One transaction: the drift guard, then the changed Step 3D, 3A and 3B objects, in dependency order.

begin;

do $guard$
declare r record; bad text := '';
begin
  for r in select * from (values ('dc_adjudicate_pair', '3918d905e8eaad3ced272ab02c88b9aa'), ('dc_derived_point_verdict', '4cd5b97def7d6179900cd95ec452d9a7'), ('dc_geocode_input', '23695d57dae07ca5d2203a562dbb1fdd'), ('dc_resolve_canonical', 'ba2a7505919bdb8c07f462ca42b84974'), ('dc_resolve_geography', 'd9a80300c6f982ef30851aeac810abfc'), ('dc_site_claims_conflict', '33d7d5e99f4cae4883e843e22bfd03da'), ('map1_dc_zip_members', '9fc1c9f51375f25db5658a14ca36937c')) x(fn, want) loop
    if (select md5(p.prosrc) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
         where n.nspname = 'public' and p.proname = r.fn) is distinct from r.want then
      bad := bad || ' ' || r.fn;
    end if;
  end loop;
  if exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
              where n.nspname = 'public' and p.proname in ('dc_publisher_stated_address', 'dc_geocodable_site_address', 'dc_derived_address_admitted')) then
    bad := bad || ' (a function this apply introduces already exists)';
  end if;
  if bad <> '' then
    raise exception 'DRIFT: live definition(s) no longer match main@f9d1326:%. Nothing applied.', bad;
  end if;
end $guard$;

-- ===== STEP 3D  docs/dc-step3d-derived-location.sql (changed objects) =====

-- ── INPUT RULE, TWO SEPARATE QUESTIONS (2026-09-24, Atlas address validation) ──────────────
-- The rule used to be one Epoch-only branch that both READ Epoch's payload and DECIDED whether
-- the result was a site address; every other source got NO_GEOCODE_RULE. So a publisher that
-- states a street address beside its own point (Compute Atlas: 876 of 2,187 current records carry
-- a `street`) was never checked against that address, and Lancaster was caught only because Epoch
-- happened to state the same address. The two questions are now two functions:
--
--   1. PUBLISHER SCHEMA EXTRACTION -- dc_publisher_stated_address. Where does this source's payload
--      state an address, and what does it say? Source-keyed, because payload schemas genuinely
--      differ (Epoch: one `Address` string + `Country`; Atlas: `location.street/city/state/
--      postalCode`). It returns the publisher's words as ONE line and decides nothing about them.
--   2. GEOCODABILITY POLICY -- dc_geocodable_site_address. Is that line specific enough to send to
--      the production ladder? ONE generic rule for every source, knowing no source name.
--
-- dc_geocode_input composes the two and keeps its signature, so every consumer is unchanged.
-- Neither function decides geography, ZIP or identity.

-- 1. EXTRACTION. Per source; returns (extraction, address_line, reason):
--      STATED       the publisher states an address; address_line is it, verbatim modulo whitespace
--      NOT_US       the publisher places the record outside the United States
--      NO_RULE      no extraction rule for this source (nothing is ever geocoded for it)
--    Atlas composes its structured fields in the SAME shape the 2026-09-24 calibration geocoded
--    (docs/dc-geocode-probe-inputs.sql, kind 'calib': "street, city, state zip"), so the measured
--    2,000 m bound applies to exactly this input. A field the publisher left empty is omitted,
--    never guessed; a blank street yields an empty line, which the policy rejects as BLANK.
create or replace function public.dc_publisher_stated_address(p_source_key text,
                                                              p_distribution_key text,
                                                              p_payload jsonb)
returns table(extraction text, address_line text, reason text)
language plpgsql
immutable
set search_path to 'public', 'pg_temp'
as $fn$
declare
    loc jsonb;
    st  text;
begin
    if p_source_key = 'epoch_ai' and p_distribution_key = 'data_centers' then
        if coalesce(p_payload->>'Country', '') <> 'United States' then
            return query select 'NOT_US'::text, null::text, 'the publisher places this record outside the United States'::text;
            return;
        end if;
        return query select 'STATED'::text,
            btrim(regexp_replace(coalesce(p_payload->>'Address', ''), '\s+', ' ', 'g')),
            'Epoch Address field'::text;
        return;
    end if;
    if p_source_key = 'compute_atlas' and p_distribution_key = 'facilities' then
        loc := coalesce(p_payload->'location', '{}'::jsonb);
        st := btrim(regexp_replace(coalesce(loc->>'street', ''), '\s+', ' ', 'g'));
        return query select 'STATED'::text,
            case when st = '' then ''
                 else concat_ws(', ', st,
                                nullif(btrim(regexp_replace(coalesce(loc->>'city', ''), '\s+', ' ', 'g')), ''),
                                nullif(btrim(concat_ws(' ',
                                    nullif(btrim(coalesce(loc->>'state', '')), ''),
                                    nullif(btrim(coalesce(loc->>'postalCode', '')), ''))), ''))
            end,
            'Atlas location.street, city, state postalCode'::text;
        return;
    end if;
    return query select 'NO_RULE'::text, null::text, 'no address extraction rule for this source'::text;
end;
$fn$;

comment on function public.dc_publisher_stated_address(text, text, jsonb) is
'STEP 3D. Publisher SCHEMA extraction only: where a source states its address, as one line. Keyed by
source because payload schemas differ; decides nothing about the line (dc_geocodable_site_address does).';

-- 2. POLICY. Is this line a geocodable SITE address? (precondition only; one rule for every source)
-- A house number and a locality are REQUIRED before anything is sent to a geocoder. Without a
-- locality a geocoder may place the address in any town ("13360 Miller Rd NW"); without a house
-- number it returns a road or a place ("Co Rd 42, Montgomery" was matched to 42 COUNTY CT, a
-- different street). A NUMBER RANGE ("14436-14998 Fairview Rd") names a frontage, not a point
-- (this also refuses Hawaii's hyphenated house numbers, "92-384 Farrington Highway": a missed
-- validation, never a wrong one). Passing this gate proves nothing about the result: output
-- quality is judged separately (dc_derived_point_verdict).
create or replace function public.dc_geocodable_site_address(p_line text)
returns table(input_quality text, geocoder_query text, reason text)
language plpgsql
immutable
set search_path to 'public', 'pg_temp'
as $fn$
declare
    a    text := btrim(regexp_replace(coalesce(p_line, ''), '\s+', ' ', 'g'));
    rest text;
    states constant text := '(AL|AK|AZ|AR|CA|CO|CT|DE|FL|GA|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|OH|OK|OR|PA|RI|SC|SD|TN|TX|UT|VT|VA|WA|WV|WI|WY|DC)';
    state_names constant text := '(Alabama|Alaska|Arizona|Arkansas|California|Colorado|Connecticut|Delaware|Florida|Georgia|Hawaii|Idaho|Illinois|Indiana|Iowa|Kansas|Kentucky|Louisiana|Maine|Maryland|Massachusetts|Michigan|Minnesota|Mississippi|Missouri|Montana|Nebraska|Nevada|New Hampshire|New Jersey|New Mexico|New York|North Carolina|North Dakota|Ohio|Oklahoma|Oregon|Pennsylvania|Rhode Island|South Carolina|South Dakota|Tennessee|Texas|Utah|Vermont|Virginia|Washington|West Virginia|Wisconsin|Wyoming|District of Columbia)';
begin
    if a = '' then
        return query select 'BLANK'::text, null::text, 'the publisher states no address'::text;
    elsif a !~ '^\d' or a ~ '^\d{5}(-\d{4})?$' then   -- a bare ZIP names an area, not a site
        return query select 'NO_HOUSE_NUMBER'::text, null::text, 'no house number: a road, place or area is not a site address'::text;
    elsif a ~ '^\d+[A-Za-z]?\s*[-–]\s*\d+' then
        return query select 'HOUSE_NUMBER_RANGE'::text, null::text, 'a house-number range names a frontage, not a point'::text;
    else
        rest := regexp_replace(a, '^\S+\s*', '');   -- a 5-digit HOUSE number is not a ZIP
        if rest ~ '\m\d{5}(-\d{4})?\M'
           or a ~ (',\s*' || states || '(\s|,|$)')
           or a ~* ('\m' || state_names || '\M') then
            return query select 'GEOCODABLE'::text, a, 'house number and locality present'::text;
        else
            return query select 'NO_LOCALITY'::text, null::text, 'no ZIP or state: the geocoder could place this street in any town'::text;
        end if;
    end if;
end;
$fn$;

comment on function public.dc_geocodable_site_address(text) is
'STEP 3D. The ONE geocodability policy, for every source: GEOCODABLE requires a single house number
and a locality. A PRECONDITION, never a verdict on the result. Knows no source name.';

-- The composition every consumer reads (signature unchanged since 2026-09-24).
create or replace function public.dc_geocode_input(p_source_key text, p_distribution_key text,
                                                   p_payload jsonb)
returns table(input_quality text, geocoder_query text, reason text)
language plpgsql
immutable
set search_path to 'public', 'pg_temp'
as $fn$
declare
    x record;
begin
    select * into x from public.dc_publisher_stated_address(p_source_key, p_distribution_key, p_payload);
    if x.extraction = 'NO_RULE' then
        return query select 'NO_GEOCODE_RULE'::text, null::text, 'no address rule for this source'::text;
    elsif x.extraction = 'NOT_US' then
        return query select 'NOT_US'::text, null::text, x.reason;
    else
        return query select * from public.dc_geocodable_site_address(x.address_line);
    end if;
end;
$fn$;

comment on function public.dc_geocode_input(text, text, jsonb) is
'STEP 3D. dc_publisher_stated_address (per-source schema extraction) then dc_geocodable_site_address
(one generic policy). GEOCODABLE is a PRECONDITION, never a verdict on the result.';

-- ── ADMISSION: which extractions' derivations may reach canonical decisions ───────────────
-- Acquiring derived evidence and letting it change decisions are two deployments, not one. A new
-- extraction is admitted only after a national dry run of its consequences has been reviewed as a
-- system (docs/dc-atlas-dryrun-report.sql). Until then its derivations are written and reported
-- (dc_observation_derived_point.admitted = false) and change NOTHING: not the geography evidence,
-- not the geography provenance, not the identity candidates.
-- This is a deployment gate over an extraction, never an authority rank: an admitted derivation is
-- judged by the SAME class rules as every other, and a non-admitted one is simply absent.
-- Admitting an extraction = one reviewed edit to this function (the committed-switch pattern).
--   epoch_ai/data_centers   admitted 2026-09-24 (#1324, national dry run 36058486723)
--   compute_atlas/facilities NOT admitted: evidence acquisition only, pending review of the
--                            national dry run (dc-atlas-dryrun.yml)
create or replace function public.dc_derived_address_admitted(p_source_key text, p_distribution_key text)
returns boolean
language sql
immutable
set search_path to 'public', 'pg_temp'
as $$ select (p_source_key, p_distribution_key) in (('epoch_ai', 'data_centers')) $$;

comment on function public.dc_derived_address_admitted(text, text) is
'STEP 3D. Deployment gate: whether an extraction''s derivations may reach geography and identity.
Binary admission of a reviewed extraction, never a rank. See the header of this section.';

-- ── CURRENT OBSERVATION -> DERIVED POINT ─────────────────────────────────────────────────
-- Keyed by the ADDRESS, not the observation: a daily re-acquisition of an unchanged address
-- reuses the same derivation, so derived evidence survives runs without re-geocoding.
-- security_invoker + revoke: create-or-replace drops reloptions (Step 3C view-grants fix).
create or replace view public.dc_observation_derived_point with (security_invoker = true) as
select o.home_signal_observation_id, o.source_key, o.distribution_key,
       gi.input_quality, gi.geocoder_query, gi.reason as input_reason,
       d.derivation_id, d.provider, d.match_type, d.lat, d.lng, d.matched_address,
       d.provider_candidates, d.derived_at, d.run_ref,
       case when gi.input_quality <> 'GEOCODABLE' then 'NOT_GEOCODABLE'
            else v.verdict end as verdict,
       v.positional_uncertainty_m,
       case when gi.input_quality <> 'GEOCODABLE' then gi.reason else v.reason end as verdict_reason,
       -- deployment gate (dc_derived_address_admitted): false = acquired and reported, decides nothing
       public.dc_derived_address_admitted(o.source_key, o.distribution_key) as admitted
  from public.dc_current_observation o
 cross join lateral public.dc_geocode_input(o.source_key, o.distribution_key, o.raw_payload) gi
  left join public.dc_address_geocode d
    on d.geocoder_query = gi.geocoder_query
   and d.ladder_version = public.dc_geocode_ladder_version()
  left join lateral public.dc_derived_point_verdict(d.match_type, d.provider_candidates,
                    gi.geocoder_query, d.matched_address, d.lat, d.lng) v on true
 where gi.input_quality <> 'NO_GEOCODE_RULE';

revoke all on public.dc_observation_derived_point from anon, authenticated;

comment on view public.dc_observation_derived_point is
'STEP 3D. Each current observation of a source with an address rule, its geocoder query, the
derivation for the current ladder version (if any) and the fail-closed verdict.';

-- ── WORK QUEUE for the writer ────────────────────────────────────────────────────────────
-- `admitted` (appended 2026-09-24): whether ANY current observation stating this address belongs to
-- an admitted extraction. The writer drains admitted work first, so a large not-yet-admitted
-- backlog can never delay a derivation that decisions are waiting for.
create or replace view public.dc_geocode_queue with (security_invoker = true) as
select p.geocoder_query, public.dc_geocode_ladder_version() as ladder_version,
       bool_or(p.admitted) as admitted
  from public.dc_observation_derived_point p
 where p.input_quality = 'GEOCODABLE'
   and p.derivation_id is null
 group by p.geocoder_query;

revoke all on public.dc_geocode_queue from anon, authenticated;

comment on view public.dc_geocode_queue is
'STEP 3D. Geocodable source addresses with no derivation for the current ladder version: the
only input dc-geocode-observations.yml reads.';

-- ===== STEP 3A  docs/dc-step3a-canonical-identity.sql (changed objects) =====

-- ⛔ DO NOT "TIDY" THESE BACK INTO FOREIGN KEYS. Doing so silently takes Step 2A from 72 to 70
--    passing checks, and the two it breaks are the ones proving the evidence plane is immutable.

-- =============================================================================================
-- SECTION 4 — CANDIDATE GENERATION
-- =============================================================================================
--
-- A candidate rule only SURFACES a pair for adjudication. It never concludes anything.
--
-- 🔑 THREE CANDIDATE RULES WERE DESIGNED, MEASURED AGAINST PRODUCTION, AND TWO WERE DELETED.
--    Recording why, because each looks reasonable until it is run:
--
--    ⛔ NORMALIZED NAME (lowercase, strip punctuation, strip a trailing parenthetical) --
--       DELETED. It produced 18 pairs, and the parenthetical it discards is the DISCRIMINATOR:
--         "AWS New Albany (3180 Beech Road)" / "(Newton Court)" /
--         "(Beech/Miller Road Campus)" / "(2550 Beech Road)"
--       are FOUR distinct Atlas records at four addresses that this rule collapsed into one
--       name. It also collapsed "Adams Fork Energy Campus Data Center (Twisted Gun Golf Course,
--       Wharncliffe)" with "(Harless Industrial Park, Holden)" -- two sites in two towns. The
--       instrument was manufacturing the very false merges the mandate forbids.
--
--    ⛔ SHARED POSTAL CODE -- DELETED. It produced 20 pairs, every one garbage:
--         "CyrusOne NVA5 [20166]" <> "Google Arcola",  "Digital Realty IAD55 [20166]" <> the same.
--       Ashburn 20166 contains dozens of unrelated data centres. A ZIP is not an identity.
--
--    ✅ EXACT NAME (K1) and SAME OPERATOR + IDENTICAL COORDINATES (K2) are retained -- NOT
--       because they confirm anything (section 5 shows they confirm nothing) but because they
--       surface exactly the pairs a human would ask about, and answering them in writing is
--       what stops the next resolver guessing.
--
-- ⛔ NO FUZZY MATCHING RULE EXISTS HERE AND NONE MAY BE ADDED. Name similarity, trigram
--    distance, coordinate proximity and shared operator are not candidate rules in this design;
--    the first two are absent entirely and the last two appear only in K2's exact-coordinate
--    form, which section 5 then refuses to treat as identity.

-- ✅ K3 (2026-09-24) IS A DELIBERATE, NARROW AMENDMENT TO THE RULE ABOVE -- and it cannot merge.
--    A source with no coordinates (Epoch) now gains a DERIVED point from its own address
--    (docs/dc-step3d-derived-location.sql). A derived point that another source's data centre
--    already occupies is the duplicate-marker risk this layer exists to prevent. The 2026-09-24
--    probe measured it: 34 of 35 matched Epoch points have an Atlas data-centre record within
--    10 km, and many are plainly the same site under another name (Google Council Bluffs 12 m;
--    QTS Hillsboro 2 281 m; Vantage TX1 / TX11 89 m; Colossus 2 / "Minihard" 3 m). Atlas's own
--    town-centroid pins sat 3.5-6.6 km from the address of the same facility (Kuna 3.5 km,
--    Ellendale 4.6 km, Bowling Green 6.2 km, Fairwater Atlanta 6.6 km), hence 10 km, plus the
--    same state and locality for a town-centroid pin that is further out.
--    K3 SURFACES ONLY. Section 5 adjudicates it POSSIBLE_MATCH and nothing else: proximity is
--    never identity. Its effect is an automatic IDENTITY_UNRESOLVED that HOLDS the derived
--    location (dc_resolve_geography) and is recomputed from evidence every run -- no person is
--    asked. Over-recall costs a held Epoch point; under-recall costs a duplicate facility on a
--    resident's map.
create or replace view public.dc_identity_candidate with (security_invoker = true) as
with o as (
    select c.home_signal_observation_id oid, c.source_key, c.distribution_key, c.acquisition_run_id,
           c.publisher_record_id, c.source_native_name, c.source_native_type, c.source_native_operator,
           c.source_native_lat, c.source_native_lon, c.source_native_precision,
           ev.source_native_address, c.raw_payload, lower(btrim(c.source_native_name)) exact_name
    from public.dc_current_observation c
    join public.dc_source_observation ev on ev.home_signal_observation_id = c.home_signal_observation_id
)
-- K1 — byte-identical name after case-folding and trimming, and nothing else discarded.
select least(a.oid, b.oid) as observation_a,
       greatest(a.oid, b.oid) as observation_b,
       'EXACT_NAME'::text as candidate_rule_key,
       jsonb_build_object('name', a.source_native_name,
                          'a_source', a.source_key, 'b_source', b.source_key) as candidate_evidence
from o a join o b
  on a.exact_name = b.exact_name and a.oid < b.oid
 where a.exact_name is not null and a.exact_name <> ''
union all
-- K2 — same operator AND byte-identical coordinates.
select least(a.oid, b.oid), greatest(a.oid, b.oid),
       'SAME_OPERATOR_IDENTICAL_COORDS'::text,
       jsonb_build_object('operator', a.source_native_operator,
                          'lat', a.source_native_lat, 'lon', a.source_native_lon,
                          'a_precision', a.source_native_precision,
                          'b_precision', b.source_native_precision,
                          'a_name', a.source_native_name, 'b_name', b.source_native_name,
                          'a_type', a.source_native_type, 'b_type', b.source_native_type)
from o a join o b
  on a.source_native_operator = b.source_native_operator
 and a.source_native_lat = b.source_native_lat
 and a.source_native_lon = b.source_native_lon
 and a.oid < b.oid
 where a.source_native_operator is not null
   and a.source_native_lat is not null and a.source_native_lon is not null
union all
-- K3 — an ACCEPTED derived address point, and ANOTHER source's data-centre record within 10 km
--      of it or in the same state and locality. Surfaces a pair for a person; concludes nothing.
select least(d.home_signal_observation_id, t.oid), greatest(d.home_signal_observation_id, t.oid),
       'DERIVED_POINT_NEAR_OTHER_SOURCE_DC'::text,
       jsonb_build_object('derived_observation', d.home_signal_observation_id,
                          'derived_query', d.geocoder_query, 'derived_matched', d.matched_address,
                          'other_name', t.source_native_name, 'other_source', t.source_key,
                          'other_operator', t.source_native_operator,
                          'distance_m', round(ST_Distance(
                               ST_SetSRID(ST_MakePoint(d.lng, d.lat), 4326)::geography,
                               ST_SetSRID(ST_MakePoint(t.source_native_lon, t.source_native_lat), 4326)::geography)))
from public.dc_observation_derived_point d
join o t on t.source_key <> d.source_key
cross join lateral public.dc_classify_observation(t.source_key, t.distribution_key,
                                                  t.source_native_type, t.raw_payload) tc
 where d.verdict = 'ACCEPTED'
   and d.admitted   -- a derivation of a not-yet-admitted extraction (Step 3D) surfaces nothing
   and tc.classification in ('CONFIRMED_DC', 'DC_CANDIDATE')
   and t.source_native_lat is not null and t.source_native_lon is not null
   and ( ST_DWithin(ST_SetSRID(ST_MakePoint(d.lng, d.lat), 4326)::geography,
                    ST_SetSRID(ST_MakePoint(t.source_native_lon, t.source_native_lat), 4326)::geography,
                    10000)
      or ( nullif(upper(btrim(t.source_native_address->>'state')), '') = split_part(d.matched_address, ', ', 3)
       and nullif(upper(btrim(t.source_native_address->>'city')), '')  = split_part(d.matched_address, ', ', 2) ) )
union all
-- K4 — the SAME source-stated site address (house number + street + state) in two sources. The
--      only candidate the adjudicator can confirm automatically, and only under its guards (A4).
select least(x.home_signal_observation_id, y.home_signal_observation_id),
       greatest(x.home_signal_observation_id, y.home_signal_observation_id),
       'EXACT_SITE_ADDRESS'::text,
       jsonb_build_object('site_key', x.site_key, 'state', x.state,
                          'a_source', x.source_key, 'b_source', y.source_key)
  from public.dc_observation_site_address x
  join public.dc_observation_site_address y
    on y.site_key = x.site_key and y.state = x.state and x.source_key < y.source_key;

comment on view public.dc_identity_candidate is
'STEP 3A candidate generation. Surfaces pairs for adjudication; concludes nothing. Normalized-
name and shared-postal-code rules were measured against production and deleted -- see the
header of this section for the false merges each produced.';

-- create-or-replace DROPS reloptions and re-inherits default privileges (Step 3C view-grants fix):
-- the view above re-declares security_invoker, and the grant is revoked again here, every time.
revoke all on public.dc_identity_candidate from anon, authenticated;

-- ===== STEP 3B  docs/dc-step3b-canonical-geography.sql (changed objects) =====

-- ── THE GEOGRAPHY EVIDENCE OF EVERY ENTITY (one definition; the resolver and every report read it)
-- Every coordinate pair any CURRENT observation linked to an entity asserts:
--   * the publisher's own point, with the publisher's own account of what it is (location basis);
--   * an ACCEPTED derived address point of Step 3D -- a different kind of evidence, labelled as
--     such: basis DERIVED_ADDRESS, no publisher precision, and its calibrated positional
--     uncertainty in metres.
-- evidence_class is decided by the EVIDENCE, never by the source's name:
--   PUBLISHER_SITE      a publisher point whose basis is not a settlement/area statement and which
--                       carries >= 2 decimal places (a claim about the site itself)
--   DERIVED_ADDRESS     a HomeSignal geocode of a publisher's site address (carries uncertainty)
--   PUBLISHER_NON_SITE  the publisher says the point is a town / administrative / area location
--   PUBLISHER_UNUSABLE  <= 1 decimal place on either axis (±~5.5 km: cannot decide a ZIP)
create or replace view public.dc_entity_geography_evidence with (security_invoker = true) as
select eo.canonical_entity_id, o.home_signal_observation_id oid, o.source_key,
       o.source_native_precision prec, o.source_native_lat lat, o.source_native_lon lng,
       least(scale(o.source_native_lat::text::numeric),
             scale(o.source_native_lon::text::numeric)) decimals,
       o.observed_at, lb.basis, lb.rule_key basis_rule, lb.evidence basis_evidence,
       null::double precision uncertainty_m,
       case when lb.basis = 'NON_SITE_AREA' then 'PUBLISHER_NON_SITE'
            when least(scale(o.source_native_lat::text::numeric),
                       scale(o.source_native_lon::text::numeric)) <= 1 then 'PUBLISHER_UNUSABLE'
            else 'PUBLISHER_SITE' end evidence_class
  from public.dc_entity_observation eo
  join public.dc_current_observation c
    on c.home_signal_observation_id = eo.home_signal_observation_id
  join public.dc_source_observation o
    on o.home_signal_observation_id = eo.home_signal_observation_id
 cross join lateral public.dc_location_basis(o.source_key, o.distribution_key, o.raw_payload) lb
 where o.source_native_lat is not null and o.source_native_lon is not null
   and o.source_native_lat between -90 and 90 and o.source_native_lon between -180 and 180
union all
select eo.canonical_entity_id, dp.home_signal_observation_id, dp.source_key,
       null::text, dp.lat, dp.lng, 6, o.observed_at,
       'DERIVED_ADDRESS'::text, dp.match_type,
       jsonb_build_object('derivation_id', dp.derivation_id, 'geocoder_query', dp.geocoder_query,
                          'matched_address', dp.matched_address, 'provider', dp.provider,
                          'match_type', dp.match_type,
                          'provider_candidates', dp.provider_candidates,
                          'derived_at', dp.derived_at, 'run_ref', dp.run_ref,
                          'verdict', dp.verdict, 'verdict_reason', dp.verdict_reason),
       dp.positional_uncertainty_m,
       'DERIVED_ADDRESS'::text
  from public.dc_entity_observation eo
  join public.dc_observation_derived_point dp
    on dp.home_signal_observation_id = eo.home_signal_observation_id
  join public.dc_source_observation o
    on o.home_signal_observation_id = eo.home_signal_observation_id
 where dp.verdict = 'ACCEPTED'
   and dp.admitted;

   -- an extraction not yet admitted (Step 3D) is acquired and reported, never evidence

revoke all on public.dc_entity_geography_evidence from public, anon, authenticated;

comment on view public.dc_entity_geography_evidence is
'STEP 3B. Every coordinate claim linked to a canonical entity, classified by what the evidence is
(PUBLISHER_SITE / DERIVED_ADDRESS / PUBLISHER_NON_SITE / PUBLISHER_UNUSABLE), never by source
name. dc_resolve_geography reads it; no resident reader.';

create or replace function public.dc_resolve_geography(p_apply boolean default false)
returns table(metric text, value text)
language plpgsql
as $fn$
declare
    v_rule_version constant integer := 5;
    v_written integer := 0;
    v_pending integer;
begin
    -- ⛔ IDENTITY FIRST, OR NOTHING (2026-09-24). This resolver reads coordinates only through
    -- observations that identity has already linked to an entity. An acquisition that commits
    -- after the hour's identity run (:25) and before this one (:35) makes the CURRENT run a set
    -- of observations linked to nothing, and every entity then has "no coordinates" -- measured
    -- 2026-09-24 14:35Z: Atlas landed 14:26:42, all 2,870 live entities were rewritten
    -- GEOGRAPHY_UNRESOLVED, and Map 1 served ZERO canonical data centres until identity ran
    -- again. Unlinked current evidence is not evidence of absence, so the resolver refuses to
    -- decide anything until identity has caught up, and the last decided geography stands.
    select count(*) into v_pending
      from public.dc_current_observation c
     where not exists (select 1 from public.dc_entity_observation eo
                        where eo.home_signal_observation_id = c.home_signal_observation_id);
    if v_pending > 0 then
        return query
            select 'MODE'::text, case when p_apply then 'APPLY' else 'REPORT_ONLY' end
            union all select 'REFUSED_IDENTITY_PENDING', v_pending::text
            union all select 'ROWS_WRITTEN', '0';
        return;
    end if;

    drop table if exists _geo_pts;
    drop table if exists _geo_pick;
    drop table if exists _geo_out;
    drop table if exists _geo_open;
    drop table if exists _geo_derived;

    -- Every coordinate pair any CURRENT observation of an entity asserts, as classified by the
    -- one evidence view below (publisher points and ACCEPTED derived address points).
    create temporary table _geo_pts on commit drop as
    select canonical_entity_id, oid, source_key, prec, lat, lng, decimals, observed_at, basis,
           basis_rule, basis_evidence, uncertainty_m, evidence_class
      from public.dc_entity_geography_evidence;

    -- Why each entity's derived location did or did not qualify (reported, never a point).
    create temporary table _geo_derived on commit drop as
    select distinct on (eo.canonical_entity_id) eo.canonical_entity_id,
           jsonb_build_object('input_quality', dp.input_quality, 'geocoder_query', dp.geocoder_query,
                              'verdict', dp.verdict, 'reason', dp.verdict_reason,
                              'match_type', dp.match_type, 'matched_address', dp.matched_address) derived
      from public.dc_entity_observation eo
      join public.dc_observation_derived_point dp
        on dp.home_signal_observation_id = eo.home_signal_observation_id
     where dp.admitted
     order by eo.canonical_entity_id, (dp.verdict = 'ACCEPTED') desc, dp.home_signal_observation_id;

    -- ⛔ IDENTITY BEFORE A DERIVED MARKER. An entity with an OPEN cross-source identity question
    -- (dc_entity_identity_open: the automatic IDENTITY_UNRESOLVED) may not be PLACED by a derived
    -- point: the other entity may be the same facility, and two markers for one site is the defect.
    -- The question is answered by Step 3A's one definition, recomputed from evidence on every run;
    -- nothing here waits for a person. Publisher points are unaffected.
    create temporary table _geo_open on commit drop as
    select distinct o.canonical_entity_id
      from public.dc_entity_identity_open o;

    create temporary table _geo_pick on commit drop as
    select distinct on (canonical_entity_id) *
      from _geo_pts
     order by canonical_entity_id,
              -- the EVIDENCE CLASS decides authority (never the source, never the label): a
              -- publisher's site point, then a derived address point, then a non-site or
              -- unusable publisher point (which can never place an entity anyway)
              (evidence_class in ('PUBLISHER_NON_SITE', 'PUBLISHER_UNUSABLE')),
              (evidence_class = 'DERIVED_ADDRESS'),
              -- inside one class only: the publisher's own precision label, then precision
              (prec = 'exact') desc nulls last,
              decimals desc,
              observed_at desc, oid;

    create temporary table _geo_out on commit drop as
    with base as (
        select e.canonical_entity_id, e.entity_grain, p.oid, p.source_key, p.prec, p.lat,
               p.lng, p.decimals, p.basis, p.basis_rule, p.basis_evidence, p.uncertainty_m,
               -- ⚖️ CANONICAL GEOGRAPHY AUTHORITY (rule_version 4). Only SITE claims are compared:
               -- a publisher's site point and an accepted derived address point. A town/area or
               -- unusable point is not a claim about the site, so it neither agrees nor disagrees.
               -- Any two DISTINCT site claims of one entity CONTRADICT each other only when they lie
               -- farther apart than the evidence itself allows (dc_site_claims_conflict). Claims are
               -- paired by (source, class, observation), never by source alone (rule_version 5): a
               -- publisher's point and the geocode of that SAME publisher's address are two claims.
               --   * a derived point carries its calibrated error bound, so a publisher's site point
               --     within that bound is CORROBORATED by it, never vetoed;
               --   * two publisher site points carry no quantified error: the peer tolerance.
               -- A contradiction beyond that allowance fails closed: SOURCES_DISAGREE, no point.
               exists (select 1 from _geo_pts a join _geo_pts b
                         on a.canonical_entity_id = b.canonical_entity_id
                        and (a.source_key, a.evidence_class, a.oid) < (b.source_key, b.evidence_class, b.oid)
                        where a.canonical_entity_id = e.canonical_entity_id
                          and public.dc_site_claims_conflict(a.evidence_class, a.uncertainty_m, a.lat, a.lng,
                                                             b.evidence_class, b.uncertainty_m, b.lat, b.lng)) disagree,
               -- which kind of contradiction (reported, never a different outcome)
               exists (select 1 from _geo_pts a join _geo_pts b
                         on a.canonical_entity_id = b.canonical_entity_id
                        and (a.source_key, a.evidence_class, a.oid) < (b.source_key, b.evidence_class, b.oid)
                        where a.canonical_entity_id = e.canonical_entity_id
                          and a.evidence_class = 'PUBLISHER_SITE' and b.evidence_class = 'PUBLISHER_SITE'
                          and public.dc_site_claims_conflict(a.evidence_class, a.uncertainty_m, a.lat, a.lng,
                                                             b.evidence_class, b.uncertainty_m, b.lat, b.lng)) peer_conflict,
               -- the chosen publisher site point, corroborated by a derived address point (any
               -- publisher's, the point's own publisher included -- rule_version 5)
               (p.evidence_class = 'PUBLISHER_SITE'
                and exists (select 1 from _geo_pts d
                             where d.canonical_entity_id = e.canonical_entity_id
                               and d.evidence_class = 'DERIVED_ADDRESS'
                               and not public.dc_site_claims_conflict(p.evidence_class, p.uncertainty_m, p.lat, p.lng,
                                                                      d.evidence_class, d.uncertainty_m, d.lat, d.lng))) corroborated,
               e.canonical_entity_id in (select canonical_entity_id from _geo_open) identity_open,
               -- a derived point may place only a record whose identity persists across runs: a
               -- singleton key (a name repeated inside its own run) would mint a new marker id
               -- every acquisition
               (p.basis = 'DERIVED_ADDRESS'
                and exists (select 1 from public.dc_observation_record_key rk
                             where rk.home_signal_observation_id = p.oid and rk.record_key_rank = 2)) unstable,
               (select dd.derived from _geo_derived dd
                 where dd.canonical_entity_id = e.canonical_entity_id) derived,
               exists (select 1 from _geo_pick q
                        where q.canonical_entity_id <> e.canonical_entity_id
                          and q.lat = p.lat and q.lng = p.lng) shared
          from public.dc_canonical_entity e
          left join _geo_pick p on p.canonical_entity_id = e.canonical_entity_id
         where e.superseded_by is null)
    select b.*,
           case when b.entity_grain = 'AGGREGATE_MULTI_SITE' then 'NOT_A_SITE'
                when b.oid is null or b.disagree or b.decimals <= 1 then 'GEOGRAPHY_UNRESOLVED'
                when b.basis = 'NON_SITE_AREA' then 'GEOGRAPHY_UNRESOLVED'
                when b.basis = 'DERIVED_ADDRESS' and b.unstable then 'GEOGRAPHY_UNRESOLVED'
                when b.basis = 'DERIVED_ADDRESS' and b.identity_open then 'GEOGRAPHY_UNRESOLVED'
                when b.basis = 'DERIVED_ADDRESS' and b.shared then 'GEOGRAPHY_UNRESOLVED'
                else 'RESOLVED' end status,
           case when b.entity_grain = 'AGGREGATE_MULTI_SITE' then 'PUBLISHER_MULTI_SITE'
                when b.oid is null then 'NO_COORDINATES'
                when b.disagree then 'SOURCES_DISAGREE'
                when b.decimals <= 1 then 'ROUNDED_COORDINATES'
                when b.basis = 'NON_SITE_AREA' then 'PUBLISHER_AREA_POINT'
                when b.basis = 'DERIVED_ADDRESS' and b.unstable then 'UNSTABLE_RECORD_IDENTITY'
                when b.basis = 'DERIVED_ADDRESS' and b.identity_open then 'IDENTITY_UNRESOLVED'
                when b.basis = 'DERIVED_ADDRESS' and b.shared then 'DERIVED_ADDRESS_SHARED'
                when b.basis = 'DERIVED_ADDRESS' then 'DERIVED_ADDRESS_POINT'
                else 'PUBLISHER_POINT' end rule_key,
           array_remove(array[
               case when b.oid is not null and b.decimals <= 1 then 'ROUNDED_COORDINATES' end,
               case when b.oid is not null and (b.decimals <= 1 or b.basis = 'NON_SITE_AREA')
                         and b.prec = 'exact'
                    then 'PUBLISHER_CLAIMS_EXACT' end,
               case when b.basis = 'NON_SITE_AREA' then 'PUBLISHER_AREA_POINT' end,
               case when b.basis = 'NON_SITE_ROAD' then 'PUBLISHER_ROAD_REFERENCE' end,
               case when b.basis = 'DERIVED_ADDRESS' then 'DERIVED_ADDRESS_POINT' end,
               case when b.basis = 'DERIVED_ADDRESS' and b.unstable then 'UNSTABLE_RECORD_IDENTITY' end,
               case when b.basis = 'DERIVED_ADDRESS' and b.identity_open then 'IDENTITY_UNRESOLVED' end,
               case when b.decimals = 2 then 'COARSE_COORDINATES' end,
               case when b.prec = 'approximate' then 'PUBLISHER_APPROXIMATE' end,
               case when b.shared then 'SHARED_COORDINATES' end,
               case when b.disagree then 'SOURCES_DISAGREE' end,
               case when b.disagree and b.peer_conflict then 'SITE_CLAIMS_CONFLICT' end,
               case when b.disagree and not b.peer_conflict then 'DERIVED_ADDRESS_BEYOND_UNCERTAINTY' end,
               case when b.corroborated and not b.disagree then 'CORROBORATED_BY_DERIVED_ADDRESS' end,
               case when b.oid is null then 'NO_COORDINATES' end], null) flags
      from base b;

    if p_apply then
        insert into public.dc_entity_geography as g
            (canonical_entity_id, geography_status, geometry_type, geom, lat, lng,
             coordinate_decimals, authority_source_key, authority_observation_id,
             publisher_precision, quality_flags, rule_key, rule_version, provenance,
             positional_uncertainty_m)
        select canonical_entity_id, status,
               case when status = 'RESOLVED' then 'POINT' end,
               case when status = 'RESOLVED' then ST_SetSRID(ST_MakePoint(lng, lat), 4326) end,
               lat, lng, decimals, source_key, oid, prec, flags, rule_key, v_rule_version,
               jsonb_build_object('rule', rule_key, 'observation', oid,
                                  'location_basis', basis, 'location_basis_rule', basis_rule,
                                  'location_basis_evidence', basis_evidence,
                                  'positional_uncertainty_m', uncertainty_m,
                                  'derived_location', derived),
               case when status = 'RESOLVED' then uncertainty_m end
          from _geo_out
        on conflict (canonical_entity_id) do update
           set geography_status = excluded.geography_status,
               geometry_type = excluded.geometry_type, geom = excluded.geom,
               lat = excluded.lat, lng = excluded.lng,
               coordinate_decimals = excluded.coordinate_decimals,
               authority_source_key = excluded.authority_source_key,
               authority_observation_id = excluded.authority_observation_id,
               publisher_precision = excluded.publisher_precision,
               quality_flags = excluded.quality_flags, rule_key = excluded.rule_key,
               rule_version = excluded.rule_version, provenance = excluded.provenance,
               positional_uncertainty_m = excluded.positional_uncertainty_m,
               updated_at = now()
         where (g.geography_status, g.lat, g.lng, g.quality_flags, g.rule_key,
                g.authority_observation_id, g.rule_version, g.positional_uncertainty_m, g.provenance)
               is distinct from
               (excluded.geography_status, excluded.lat, excluded.lng, excluded.quality_flags,
                excluded.rule_key, excluded.authority_observation_id, excluded.rule_version,
                excluded.positional_uncertainty_m, excluded.provenance);
        get diagnostics v_written = row_count;
    end if;

    return query
        select 'MODE'::text, case when p_apply then 'APPLY' else 'REPORT_ONLY' end
        union all select 'ENTITIES', count(*)::text from _geo_out
        union all select 'ROWS_WRITTEN', case when p_apply then v_written::text else 'n/a' end
        union all select 'STATUS_' || s.status, s.n::text
               from (select status, count(*) n from _geo_out group by status) s
        union all select 'RULE_' || r.rule_key, r.n::text
               from (select rule_key, count(*) n from _geo_out group by rule_key) r
        union all select 'FLAG_' || f.flag, f.n::text
               from (select flag, count(*) n from _geo_out, unnest(flags) flag group by flag) f;
end;
$fn$;

comment on function public.dc_resolve_geography(boolean) is
'STEP 3B resolver. Default REPORT ONLY. Decides each canonical entity''s geography from its
current observations by column-level rules (grain, coordinates present, source agreement,
decimal places); never by place, project or source name. Idempotent: an unchanged entity is
not rewritten.';

commit;
