-- GENERATED by test/dc_atlas_validation_pg/build_admission.py from the DDL of record. Do not edit.

-- STAGE 10: admit Atlas (compute_atlas/facilities) in the derived-address admission switch.

-- One transaction: drift guard, the switch and its comment, in-transaction post-condition.

begin;

do $guard$
begin
  if (select md5(p.prosrc) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
       where n.nspname = 'public' and p.proname = 'dc_derived_address_admitted') is distinct from
     'cd968b64ada7adaee18a4dc8be0c4a4b'
     or public.dc_derived_address_admitted('compute_atlas', 'facilities')
     or not public.dc_derived_address_admitted('epoch_ai', 'data_centers') then
    raise exception 'DRIFT: the live admission switch is not Phase A''s (Epoch only). Nothing applied.';
  end if;
end $guard$;

-- ===== STEP 3D  docs/dc-step3d-derived-location.sql (the admission switch) =====

-- ── ADMISSION: which extractions' derivations may reach canonical decisions ───────────────
-- Acquiring derived evidence and letting it change decisions are two deployments, not one. A new
-- extraction is admitted only after a national dry run of its consequences has been reviewed as a
-- system (docs/dc-atlas-dryrun-report.sql). Until then its derivations are written and reported
-- (dc_observation_derived_point.admitted = false) and change NOTHING: not the geography evidence,
-- not the geography provenance, not the identity candidates.
-- This is a deployment gate over an extraction, never an authority rank: an admitted derivation is
-- judged by the SAME class rules as every other, and a non-admitted one is simply absent.
-- Admitting an extraction = one reviewed edit to this function (the committed-switch pattern).
--   epoch_ai/data_centers   admitted 2026-09-24 (#1324, national dry run 36058486723)
--   compute_atlas/facilities admitted 2026-09-26 (stage 10), after the admission dry run on that
--                            day's production copy (dc-atlas-admission-dryrun.yml, run 36253526398:
--                            1 facility added, 26 withheld, 0 moved), reviewed by the founder.
--                            Applied by scripts/dc-atlas-admission-apply.sh.
create or replace function public.dc_derived_address_admitted(p_source_key text, p_distribution_key text)
returns boolean
language sql
immutable
set search_path to 'public', 'pg_temp'
as $$ select (p_source_key, p_distribution_key) in (('epoch_ai', 'data_centers'), ('compute_atlas', 'facilities')) $$;

comment on function public.dc_derived_address_admitted(text, text) is
'STEP 3D. Deployment gate: whether an extraction''s derivations may reach geography and identity.
Binary admission of a reviewed extraction, never a rank. See the header of this section.';

do $post$
begin
  if not public.dc_derived_address_admitted('compute_atlas', 'facilities')
     or not public.dc_derived_address_admitted('epoch_ai', 'data_centers')
     or public.dc_derived_address_admitted('compute_atlas', 'other')
     or public.dc_derived_address_admitted('some_new_source', 'facilities') then
    raise exception 'POST-CONDITION: the switch does not admit exactly Epoch data_centers and Atlas facilities. Rolled back.';
  end if;
end $post$;

commit;
