-- GENERATED by scripts/build-epoch-geography-apply.py from the DDL of record. Do not edit.

-- One transaction: the drift guard, then Step 3D, 3A, 3B and the Map 1 reader, in dependency order.

begin;

do $guard$
declare r record; bad text := '';
begin
  for r in select * from (values ('dc_adjudicate_pair', '27874cd1819cf24fe60746bf7dd8075f'), ('dc_resolve_canonical', '5a3eb4e3d4fa337452649c789e335f22'), ('dc_resolve_geography', 'e8680f1ea7a38242e53dff667e6a96bf'), ('map1_dc_zip_members', 'b143605c4cacca1a6da462443a0add7a')) x(fn, want) loop
    if (select md5(p.prosrc) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
         where n.nspname = 'public' and p.proname = r.fn) is distinct from r.want then
      bad := bad || ' ' || r.fn;
    end if;
  end loop;
  if bad <> '' then
    raise exception 'DRIFT: live definition(s) no longer match main@58aeb8c:%. Nothing applied.', bad;
  end if;
end $guard$;

-- ===== STEP 3D  docs/dc-step3d-derived-location.sql =====

-- ============================================================================
-- STEP 3D · DERIVED LOCATION EVIDENCE — DDL OF RECORD
-- ============================================================================
-- A publisher's ADDRESS is evidence. A geocoder's answer for that address is a SECOND,
-- DIFFERENT fact: "the production ladder, asked Q on date D, returned point P of quality T".
-- This file stores the second fact beside the first, never inside it.
--
-- WHAT IT IS
--   * dc_geocode_input        per-SOURCE canonical rule: which address a record states, and
--                             whether it is a geocodable site address at all (precondition).
--   * dc_address_geocode      append-only DERIVED evidence: one row per (query, ladder version).
--                             Written ONLY by .github/workflows/dc-geocode-observations.yml,
--                             which runs HomeSignal's ONE geocoding ladder
--                             (get-address-report/geocode-cache.ts::productionLadder via
--                             resolveGeocode, keyed by canonical-addr.ts::canonicalAddr).
--   * dc_derived_point_verdict the fail-closed quality rule (output quality, not input syntax).
--   * dc_observation_derived_point  current observation -> its derived point + verdict.
--   * dc_geocode_queue        the addresses the writer still has to resolve.
--
-- WHAT IT IS NOT
--   * It assigns NO ZIP. The provider's postal ZIP is kept as a diagnostic inside
--     matched_address and is never read by any membership decision. Membership stays the ONE
--     polygon authority (geo.zip_point_membership_in) inside public.map1_dc_zip_members.
--   * It decides NO identity and NO geography. The canonical geography resolver
--     (dc_resolve_geography) decides whether an ACCEPTED derived point may place an entity.
--   * It writes NOTHING into dc_source_observation. Publisher evidence is immutable, and a
--     geocoder coordinate written there would read as if the publisher had supplied it.
--   * It is not a second geocoder: SQL never calls a provider. The ladder runs in TypeScript,
--     in exactly one place, and this file only stores what it returned.
--
-- WHY A NEW TABLE (the smallest structure that keeps the two facts apart; measured 2026-09-24):
--   * dc_source_observation is immutable publisher evidence (guard trigger refuses UPDATE).
--   * public.geocodes is the report engine's CACHE: keyed by canonical address, overwritten by
--     upsert_geocode_if_better when a better tier arrives, and carrying no provider candidate
--     count. It cannot say what the ladder returned WHEN a DC decision was made.
--   * dc_entity_geography is a DECISION (one row per entity), not evidence.
--   The Step-2 v1 contract's dc_derived_geometry + per-source geocoding switch were superseded
--   by Step 2A and are NOT resurrected: the per-source switch is dc_geocode_input itself (a
--   source with no rule returns NO_GEOCODE_RULE and is never queued).
--
-- PROBE BEHIND EVERY RULE (dc-geocode-probe.yml, run 36029398914, zero writes, 2026-09-24):
--   Epoch US data-centre records 77: range_interpolated 35 (1 with TWO provider candidates),
--   failed 34, blank 8. The OpenAddresses parcel rung covers two Texas counties only, so
--   nearly every derived point is Census street interpolation.
--   CALIBRATION, 200 Atlas records whose own site point is published (exact, >= 5 dp, UNSTATED
--   basis) and which carry a street address -- the SAME record's address geocoded vs its own
--   point, so no identity is assumed: p50 120 m · p95 396 m · p99 637 m · max 1,801 m;
--   200/200 landed in the same ZCTA as the site point.
--   => positional uncertainty is carried as 2,000 m (the measured maximum, rounded UP), and
--      Map 1 membership requires the WHOLE uncertainty disk inside one ZCTA. Road centrelines
--      are ZCTA edges: 5 of the 35 Epoch points sit 6-26 m from one.
-- ============================================================================

create or replace function public.dc_geocode_ladder_version()
returns text language sql immutable as $$ select 'production-ladder-v1'::text $$;

comment on function public.dc_geocode_ladder_version() is
'STEP 3D. The version of get-address-report/geocode-cache.ts::productionLadder whose answers
dc_address_geocode stores. A ladder change is a new version, so old derivations are never
mistaken for new ones and nothing is overwritten.';

-- ── INPUT RULE: is this a geocodable SITE address? (precondition only) ─────────────────────
-- A house number and a locality are REQUIRED before anything is sent to a geocoder. Without a
-- locality a geocoder may place the address in any town ("13360 Miller Rd NW"); without a house
-- number it returns a road or a place ("Co Rd 42, Montgomery" was matched to 42 COUNTY CT, a
-- different street). A NUMBER RANGE ("14436-14998 Fairview Rd") names a frontage, not a point.
-- Passing this gate proves nothing about the result: output quality is judged separately.
create or replace function public.dc_geocode_input(p_source_key text, p_distribution_key text,
                                                   p_payload jsonb)
returns table(input_quality text, geocoder_query text, reason text)
language plpgsql
immutable
set search_path to 'public', 'pg_temp'
as $fn$
declare
    a    text;
    rest text;
    states constant text := '(AL|AK|AZ|AR|CA|CO|CT|DE|FL|GA|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|OH|OK|OR|PA|RI|SC|SD|TN|TX|UT|VT|VA|WA|WV|WI|WY|DC)';
    state_names constant text := '(Alabama|Alaska|Arizona|Arkansas|California|Colorado|Connecticut|Delaware|Florida|Georgia|Hawaii|Idaho|Illinois|Indiana|Iowa|Kansas|Kentucky|Louisiana|Maine|Maryland|Massachusetts|Michigan|Minnesota|Mississippi|Missouri|Montana|Nebraska|Nevada|New Hampshire|New Jersey|New Mexico|New York|North Carolina|North Dakota|Ohio|Oklahoma|Oregon|Pennsylvania|Rhode Island|South Carolina|South Dakota|Tennessee|Texas|Utah|Vermont|Virginia|Washington|West Virginia|Wisconsin|Wyoming|District of Columbia)';
begin
    if p_source_key = 'epoch_ai' and p_distribution_key = 'data_centers' then
        a := btrim(regexp_replace(coalesce(p_payload->>'Address', ''), '\s+', ' ', 'g'));
        if coalesce(p_payload->>'Country', '') <> 'United States' then
            return query select 'NOT_US'::text, null::text, 'the publisher places this record outside the United States'::text;
        elsif a = '' then
            return query select 'BLANK'::text, null::text, 'the publisher states no address'::text;
        elsif a !~ '^\d' or a ~ '^\d{5}(-\d{4})?$' then   -- a bare ZIP names an area, not a site
            return query select 'NO_HOUSE_NUMBER'::text, null::text, 'no house number: a road, place or area is not a site address'::text;
        elsif a ~ '^\d+[A-Za-z]?\s*[-–]\s*\d+' then
            return query select 'HOUSE_NUMBER_RANGE'::text, null::text, 'a house-number range names a frontage, not a point'::text;
        else
            rest := regexp_replace(a, '^\S+\s*', '');   -- a 5-digit HOUSE number is not a ZIP
            if rest ~ '\m\d{5}(-\d{4})?\M'
               or a ~ (',\s*' || states || '(\s|,|$)')
               or a ~* ('\m' || state_names || '\M') then
                return query select 'GEOCODABLE'::text, a, 'house number and locality present'::text;
            else
                return query select 'NO_LOCALITY'::text, null::text, 'no ZIP or state: the geocoder could place this street in any town'::text;
            end if;
        end if;
        return;
    end if;
    -- Every other source: no rule, so nothing is geocoded. Adding a source is adding a branch.
    return query select 'NO_GEOCODE_RULE'::text, null::text, 'no address rule for this source'::text;
end;
$fn$;

comment on function public.dc_geocode_input(text, text, jsonb) is
'STEP 3D. Per-source address rule, keyed like dc_classify_observation. GEOCODABLE requires a
single house number and a locality; it is a PRECONDITION, never a verdict on the result.';

-- ── DERIVED EVIDENCE: what the ladder returned ────────────────────────────────────────────
create table if not exists public.dc_address_geocode (
    derivation_id              uuid primary key default gen_random_uuid(),
    geocoder_query             text not null,       -- exactly what was sent to the ladder
    canonical_addr             text not null,       -- canonicalAddr(query): the public.geocodes key
    ladder_version             text not null,
    provider                   text not null,       -- the rung that answered ('none' when none did)
    match_type                 text not null,
    lat                        double precision,
    lng                        double precision,
    matched_address            text,                -- provider's matched address (its ZIP is DIAGNOSTIC ONLY)
    provider_candidates        integer,             -- how many matches the provider returned
    provider_matched_addresses text[],
    derived_at                 timestamptz not null default now(),
    run_ref                    text not null,       -- the workflow run that derived it
    constraint dc_address_geocode_type_ck check (match_type in
        ('rooftop', 'parcel_centroid', 'range_interpolated', 'zip_centroid', 'county_centroid', 'failed')),
    constraint dc_address_geocode_point_ck check (
        (match_type = 'failed' and lat is null and lng is null)
     or (match_type <> 'failed' and lat is not null and lng is not null
         and lat between -90 and 90 and lng between -180 and 180))
);

create unique index if not exists dc_address_geocode_query_ladder
    on public.dc_address_geocode (geocoder_query, ladder_version);

alter table public.dc_address_geocode enable row level security;

revoke all on public.dc_address_geocode from anon, authenticated;

comment on table public.dc_address_geocode is
'STEP 3D. DERIVED location evidence: the production geocoding ladder''s answer for a source
address, with provenance. Append-only. Never copied into dc_source_observation, never a ZIP.';

-- Append-only: a derivation is a historical fact. A better answer is a NEW ladder version.
create or replace function public.dc_address_geocode_guard()
returns trigger language plpgsql as $g$
begin
    raise exception 'dc_address_geocode is append-only derived evidence (%): add a new ladder_version instead',
        tg_op;
end;
$g$;

drop trigger if exists dc_address_geocode_guard_trg on public.dc_address_geocode;

create trigger dc_address_geocode_guard_trg
    before update or delete on public.dc_address_geocode
    for each row execute function public.dc_address_geocode_guard();

drop trigger if exists dc_address_geocode_truncate_trg on public.dc_address_geocode;

create trigger dc_address_geocode_truncate_trg
    before truncate on public.dc_address_geocode
    for each statement execute function public.dc_address_geocode_guard();

-- ── QUALITY RULE: may this derived point stand for a SITE? (fail closed) ──────────────────
-- ACCEPTED only when ALL hold; anything else is a named rejection:
--   * a point-grade match type: rooftop, parcel_centroid or range_interpolated
--     (zip_centroid / county_centroid are AREA answers; failed / unknown are nothing);
--   * exactly ONE provider candidate (two matches = the provider could not choose);
--   * the matched house number is the queried house number, and the matched state is the
--     queried state when the query names one (the provider answered the address we asked).
-- The positional uncertainty returned with an ACCEPTED point is the calibrated bound (header).
-- Unmeasured tiers (rooftop, parcel_centroid) get the SAME bound: they are at least as precise
-- by definition, and no Epoch record reaches them today, so no tighter number is invented.
create or replace function public.dc_derived_point_verdict(
    p_match_type text, p_provider_candidates integer, p_query text, p_matched text,
    p_lat double precision, p_lng double precision)
returns table(verdict text, positional_uncertainty_m double precision, reason text)
language plpgsql
immutable
set search_path to 'public', 'pg_temp'
as $fn$
declare
    q_no text := substring(coalesce(p_query, '') from '^(\d+)');
    m_no text := substring(coalesce(p_matched, '') from '^(\d+)');
    q_st text := substring(coalesce(p_query, '') from ',\s*([A-Z]{2})(?:\s+\d{5}(?:-\d{4})?)?\s*(?:,|$)');
    m_st text := substring(coalesce(p_matched, '') from ',\s*([A-Z]{2}),\s*\d{5}\s*$');
begin
    if p_match_type is null then
        return query select 'NOT_YET_GEOCODED'::text, null::double precision, 'no derivation for this address yet'::text;
    elsif p_match_type = 'failed' then
        return query select 'REJECTED_NO_MATCH'::text, null::double precision, 'the ladder matched nothing; no fallback point'::text;
    elsif p_match_type in ('zip_centroid', 'county_centroid') then
        return query select 'REJECTED_AREA_CENTROID'::text, null::double precision, 'an area centroid is not a site'::text;
    elsif p_match_type not in ('rooftop', 'parcel_centroid', 'range_interpolated') then
        return query select 'REJECTED_UNKNOWN_MATCH_TYPE'::text, null::double precision, 'unknown precision is not a site'::text;
    elsif p_lat is null or p_lng is null then
        return query select 'REJECTED_NO_MATCH'::text, null::double precision, 'no coordinates returned'::text;
    elsif p_provider_candidates is distinct from 1 then
        return query select 'REJECTED_AMBIGUOUS'::text, null::double precision,
            'the provider returned ' || coalesce(p_provider_candidates::text, 'an unknown number of') || ' candidates';
    elsif q_no is null or m_no is null or q_no <> m_no then
        return query select 'REJECTED_MATCH_DIVERGES'::text, null::double precision,
            'matched house number ' || coalesce(m_no, 'none') || ' is not the queried ' || coalesce(q_no, 'none');
    elsif q_st is not null and m_st is not null and q_st <> m_st then
        return query select 'REJECTED_MATCH_DIVERGES'::text, null::double precision,
            'matched state ' || m_st || ' is not the queried ' || q_st;
    else
        return query select 'ACCEPTED'::text, 2000::double precision,
            p_match_type || ', one candidate, house number agrees; uncertainty = calibrated max error (2,000 m)';
    end if;
end;
$fn$;

comment on function public.dc_derived_point_verdict(text, integer, text, text, double precision, double precision) is
'STEP 3D. Output-quality rule for a derived point. Area centroids, failures, unknown types,
ambiguous or divergent matches never become a site. ACCEPTED carries the calibrated 2,000 m
positional uncertainty that Map 1 membership must respect.';

-- ── CURRENT OBSERVATION -> DERIVED POINT ─────────────────────────────────────────────────
-- Keyed by the ADDRESS, not the observation: a daily re-acquisition of an unchanged address
-- reuses the same derivation, so derived evidence survives runs without re-geocoding.
-- security_invoker + revoke: create-or-replace drops reloptions (Step 3C view-grants fix).
create or replace view public.dc_observation_derived_point with (security_invoker = true) as
select o.home_signal_observation_id, o.source_key, o.distribution_key,
       gi.input_quality, gi.geocoder_query, gi.reason as input_reason,
       d.derivation_id, d.provider, d.match_type, d.lat, d.lng, d.matched_address,
       d.provider_candidates, d.derived_at, d.run_ref,
       case when gi.input_quality <> 'GEOCODABLE' then 'NOT_GEOCODABLE'
            else v.verdict end as verdict,
       v.positional_uncertainty_m,
       case when gi.input_quality <> 'GEOCODABLE' then gi.reason else v.reason end as verdict_reason
  from public.dc_current_observation o
 cross join lateral public.dc_geocode_input(o.source_key, o.distribution_key, o.raw_payload) gi
  left join public.dc_address_geocode d
    on d.geocoder_query = gi.geocoder_query
   and d.ladder_version = public.dc_geocode_ladder_version()
  left join lateral public.dc_derived_point_verdict(d.match_type, d.provider_candidates,
                    gi.geocoder_query, d.matched_address, d.lat, d.lng) v on true
 where gi.input_quality <> 'NO_GEOCODE_RULE';

revoke all on public.dc_observation_derived_point from anon, authenticated;

comment on view public.dc_observation_derived_point is
'STEP 3D. Each current observation of a source with an address rule, its geocoder query, the
derivation for the current ladder version (if any) and the fail-closed verdict.';

-- ── WORK QUEUE for the writer ────────────────────────────────────────────────────────────
create or replace view public.dc_geocode_queue with (security_invoker = true) as
select distinct p.geocoder_query, public.dc_geocode_ladder_version() as ladder_version
  from public.dc_observation_derived_point p
 where p.input_quality = 'GEOCODABLE'
   and p.derivation_id is null;

revoke all on public.dc_geocode_queue from anon, authenticated;

comment on view public.dc_geocode_queue is
'STEP 3D. Geocodable source addresses with no derivation for the current ladder version: the
only input dc-geocode-observations.yml reads.';

-- ===== STEP 3A  docs/dc-step3a-canonical-identity.sql (changed objects) =====

-- ── STABLE RECORD KEYS (2026-09-24) ───────────────────────────────────────────────────────────
-- The key under which a SOURCE RECORD persists across acquisitions. It is evidence identity, not
-- canonical identity: two records never share a key, and nothing cross-source is decided here.
--   * the publisher's own record id, when the source supplies one (Atlas) -- unchanged, and in the
--     exact format A1 has always grouped on;
--   * otherwise the record's NAME, but ONLY for a source whose registry says it supplies no
--     record id AND only when that name is unique within its own acquisition run and
--     distribution. Measured 2026-09-24 for epoch_ai/data_centers: 87 / 91 / 92 names in three
--     runs, unique in every run, every earlier name present in the next. The source's own table
--     key is its Name; treating it as such is what stops a new canonical entity (and a new Map 1
--     marker id) being minted for the same Epoch record every day -- measured: 270 entities for
--     92 current records after 3 runs.
--     A rename mints a new key (fails safe: a decision is lost, nothing is merged). A name that
--     repeats inside a run is NOT a key, so epoch_ai/timelines (538 rows, 92 names) stays
--     singleton -- the rule is the uniqueness measurement, not a list of distributions;
--   * otherwise a singleton key that no other observation can ever share.
create or replace view public.dc_observation_record_key with (security_invoker = true) as
select o.home_signal_observation_id,
       case when o.publisher_record_id is not null
              then o.source_key || '|' || o.distribution_key || '|' || o.publisher_record_id
            when s.supplies_publisher_record_id is false
             and nullif(btrim(o.source_native_name), '') is not null
             and count(*) over (partition by o.source_key, o.acquisition_run_id, o.distribution_key,
                                             btrim(o.source_native_name)) = 1
              then o.source_key || '|' || o.distribution_key || '|name:' || btrim(o.source_native_name)
            else 'singleton|' || o.home_signal_observation_id::text end as record_key,
       case when o.publisher_record_id is not null then 0
            when s.supplies_publisher_record_id is false
             and nullif(btrim(o.source_native_name), '') is not null
             and count(*) over (partition by o.source_key, o.acquisition_run_id, o.distribution_key,
                                             btrim(o.source_native_name)) = 1 then 1
            else 2 end as record_key_rank   -- 0 publisher id, 1 unique name, 2 singleton
  from public.dc_source_observation o
  join public.dc_source s on s.source_key = o.source_key;

revoke all on public.dc_observation_record_key from anon, authenticated;

comment on view public.dc_observation_record_key is
'STEP 3A. Per-observation stable record key: publisher record id, else a run-unique name for a
source that supplies no id, else a singleton. Evidence identity only; never cross-source.';

-- ── HUMAN IDENTITY REVIEW (2026-09-24) ─────────────────────────────────────────────────────────
-- Cross-source identity is never confirmed by a rule (section 5). A person may confirm it, or
-- confirm that two records are DIFFERENT, and that decision must outlive the runs: so it is
-- keyed on stable RECORD keys, never on observation ids (which change every acquisition).
--   * CONFIRMED_MATCH    the two records describe ONE physical facility. The resolver links them
--                        to one canonical entity -- unless that would put two records of the
--                        SAME source into one entity (the wrong-sibling guard), in which case the
--                        whole reviewed component is refused and nothing merges.
--   * CONFIRMED_DISTINCT the two records are different facilities; the pair stops blocking a
--                        derived location from publishing.
-- Tenant vs operator: a review merges RECORDS, never parties. Each source's operator/tenant
-- fields stay on its own observation (source_native_operator); nothing is overwritten.
-- A review is revoked, never deleted, so the history of a decision is kept.
create table if not exists public.dc_identity_review (
    review_id       uuid primary key default gen_random_uuid(),
    record_key_a    text not null,
    record_key_b    text not null,
    verdict         text not null,
    reviewer        text not null,
    rationale       text not null,
    evidence        jsonb not null default '{}'::jsonb,
    reviewed_at     timestamptz not null default now(),
    revoked_at      timestamptz,
    revoked_reason  text,
    constraint dc_identity_review_verdict_ck check (verdict in ('CONFIRMED_MATCH', 'CONFIRMED_DISTINCT')),
    constraint dc_identity_review_ordered_ck check ((record_key_a collate "C") < (record_key_b collate "C")),
    constraint dc_identity_review_stable_ck check (record_key_a !~ '^singleton\|' and record_key_b !~ '^singleton\|'),
    constraint dc_identity_review_cross_source_ck check (split_part(record_key_a, '|', 1) <> split_part(record_key_b, '|', 1)),
    constraint dc_identity_review_accountable_ck check (btrim(reviewer) <> '' and length(btrim(rationale)) >= 20),
    constraint dc_identity_review_revocation_ck check ((revoked_at is null) = (revoked_reason is null))
);

create unique index if not exists dc_identity_review_active_pair
    on public.dc_identity_review (record_key_a, record_key_b) where revoked_at is null;

alter table public.dc_identity_review enable row level security;

revoke all on public.dc_identity_review from anon, authenticated;

comment on table public.dc_identity_review is
'STEP 3A. Accountable human identity decisions between two cross-source RECORD keys. The only
path by which Atlas and Epoch records can become one canonical entity.';

-- ⛔ DO NOT "TIDY" THESE BACK INTO FOREIGN KEYS. Doing so silently takes Step 2A from 72 to 70
--    passing checks, and the two it breaks are the ones proving the evidence plane is immutable.

-- =============================================================================================
-- SECTION 4 — CANDIDATE GENERATION
-- =============================================================================================
--
-- A candidate rule only SURFACES a pair for adjudication. It never concludes anything.
--
-- 🔑 THREE CANDIDATE RULES WERE DESIGNED, MEASURED AGAINST PRODUCTION, AND TWO WERE DELETED.
--    Recording why, because each looks reasonable until it is run:
--
--    ⛔ NORMALIZED NAME (lowercase, strip punctuation, strip a trailing parenthetical) --
--       DELETED. It produced 18 pairs, and the parenthetical it discards is the DISCRIMINATOR:
--         "AWS New Albany (3180 Beech Road)" / "(Newton Court)" /
--         "(Beech/Miller Road Campus)" / "(2550 Beech Road)"
--       are FOUR distinct Atlas records at four addresses that this rule collapsed into one
--       name. It also collapsed "Adams Fork Energy Campus Data Center (Twisted Gun Golf Course,
--       Wharncliffe)" with "(Harless Industrial Park, Holden)" -- two sites in two towns. The
--       instrument was manufacturing the very false merges the mandate forbids.
--
--    ⛔ SHARED POSTAL CODE -- DELETED. It produced 20 pairs, every one garbage:
--         "CyrusOne NVA5 [20166]" <> "Google Arcola",  "Digital Realty IAD55 [20166]" <> the same.
--       Ashburn 20166 contains dozens of unrelated data centres. A ZIP is not an identity.
--
--    ✅ EXACT NAME (K1) and SAME OPERATOR + IDENTICAL COORDINATES (K2) are retained -- NOT
--       because they confirm anything (section 5 shows they confirm nothing) but because they
--       surface exactly the pairs a human would ask about, and answering them in writing is
--       what stops the next resolver guessing.
--
-- ⛔ NO FUZZY MATCHING RULE EXISTS HERE AND NONE MAY BE ADDED. Name similarity, trigram
--    distance, coordinate proximity and shared operator are not candidate rules in this design;
--    the first two are absent entirely and the last two appear only in K2's exact-coordinate
--    form, which section 5 then refuses to treat as identity.

-- ✅ K3 (2026-09-24) IS A DELIBERATE, NARROW AMENDMENT TO THE RULE ABOVE -- and it cannot merge.
--    A source with no coordinates (Epoch) now gains a DERIVED point from its own address
--    (docs/dc-step3d-derived-location.sql). A derived point that another source's data centre
--    already occupies is the duplicate-marker risk this layer exists to prevent. The 2026-09-24
--    probe measured it: 34 of 35 matched Epoch points have an Atlas data-centre record within
--    10 km, and many are plainly the same site under another name (Google Council Bluffs 12 m;
--    QTS Hillsboro 2 281 m; Vantage TX1 / TX11 89 m; Colossus 2 / "Minihard" 3 m). Atlas's own
--    town-centroid pins sat 3.5-6.6 km from the address of the same facility (Kuna 3.5 km,
--    Ellendale 4.6 km, Bowling Green 6.2 km, Fairwater Atlanta 6.6 km), hence 10 km, plus the
--    same state and locality for a town-centroid pin that is further out.
--    K3 SURFACES ONLY. Section 5 adjudicates it POSSIBLE_MATCH and nothing else; the only way to
--    a merge is an accountable human review. Its effect is to HOLD the derived location
--    (dc_resolve_geography: IDENTITY_REVIEW_REQUIRED) until someone decides -- over-recall costs
--    a held Epoch point, under-recall costs a duplicate facility on a resident's map.
create or replace view public.dc_identity_candidate with (security_invoker = true) as
with o as (
    select c.home_signal_observation_id oid, c.source_key, c.distribution_key, c.acquisition_run_id,
           c.publisher_record_id, c.source_native_name, c.source_native_type, c.source_native_operator,
           c.source_native_lat, c.source_native_lon, c.source_native_precision,
           ev.source_native_address, c.raw_payload, lower(btrim(c.source_native_name)) exact_name
    from public.dc_current_observation c
    join public.dc_source_observation ev on ev.home_signal_observation_id = c.home_signal_observation_id
)
-- K1 — byte-identical name after case-folding and trimming, and nothing else discarded.
select least(a.oid, b.oid) as observation_a,
       greatest(a.oid, b.oid) as observation_b,
       'EXACT_NAME'::text as candidate_rule_key,
       jsonb_build_object('name', a.source_native_name,
                          'a_source', a.source_key, 'b_source', b.source_key) as candidate_evidence
from o a join o b
  on a.exact_name = b.exact_name and a.oid < b.oid
 where a.exact_name is not null and a.exact_name <> ''
union all
-- K2 — same operator AND byte-identical coordinates.
select least(a.oid, b.oid), greatest(a.oid, b.oid),
       'SAME_OPERATOR_IDENTICAL_COORDS'::text,
       jsonb_build_object('operator', a.source_native_operator,
                          'lat', a.source_native_lat, 'lon', a.source_native_lon,
                          'a_precision', a.source_native_precision,
                          'b_precision', b.source_native_precision,
                          'a_name', a.source_native_name, 'b_name', b.source_native_name,
                          'a_type', a.source_native_type, 'b_type', b.source_native_type)
from o a join o b
  on a.source_native_operator = b.source_native_operator
 and a.source_native_lat = b.source_native_lat
 and a.source_native_lon = b.source_native_lon
 and a.oid < b.oid
 where a.source_native_operator is not null
   and a.source_native_lat is not null and a.source_native_lon is not null
union all
-- K3 — an ACCEPTED derived address point, and ANOTHER source's data-centre record within 10 km
--      of it or in the same state and locality. Surfaces a pair for a person; concludes nothing.
select least(d.home_signal_observation_id, t.oid), greatest(d.home_signal_observation_id, t.oid),
       'DERIVED_POINT_NEAR_OTHER_SOURCE_DC'::text,
       jsonb_build_object('derived_observation', d.home_signal_observation_id,
                          'derived_query', d.geocoder_query, 'derived_matched', d.matched_address,
                          'other_name', t.source_native_name, 'other_source', t.source_key,
                          'other_operator', t.source_native_operator,
                          'distance_m', round(ST_Distance(
                               ST_SetSRID(ST_MakePoint(d.lng, d.lat), 4326)::geography,
                               ST_SetSRID(ST_MakePoint(t.source_native_lon, t.source_native_lat), 4326)::geography)))
from public.dc_observation_derived_point d
join o t on t.source_key <> d.source_key
cross join lateral public.dc_classify_observation(t.source_key, t.distribution_key,
                                                  t.source_native_type, t.raw_payload) tc
 where d.verdict = 'ACCEPTED'
   and tc.classification in ('CONFIRMED_DC', 'DC_CANDIDATE')
   and t.source_native_lat is not null and t.source_native_lon is not null
   and ( ST_DWithin(ST_SetSRID(ST_MakePoint(d.lng, d.lat), 4326)::geography,
                    ST_SetSRID(ST_MakePoint(t.source_native_lon, t.source_native_lat), 4326)::geography,
                    10000)
      or ( nullif(upper(btrim(t.source_native_address->>'state')), '') = split_part(d.matched_address, ', ', 3)
       and nullif(upper(btrim(t.source_native_address->>'city')), '')  = split_part(d.matched_address, ', ', 2) ) );

comment on view public.dc_identity_candidate is
'STEP 3A candidate generation. Surfaces pairs for adjudication; concludes nothing. Normalized-
name and shared-postal-code rules were measured against production and deleted -- see the
header of this section for the false merges each produced.';

-- create-or-replace DROPS reloptions and re-inherits default privileges (Step 3C view-grants fix):
-- the view above re-declares security_invoker, and the grant is revoked again here, every time.
revoke all on public.dc_identity_candidate from anon, authenticated;

-- =============================================================================================
-- SECTION 5 — ADJUDICATION
-- =============================================================================================
--
-- ⛔ THE FOLLOWING ARE NEVER SUFFICIENT FOR CONFIRMED_MATCH, AND THE DATA IS WHY:
--
--   same NAME            "Red Oak Campus" appears twice in one Atlas run, at 32.5135,-96.7282
--                        and at 32.537981,-96.804371 -- roughly five miles apart.
--
--   same OPERATOR +      14 groups / 29 observations share an operator and BYTE-IDENTICAL
--   identical COORDS     coordinates while describing different things:
--                          "Monarch Data Center" <> "Monarch Data Center On-Site Generation"
--                          "Savannah River Site AI Data Center" <> "... Energy Generation Project"
--                          "Alterra Marshall Technology & Energy Center" <> "... Gas Generation"
--                        A data centre and the power plant built to feed it share a point.
--
--   COORDINATE           Only 696 of 2,087 Atlas observations are source_native_precision
--   PROXIMITY            'exact'. 1,382 are 'approximate' and 9 are 'representative_multi_site'.
--                        All five same-type K2 pairs are approximate/approximate, so their
--                        identical coordinates are an artifact of approximation, not evidence
--                        of co-location: "Stream Chicago I (ORDA)" / "II (ORDB)" / "III (ORDC)"
--                        are three buildings sharing one approximate campus pin.
--
--   same ADDRESS         See the deleted postal-code candidate rule in section 4.
--
-- ✅ WHAT DOES CONFIRM. Exactly one rule, and it is the one that makes the entity STABLE
--    ACROSS ACQUISITIONS: the same source's same publisher_record_id observed in two different
--    runs is the same real-world thing. That is the publisher's own record identity persisting
--    over time, which is deterministic and explainable.
--
-- ✅ WHAT CONFIRMS DISTINCTNESS. Two observations from the SAME run of the SAME distribution
--    carrying DIFFERENT publisher_record_ids are two records the publisher itself asserts are
--    different. Atlas carries 2,087 distinct publisher_record_ids for 2,087 rows.
--
-- ⚠️ ATLAS <-> EPOCH CANNOT PRODUCE A CONFIRMED_MATCH ON TODAY'S EVIDENCE, AND THAT IS A
--    MEASURED FACT RATHER THAN A CHOICE. Epoch supplies NO publisher_record_id (0 of 87), NO
--    coordinates (0 of 87) and NO lifecycle status (0 of 87). Its only identity-bearing field
--    is a Name. Exactly 2 Epoch names are byte-identical to an Atlas name ("Meta Prometheus",
--    "Meta Hyperion"), and a name alone is never sufficient. So the honest ceiling for every
--    cross-source pair is CANDIDATE_MATCH.
--
-- ⚠️ AND THE GRAIN MAKES IT WORSE, WHICH IS WHY NO AMOUNT OF NAME CLEVERNESS FIXES IT. Epoch
--    publishes at CAMPUS grain and Atlas at BUILDING/SITE grain. Epoch has ONE "AWS New Albany";
--    Atlas has FOUR. There is no correct one-to-one answer to pick, and picking one would be a
--    false merge dressed as a match.

create or replace function public.dc_adjudicate_pair(
    p_observation_a uuid,
    p_observation_b uuid,
    p_candidate_rule_key text
) returns table(decision_state text, decision_rule_key text, evidence jsonb)
language plpgsql
stable
as $fn$
declare
    a record;
    b record;
    ka text;
    kb text;
    rv record;
begin
    select o.home_signal_observation_id oid, o.source_key, o.distribution_key,
           o.acquisition_run_id, o.publisher_record_id, o.source_native_name,
           o.source_native_type, o.source_native_precision
      into a
      from public.dc_source_observation o
     where o.home_signal_observation_id = p_observation_a;

    select o.home_signal_observation_id oid, o.source_key, o.distribution_key,
           o.acquisition_run_id, o.publisher_record_id, o.source_native_name,
           o.source_native_type, o.source_native_precision
      into b
      from public.dc_source_observation o
     where o.home_signal_observation_id = p_observation_b;

    if a.oid is null or b.oid is null then
        return query select 'UNRESOLVED'::text, 'OBSERVATION_NOT_FOUND'::text,
            jsonb_build_object('why', 'one or both observations are absent; fail closed');
        return;
    end if;

    -- A1. The one confirming rule: the publisher's own record identity, persisting across runs.
    if a.source_key = b.source_key
       and a.distribution_key = b.distribution_key
       and a.publisher_record_id is not null
       and a.publisher_record_id = b.publisher_record_id then
        return query select 'CONFIRMED_MATCH'::text,
            'SAME_SOURCE_SAME_PUBLISHER_RECORD_ID'::text,
            jsonb_build_object('source_key', a.source_key,
                'publisher_record_id', a.publisher_record_id,
                'same_run', a.acquisition_run_id = b.acquisition_run_id,
                'why', 'the publisher asserts one record identity observed more than once');
        return;
    end if;

    -- A2. The publisher asserts two DIFFERENT records within one run of one distribution.
    if a.source_key = b.source_key
       and a.distribution_key = b.distribution_key
       and a.acquisition_run_id = b.acquisition_run_id
       and a.publisher_record_id is distinct from b.publisher_record_id then
        return query select 'CONFIRMED_DISTINCT'::text,
            'SAME_RUN_DIFFERENT_PUBLISHER_RECORD_ID'::text,
            jsonb_build_object('source_key', a.source_key,
                'a_publisher_record_id', a.publisher_record_id,
                'b_publisher_record_id', b.publisher_record_id,
                'a_name', a.source_native_name, 'b_name', b.source_native_name,
                'a_type', a.source_native_type, 'b_type', b.source_native_type,
                'a_precision', a.source_native_precision, 'b_precision', b.source_native_precision,
                'candidate_rule', p_candidate_rule_key,
                'why', 'one publisher, one release, two records: the publisher itself separates them');
        return;
    end if;

    -- A0. Cross-source, and a PERSON has decided (dc_identity_review, keyed on stable RECORD
    --     keys so the decision outlives the observation ids). Checked before any weak signal.
    --     This is the only route to a cross-source CONFIRMED_MATCH.
    if a.source_key <> b.source_key then
        select rk.record_key into ka from public.dc_observation_record_key rk
         where rk.home_signal_observation_id = a.oid;
        select rk.record_key into kb from public.dc_observation_record_key rk
         where rk.home_signal_observation_id = b.oid;
        select r.review_id, r.verdict, r.reviewer, r.reviewed_at into rv
          from public.dc_identity_review r
         where r.revoked_at is null
           and r.record_key_a = case when (ka collate "C") < (kb collate "C") then ka else kb end
           and r.record_key_b = case when (ka collate "C") < (kb collate "C") then kb else ka end;
        if rv.review_id is not null then
            return query select rv.verdict::text, ('REVIEWED_' || rv.verdict)::text,
                jsonb_build_object('review_id', rv.review_id, 'reviewer', rv.reviewer,
                    'reviewed_at', rv.reviewed_at, 'record_key_a', ka, 'record_key_b', kb,
                    'candidate_rule', p_candidate_rule_key,
                    'why', 'an accountable human review of the two records');
            return;
        end if;
    end if;

    -- A3. Cross-source. No deterministic identity exists on today's evidence, so the ceiling is
    --     CANDIDATE. Exact name is the strongest available signal and it is still only a name.
    if a.source_key <> b.source_key then
        if p_candidate_rule_key = 'EXACT_NAME' then
            return query select 'CANDIDATE_MATCH'::text,
                'CROSS_SOURCE_EXACT_NAME_ONLY'::text,
                jsonb_build_object('name', a.source_native_name,
                    'a_source', a.source_key, 'b_source', b.source_key,
                    'grain_compatible', false,
                    'why', 'name alone is never sufficient, and the two sources publish at different grains');
            return;
        end if;
        return query select 'POSSIBLE_MATCH'::text,
            case when p_candidate_rule_key = 'DERIVED_POINT_NEAR_OTHER_SOURCE_DC'
                 then 'CROSS_SOURCE_DERIVED_POINT_NEARBY' else 'CROSS_SOURCE_WEAK_SIGNAL' end::text,
            jsonb_build_object('candidate_rule', p_candidate_rule_key,
                'why', 'surfaced by a non-identity signal; not adjudicable on current evidence');
        return;
    end if;

    -- Anything else is honestly unresolved.
    return query select 'UNRESOLVED'::text, 'NO_APPLICABLE_RULE'::text,
        jsonb_build_object('candidate_rule', p_candidate_rule_key,
            'why', 'no deterministic rule applies; fail closed rather than guess');
end;
$fn$;

comment on function public.dc_adjudicate_pair(uuid, uuid, text) is
'STEP 3A adjudication, rule version 2. CONFIRMED_MATCH requires the publisher''s own record
identity, or (cross-source only) an accountable human review of the two stable record keys.
Name, operator, coordinates, address and derived points never confirm. Fails closed.';

-- =============================================================================================
-- SECTION 6 — THE RESOLVER
-- =============================================================================================
--
-- Entity formation is the connected components of CONFIRMED_MATCH, and of nothing else. A
-- CANDIDATE_MATCH, a POSSIBLE_MATCH and an UNRESOLVED never merge anything; they are recorded
-- so Step 3B/3C can revisit them with parcel and geography evidence that does not exist yet.
--
-- p_apply = false is REPORT ONLY: it computes and returns the whole disposition and writes
-- nothing. That is the default, and it is how the design gate was run.

-- 🔑 WHY THERE IS NO UNION-FIND HERE, STATED AS A PROOF RATHER THAN A CONVENIENCE.
--    Entity formation is the connected components of CONFIRMED_MATCH. CONFIRMED_MATCH is
--    produced by exactly one rule (A1): equality of the tuple
--        (source_key, distribution_key, publisher_record_id).
--    Equality of a tuple is reflexive, symmetric and transitive, so its connected components
--    ARE its equivalence classes, and grouping by that tuple computes them exactly. A graph
--    traversal would return the same partition at more cost and more risk.
--    An observation with a NULL publisher_record_id can never satisfy A1, so it is always its
--    own component -- the correct conservative outcome, and the one every Epoch row takes.

-- ⚖️ RULE VERSION 2 (2026-09-24): THE PARTITION NOW HAS TWO KINDS OF EDGE, AND NO OTHER.
--   1. RECORD CONTINUITY: observations sharing a stable record key (dc_observation_record_key)
--      -- the publisher id, or a run-unique name for a source that supplies no id. Equality of
--      a key is still an equivalence relation, so grouping by it is still exact.
--   2. ACCOUNTABLE REVIEW: an active CONFIRMED_MATCH in dc_identity_review between two
--      cross-source record keys. Those edges are few, so their connected components are
--      computed by a small recursive walk over the review graph.
--   Nothing else links anything. A CANDIDATE / POSSIBLE / UNRESOLVED decision merges nothing.
--
-- 🔒 WRONG-SIBLING GUARD. A reviewed component that would contain two records of the SAME
--    source and distribution is REFUSED as a whole: every member falls back to its own record
--    key and nothing merges. A publisher separates its own records (A2); a review can never
--    fold two of them into one facility -- "Colossus 2" confirmed against both "Minihard" and
--    "Colossus 2 (Whitehaven)" merges neither.
--
-- ⚖️ ENTITY FOR A GROUP, deterministically, and stable across runs:
--    each existing entity is ANCHORED to the group of its best-ranked record key (publisher id
--    before name before singleton, then key order); a group's entity is the anchored entity
--    whose anchor key ranks best, then the oldest. Every other entity anchored to the same group
--    is superseded by it and its evidence relinked -- so a reviewed Atlas + Epoch pair keeps the
--    ATLAS entity (and its Map 1 marker id), and the one-time Epoch continuity consolidation
--    (270 run-minted entities -> one per record) is the same rule, not a special migration.
--    Evidence of a group an entity is NOT anchored to (a revoked or refused review) is moved to
--    that group's entity, minting one if needed: a merge is always reversible.
create or replace function public.dc_resolve_canonical(
    p_apply           boolean default false,
    p_include_history boolean default false
) returns table(metric text, value text)
language plpgsql
as $fn$
declare
    v_rule_version constant integer := 2;
    v_entities     integer;
    v_obs          integer;
    v_classified   integer;
    v_linked       integer;
    v_newly_linked integer := 0;
    v_minted       integer := 0;
    v_reused       integer := 0;
    v_relinked     integer := 0;
    v_superseded   integer := 0;
    v_reviews      integer := 0;
    v_refused      integer := 0;
begin
    drop table if exists _res_obs;
    drop table if exists _res_class;
    drop table if exists _res_decision;
    drop table if exists _res_edge;
    drop table if exists _res_comp;
    drop table if exists _res_refused;
    drop table if exists _res_key;
    drop table if exists _res_entity;
    drop table if exists _res_all;
    drop table if exists _res_anchor;
    drop table if exists _res_target;
    drop table if exists _res_new;

    -- The observation set under resolution. p_include_history is the HISTORICAL DUPLICATE TEST
    -- switch: it deliberately admits superseded runs so the resolver can be PROVEN to collapse
    -- them onto one entity instead of minting duplicates.
    create temporary table _res_obs on commit drop as
    select o.home_signal_observation_id oid, o.acquisition_run_id, o.source_key,
           o.distribution_key, o.publisher_record_id, o.source_native_name,
           o.source_native_type, o.source_native_precision, o.raw_payload,
           rk.record_key, rk.record_key_rank
      from public.dc_source_observation o
      join public.dc_observation_record_key rk
        on rk.home_signal_observation_id = o.home_signal_observation_id
     where p_include_history
        or o.home_signal_observation_id in (
              select c.home_signal_observation_id from public.dc_current_observation c);

    -- Classification, per observation, from the shipped function. One row per observation or
    -- the accounting check below fails -- a classifier that silently returns nothing would
    -- otherwise look identical to one that classified everything.
    create temporary table _res_class on commit drop as
    select r.oid, c.classification, c.rule_key, c.evidence
      from _res_obs r
      cross join lateral public.dc_classify_observation(
          r.source_key, r.distribution_key, r.source_native_type, r.raw_payload) c;

    -- Adjudicate every generated candidate pair (recorded; never a merge by itself).
    create temporary table _res_decision on commit drop as
    select k.observation_a, k.observation_b, k.candidate_rule_key,
           d.decision_state, d.decision_rule_key,
           d.evidence || jsonb_build_object('candidate_evidence', k.candidate_evidence) evidence
      from public.dc_identity_candidate k
      cross join lateral public.dc_adjudicate_pair(
          k.observation_a, k.observation_b, k.candidate_rule_key) d;

    -- Reviewed edges and their connected components.
    create temporary table _res_edge on commit drop as
    select r.record_key_a a, r.record_key_b b
      from public.dc_identity_review r
     where r.revoked_at is null and r.verdict = 'CONFIRMED_MATCH';
    select count(*) into v_reviews from _res_edge;

    create temporary table _res_comp on commit drop as
    with recursive adj(k, other) as (
        select a, b from _res_edge union select b, a from _res_edge
    ), walk(k, root) as (
        select k, k from adj
        union
        select j.other, w.root from walk w join adj j on j.k = w.k
    )
    select w.k as record_key, min(w.root collate "C") as comp from walk w group by w.k;

    -- 🔒 the wrong-sibling guard: two records of one source+distribution in one component
    create temporary table _res_refused on commit drop as
    select c.comp from _res_comp c
     group by c.comp
    having count(distinct split_part(c.record_key, '|', 1) || '|' || split_part(c.record_key, '|', 2))
           < count(*);
    select count(*) into v_refused from _res_refused;

    create temporary table _res_key on commit drop as
    select c.record_key,
           case when f.comp is null then c.comp else c.record_key end as group_key
      from _res_comp c left join _res_refused f on f.comp = c.comp;

    create temporary table _res_entity on commit drop as
    select r.oid, coalesce(k.group_key, r.record_key) as group_key, r.record_key, r.record_key_rank,
           case when k.group_key is not null and k.group_key <> r.record_key then 'REVIEWED_CONFIRMED_MATCH'
                when r.record_key_rank = 0 then 'SAME_SOURCE_SAME_PUBLISHER_RECORD_ID'
                when r.record_key_rank = 1 then 'SAME_SOURCE_SAME_NAME_UNIQUE_IN_RUN'
                else 'SINGLETON_NO_STABLE_RECORD_KEY' end as link_rule_key
      from _res_obs r left join _res_key k on k.record_key = r.record_key;

    select count(distinct group_key), count(*) into v_entities, v_obs from _res_entity;
    select count(*) into v_classified from _res_class;
    select count(*) into v_linked from (
        select group_key from _res_entity group by group_key having count(*) > 1) g;

    -- Every observation that is already linked, plus every one under resolution that is not.
    create temporary table _res_all on commit drop as
    select eo.home_signal_observation_id oid, eo.canonical_entity_id eid,
           rk.record_key, rk.record_key_rank,
           coalesce(k.group_key, rk.record_key) as group_key
      from public.dc_entity_observation eo
      join public.dc_observation_record_key rk
        on rk.home_signal_observation_id = eo.home_signal_observation_id
      left join _res_key k on k.record_key = rk.record_key
    union all
    select e.oid, null::uuid, e.record_key, e.record_key_rank, e.group_key
      from _res_entity e
     where not exists (select 1 from public.dc_entity_observation eo
                        where eo.home_signal_observation_id = e.oid);

    -- each existing entity's anchor: the group of its best-ranked record key
    create temporary table _res_anchor on commit drop as
    select distinct on (a.eid) a.eid, a.record_key anchor_key, a.record_key_rank anchor_rank,
           a.group_key anchor_group
      from _res_all a
     where a.eid is not null
     order by a.eid, a.record_key_rank, a.record_key collate "C";

    -- a group's entity: the anchored entity with the best anchor key, then the oldest
    create temporary table _res_target on commit drop as
    select distinct on (an.anchor_group) an.anchor_group group_key, an.eid target
      from _res_anchor an
      join public.dc_canonical_entity ce on ce.canonical_entity_id = an.eid
     order by an.anchor_group, an.anchor_rank, an.anchor_key collate "C", ce.created_at, an.eid;

    -- groups that still need an entity (new records; evidence split off by a revoked review)
    create temporary table _res_new on commit drop as
    select g.group_key, gen_random_uuid() canonical_entity_id
      from (select distinct group_key from _res_all) g
     where not exists (select 1 from _res_target t where t.group_key = g.group_key);
    select count(*) into v_minted from _res_new;
    select count(*) into v_reused from _res_target t
     where exists (select 1 from _res_entity e where e.group_key = t.group_key);
    select count(*) into v_relinked from _res_all a
      join _res_target t on t.group_key = a.group_key
     where a.eid is not null and a.eid <> t.target;
    select count(*) into v_superseded from _res_anchor an
      join _res_target t on t.group_key = an.anchor_group
      join public.dc_canonical_entity ce on ce.canonical_entity_id = an.eid
     where an.eid <> t.target and ce.superseded_by is distinct from t.target;

    if p_apply then
        insert into _res_target select group_key, canonical_entity_id from _res_new;

        insert into public.dc_canonical_entity
            (canonical_entity_id, entity_grain, classification, classification_conflict,
             rule_version, observation_count, source_count)
        select n.canonical_entity_id,
               -- GRAIN. The publisher's own statement is the only input. A record Atlas marks
               -- representative_multi_site, or annotates with a location.multiSite note, is NOT
               -- a site: on three of them the publisher says outright that the pin "is not a
               -- physical facility location". Such a record is held at its own grain rather
               -- than being treated as a site or split into sites we cannot individuate.
               case when bool_or(o.source_native_precision = 'representative_multi_site'
                                 or o.raw_payload->'location'->'multiSite' is not null)
                    then 'AGGREGATE_MULTI_SITE' else 'SITE' end,
               'CLASSIFICATION_UNRESOLVED', false, v_rule_version, 0, 0
          from _res_new n
          join _res_all a on a.group_key = n.group_key
          join public.dc_source_observation o on o.home_signal_observation_id = a.oid
         group by n.canonical_entity_id;

        -- relink evidence whose group's entity is another one (review merge, continuity
        -- consolidation, or a revoked review splitting evidence back out)
        update public.dc_entity_observation eo
           set canonical_entity_id = t.target,
               link_rule_key = case when a.group_key <> a.record_key then 'REVIEWED_CONFIRMED_MATCH'
                                    when a.record_key_rank = 1 then 'SAME_SOURCE_SAME_NAME_UNIQUE_IN_RUN'
                                    else eo.link_rule_key end,
               linked_at = now()
          from _res_all a
          join _res_target t on t.group_key = a.group_key
         where eo.home_signal_observation_id = a.oid
           and a.eid is not null and a.eid <> t.target;
        get diagnostics v_relinked = row_count;

        -- every other entity anchored to a group is superseded by that group's entity
        update public.dc_canonical_entity ce
           set superseded_by = t.target,
               supersede_reason = 'RULE_V2_SAME_GROUP: ' || an.anchor_group,
               updated_at = now()
          from _res_anchor an
          join _res_target t on t.group_key = an.anchor_group
         where ce.canonical_entity_id = an.eid
           and an.eid <> t.target
           and ce.superseded_by is distinct from t.target;
        get diagnostics v_superseded = row_count;

        insert into public.dc_entity_observation
            (canonical_entity_id, home_signal_observation_id, source_key, distribution_key,
             publisher_record_id, observation_classification, classification_rule_key,
             classification_evidence, link_rule_key)
        select t.target, o.oid, o.source_key, o.distribution_key, o.publisher_record_id,
               c.classification, c.rule_key, c.evidence, re.link_rule_key
          from _res_entity re
          join _res_obs    o on o.oid = re.oid
          join _res_class  c on c.oid = re.oid
          join _res_target t on t.group_key = re.group_key
        on conflict (home_signal_observation_id) do nothing;
        get diagnostics v_newly_linked = row_count;

        -- Counts and classification recomputed from each touched entity's OWN links, by the
        -- most-confirmed rule, so an entity can never disagree with the evidence attached to it.
        update public.dc_canonical_entity e
           set observation_count = s.n_obs,
               source_count      = s.n_src,
               classification    = s.cls,
               classification_conflict = s.conflict,
               updated_at        = now()
          from (select eo.canonical_entity_id,
                       count(*) n_obs, count(distinct eo.source_key) n_src,
                       case when bool_or(eo.observation_classification = 'CONFIRMED_DC') then 'CONFIRMED_DC'
                            when bool_or(eo.observation_classification = 'DC_CANDIDATE') then 'DC_CANDIDATE'
                            when bool_or(eo.observation_classification = 'CLASSIFICATION_UNRESOLVED')
                                 then 'CLASSIFICATION_UNRESOLVED'
                            else 'NON_DC' end cls,
                       count(distinct eo.observation_classification) > 1 conflict
                  from public.dc_entity_observation eo
                 where eo.canonical_entity_id in (select target from _res_target)
                 group by eo.canonical_entity_id) s
         where e.canonical_entity_id = s.canonical_entity_id
           and (e.observation_count, e.source_count, e.classification, e.classification_conflict)
               is distinct from (s.n_obs, s.n_src, s.cls, s.conflict);

        insert into public.dc_identity_decision
            (observation_a, observation_b, decision_state, candidate_rule_key,
             decision_rule_key, rule_version, evidence)
        select observation_a, observation_b, decision_state, candidate_rule_key,
               decision_rule_key, v_rule_version, evidence
          from _res_decision
        on conflict (observation_a, observation_b, candidate_rule_key) do nothing;
    end if;

    return query
        select 'MODE'::text, case when p_apply then 'APPLY' else 'REPORT_ONLY' end
        union all select 'INCLUDE_HISTORY', p_include_history::text
        union all select 'OBSERVATIONS_CONSIDERED', v_obs::text
        union all select 'OBSERVATIONS_CLASSIFIED', v_classified::text
        union all select 'PROPOSED_CANONICAL_ENTITIES', v_entities::text
        union all select 'MULTI_OBSERVATION_ENTITIES', v_linked::text
        union all select 'REVIEWS_ACTIVE_CONFIRMED_MATCH', v_reviews::text
        union all select 'REVIEW_COMPONENTS_REFUSED_SIBLING', v_refused::text
        union all select 'ENTITIES_MINTED', v_minted::text
        union all select 'GROUPS_ALREADY_ENTITIES', v_reused::text
        union all select 'OBSERVATIONS_RELINKED', v_relinked::text
        union all select 'ENTITIES_SUPERSEDED', v_superseded::text
        union all select 'OBSERVATIONS_NEWLY_LINKED',
               case when p_apply then v_newly_linked::text else 'n/a' end
        union all select 'ACCOUNTED_FOR',
               (select count(*) from _res_entity e join _res_class c on c.oid = e.oid)::text
        union all select 'OBS_' || upper(x.source_key), x.n::text
               from (select source_key, count(*) n from _res_obs group by source_key) x
        union all select 'CLASS_' || y.classification, y.n::text
               from (select classification, count(*) n from _res_class group by classification) y
        union all select 'DECISION_' || z.decision_state, z.n::text
               from (select decision_state, count(*) n from _res_decision group by decision_state) z
        union all select 'CANDIDATE_' || w.candidate_rule_key, w.n::text
               from (select candidate_rule_key, count(*) n from _res_decision
                      group by candidate_rule_key) w;
end;
$fn$;

comment on function public.dc_resolve_canonical(boolean, boolean) is
'STEP 3A resolver, rule version 2. Default REPORT ONLY. Entities are the connected components of
stable record continuity (publisher id, or a run-unique name for a source with no id) and of
accountable CONFIRMED_MATCH reviews -- nothing else. A reviewed component holding two records of
one source is refused whole. Merges keep the best-anchored entity and are reversible.';

-- ===== STEP 3B  docs/dc-step3b-canonical-geography.sql (changed objects) =====

-- rule_version 3: a derived point's positional uncertainty travels with the decision, so the ONE
-- membership authority (map1_dc_zip_members) can refuse a point whose error disk crosses a ZCTA.
alter table public.dc_entity_geography add column if not exists positional_uncertainty_m double precision;

create or replace function public.dc_resolve_geography(p_apply boolean default false)
returns table(metric text, value text)
language plpgsql
as $fn$
declare
    v_rule_version constant integer := 3;
    v_written integer := 0;
    v_pending integer;
begin
    -- ⛔ IDENTITY FIRST, OR NOTHING (2026-09-24). This resolver reads coordinates only through
    -- observations that identity has already linked to an entity. An acquisition that commits
    -- after the hour's identity run (:25) and before this one (:35) makes the CURRENT run a set
    -- of observations linked to nothing, and every entity then has "no coordinates" -- measured
    -- 2026-09-24 14:35Z: Atlas landed 14:26:42, all 2,870 live entities were rewritten
    -- GEOGRAPHY_UNRESOLVED, and Map 1 served ZERO canonical data centres until identity ran
    -- again. Unlinked current evidence is not evidence of absence, so the resolver refuses to
    -- decide anything until identity has caught up, and the last decided geography stands.
    select count(*) into v_pending
      from public.dc_current_observation c
     where not exists (select 1 from public.dc_entity_observation eo
                        where eo.home_signal_observation_id = c.home_signal_observation_id);
    if v_pending > 0 then
        return query
            select 'MODE'::text, case when p_apply then 'APPLY' else 'REPORT_ONLY' end
            union all select 'REFUSED_IDENTITY_PENDING', v_pending::text
            union all select 'ROWS_WRITTEN', '0';
        return;
    end if;

    drop table if exists _geo_pts;
    drop table if exists _geo_pick;
    drop table if exists _geo_out;
    drop table if exists _geo_open;
    drop table if exists _geo_derived;

    -- Every coordinate pair any CURRENT observation of an entity asserts -- the publisher's own
    -- points, and (rule_version 3) the ACCEPTED derived address points of Step 3D, which are a
    -- different kind of evidence and are labelled as such: basis DERIVED_ADDRESS, no publisher
    -- precision, and a positional uncertainty that Map 1 membership must respect.
    create temporary table _geo_pts on commit drop as
    select eo.canonical_entity_id, o.home_signal_observation_id oid, o.source_key,
           o.source_native_precision prec, o.source_native_lat lat, o.source_native_lon lng,
           least(scale(o.source_native_lat::text::numeric),
                 scale(o.source_native_lon::text::numeric)) decimals,
           o.observed_at, lb.basis, lb.rule_key basis_rule, lb.evidence basis_evidence,
           null::double precision uncertainty_m
      from public.dc_entity_observation eo
      join public.dc_current_observation c
        on c.home_signal_observation_id = eo.home_signal_observation_id
      join public.dc_source_observation o
        on o.home_signal_observation_id = eo.home_signal_observation_id
     cross join lateral public.dc_location_basis(o.source_key, o.distribution_key,
                                                 o.raw_payload) lb
     where o.source_native_lat is not null and o.source_native_lon is not null
       and o.source_native_lat between -90 and 90 and o.source_native_lon between -180 and 180
    union all
    select eo.canonical_entity_id, dp.home_signal_observation_id, dp.source_key,
           null::text, dp.lat, dp.lng, 6, o.observed_at,
           'DERIVED_ADDRESS'::text, dp.match_type,
           jsonb_build_object('derivation_id', dp.derivation_id, 'geocoder_query', dp.geocoder_query,
                              'matched_address', dp.matched_address, 'provider', dp.provider,
                              'match_type', dp.match_type,
                              'provider_candidates', dp.provider_candidates,
                              'derived_at', dp.derived_at, 'run_ref', dp.run_ref,
                              'verdict', dp.verdict, 'verdict_reason', dp.verdict_reason),
           dp.positional_uncertainty_m
      from public.dc_entity_observation eo
      join public.dc_observation_derived_point dp
        on dp.home_signal_observation_id = eo.home_signal_observation_id
      join public.dc_source_observation o
        on o.home_signal_observation_id = eo.home_signal_observation_id
     where dp.verdict = 'ACCEPTED';

    -- Why each entity's derived location did or did not qualify (reported, never a point).
    create temporary table _geo_derived on commit drop as
    select distinct on (eo.canonical_entity_id) eo.canonical_entity_id,
           jsonb_build_object('input_quality', dp.input_quality, 'geocoder_query', dp.geocoder_query,
                              'verdict', dp.verdict, 'reason', dp.verdict_reason,
                              'match_type', dp.match_type, 'matched_address', dp.matched_address) derived
      from public.dc_entity_observation eo
      join public.dc_observation_derived_point dp
        on dp.home_signal_observation_id = eo.home_signal_observation_id
     order by eo.canonical_entity_id, (dp.verdict = 'ACCEPTED') desc, dp.home_signal_observation_id;

    -- ⛔ IDENTITY BEFORE A DERIVED MARKER. An entity with an OPEN cross-source identity question
    -- -- a surfaced candidate pair with another data-centre entity that no person has decided
    -- CONFIRMED_DISTINCT (and that did not merge) -- may not be PLACED by a derived point: the
    -- other entity may be the same facility, and two markers for one site is the defect.
    -- Publisher points are unaffected (their behaviour before rule_version 3 is unchanged).
    create temporary table _geo_open on commit drop as
    select distinct x.canonical_entity_id
      from public.dc_identity_candidate k
      join public.dc_entity_observation x
        on x.home_signal_observation_id in (k.observation_a, k.observation_b)
      join public.dc_entity_observation y
        on y.home_signal_observation_id in (k.observation_a, k.observation_b)
       and y.home_signal_observation_id <> x.home_signal_observation_id
      join public.dc_canonical_entity ye on ye.canonical_entity_id = y.canonical_entity_id
     cross join lateral public.dc_adjudicate_pair(k.observation_a, k.observation_b,
                                                  k.candidate_rule_key) d
     where x.source_key <> y.source_key
       and y.canonical_entity_id <> x.canonical_entity_id
       and ye.superseded_by is null
       and ye.classification in ('CONFIRMED_DC', 'DC_CANDIDATE')
       and d.decision_state <> 'CONFIRMED_DISTINCT';

    create temporary table _geo_pick on commit drop as
    select distinct on (canonical_entity_id) *
      from _geo_pts
     order by canonical_entity_id, (basis = 'NON_SITE_AREA'), (basis = 'DERIVED_ADDRESS'),
              (prec = 'exact') desc nulls last,
              decimals desc,
              observed_at desc, oid;

    create temporary table _geo_out on commit drop as
    with base as (
        select e.canonical_entity_id, e.entity_grain, p.oid, p.source_key, p.prec, p.lat,
               p.lng, p.decimals, p.basis, p.basis_rule, p.basis_evidence, p.uncertainty_m,
               -- A publisher's town/area point is not a claim about the SITE (rule_version 2),
               -- so it can neither disagree with nor be agreed with: only site claims -- publisher
               -- site points and accepted derived points -- are compared.
               exists (select 1 from _geo_pts a join _geo_pts b
                         on a.canonical_entity_id = b.canonical_entity_id
                        and a.source_key < b.source_key
                        where a.canonical_entity_id = e.canonical_entity_id
                          and a.basis <> 'NON_SITE_AREA' and b.basis <> 'NON_SITE_AREA'
                          and ST_DistanceSphere(ST_MakePoint(a.lng, a.lat),
                                                ST_MakePoint(b.lng, b.lat)) > 1000) disagree,
               e.canonical_entity_id in (select canonical_entity_id from _geo_open) identity_open,
               (select dd.derived from _geo_derived dd
                 where dd.canonical_entity_id = e.canonical_entity_id) derived,
               exists (select 1 from _geo_pick q
                        where q.canonical_entity_id <> e.canonical_entity_id
                          and q.lat = p.lat and q.lng = p.lng) shared
          from public.dc_canonical_entity e
          left join _geo_pick p on p.canonical_entity_id = e.canonical_entity_id
         where e.superseded_by is null)
    select b.*,
           case when b.entity_grain = 'AGGREGATE_MULTI_SITE' then 'NOT_A_SITE'
                when b.oid is null or b.disagree or b.decimals <= 1 then 'GEOGRAPHY_UNRESOLVED'
                when b.basis = 'NON_SITE_AREA' then 'GEOGRAPHY_UNRESOLVED'
                when b.basis = 'DERIVED_ADDRESS' and b.identity_open then 'GEOGRAPHY_UNRESOLVED'
                when b.basis = 'DERIVED_ADDRESS' and b.shared then 'GEOGRAPHY_UNRESOLVED'
                else 'RESOLVED' end status,
           case when b.entity_grain = 'AGGREGATE_MULTI_SITE' then 'PUBLISHER_MULTI_SITE'
                when b.oid is null then 'NO_COORDINATES'
                when b.disagree then 'SOURCES_DISAGREE'
                when b.decimals <= 1 then 'ROUNDED_COORDINATES'
                when b.basis = 'NON_SITE_AREA' then 'PUBLISHER_AREA_POINT'
                when b.basis = 'DERIVED_ADDRESS' and b.identity_open then 'IDENTITY_REVIEW_REQUIRED'
                when b.basis = 'DERIVED_ADDRESS' and b.shared then 'DERIVED_ADDRESS_SHARED'
                when b.basis = 'DERIVED_ADDRESS' then 'DERIVED_ADDRESS_POINT'
                else 'PUBLISHER_POINT' end rule_key,
           array_remove(array[
               case when b.oid is not null and b.decimals <= 1 then 'ROUNDED_COORDINATES' end,
               case when b.oid is not null and (b.decimals <= 1 or b.basis = 'NON_SITE_AREA')
                         and b.prec = 'exact'
                    then 'PUBLISHER_CLAIMS_EXACT' end,
               case when b.basis = 'NON_SITE_AREA' then 'PUBLISHER_AREA_POINT' end,
               case when b.basis = 'NON_SITE_ROAD' then 'PUBLISHER_ROAD_REFERENCE' end,
               case when b.basis = 'DERIVED_ADDRESS' then 'DERIVED_ADDRESS_POINT' end,
               case when b.basis = 'DERIVED_ADDRESS' and b.identity_open then 'IDENTITY_REVIEW_REQUIRED' end,
               case when b.decimals = 2 then 'COARSE_COORDINATES' end,
               case when b.prec = 'approximate' then 'PUBLISHER_APPROXIMATE' end,
               case when b.shared then 'SHARED_COORDINATES' end,
               case when b.disagree then 'SOURCES_DISAGREE' end,
               case when b.oid is null then 'NO_COORDINATES' end], null) flags
      from base b;

    if p_apply then
        insert into public.dc_entity_geography as g
            (canonical_entity_id, geography_status, geometry_type, geom, lat, lng,
             coordinate_decimals, authority_source_key, authority_observation_id,
             publisher_precision, quality_flags, rule_key, rule_version, provenance,
             positional_uncertainty_m)
        select canonical_entity_id, status,
               case when status = 'RESOLVED' then 'POINT' end,
               case when status = 'RESOLVED' then ST_SetSRID(ST_MakePoint(lng, lat), 4326) end,
               lat, lng, decimals, source_key, oid, prec, flags, rule_key, v_rule_version,
               jsonb_build_object('rule', rule_key, 'observation', oid,
                                  'location_basis', basis, 'location_basis_rule', basis_rule,
                                  'location_basis_evidence', basis_evidence,
                                  'positional_uncertainty_m', uncertainty_m,
                                  'derived_location', derived),
               case when status = 'RESOLVED' then uncertainty_m end
          from _geo_out
        on conflict (canonical_entity_id) do update
           set geography_status = excluded.geography_status,
               geometry_type = excluded.geometry_type, geom = excluded.geom,
               lat = excluded.lat, lng = excluded.lng,
               coordinate_decimals = excluded.coordinate_decimals,
               authority_source_key = excluded.authority_source_key,
               authority_observation_id = excluded.authority_observation_id,
               publisher_precision = excluded.publisher_precision,
               quality_flags = excluded.quality_flags, rule_key = excluded.rule_key,
               rule_version = excluded.rule_version, provenance = excluded.provenance,
               positional_uncertainty_m = excluded.positional_uncertainty_m,
               updated_at = now()
         where (g.geography_status, g.lat, g.lng, g.quality_flags, g.rule_key,
                g.authority_observation_id, g.rule_version, g.positional_uncertainty_m, g.provenance)
               is distinct from
               (excluded.geography_status, excluded.lat, excluded.lng, excluded.quality_flags,
                excluded.rule_key, excluded.authority_observation_id, excluded.rule_version,
                excluded.positional_uncertainty_m, excluded.provenance);
        get diagnostics v_written = row_count;
    end if;

    return query
        select 'MODE'::text, case when p_apply then 'APPLY' else 'REPORT_ONLY' end
        union all select 'ENTITIES', count(*)::text from _geo_out
        union all select 'ROWS_WRITTEN', case when p_apply then v_written::text else 'n/a' end
        union all select 'STATUS_' || s.status, s.n::text
               from (select status, count(*) n from _geo_out group by status) s
        union all select 'RULE_' || r.rule_key, r.n::text
               from (select rule_key, count(*) n from _geo_out group by rule_key) r
        union all select 'FLAG_' || f.flag, f.n::text
               from (select flag, count(*) n from _geo_out, unnest(flags) flag group by flag) f;
end;
$fn$;

comment on function public.dc_resolve_geography(boolean) is
'STEP 3B resolver. Default REPORT ONLY. Decides each canonical entity''s geography from its
current observations by column-level rules (grain, coordinates present, source agreement,
decimal places); never by place, project or source name. Idempotent: an unchanged entity is
not rewritten.';

-- ===== MAP 1    docs/map1-dc-publication.sql =====

create or replace function public.map1_dc_zip_members(p_zip text)
returns table(source_key text, source_name text, source_url text, source_licence text,
              project_name text, developer_or_operator text, raw_status text,
              normalized_status text, map_status text, project_type text,
              lat double precision, lng double precision, location_text text,
              location_precision text, distance_mi numeric, last_seen_at timestamptz,
              has_more boolean, zip_membership text, canonical_entity_id uuid,
              publication_basis text, quality_flags text[], source_count integer)
language sql
stable
security definer
set search_path to 'public', 'geo', 'pg_temp'
as $function$
  with
  -- THE ONE LIFECYCLE MAP: source lifecycle word -> Map 1 permit-vocabulary pin status.
  lifecycle(v, map_status) as (values
    ('operational',        'Operating'),
    ('under_construction', 'Approved'),
    ('permitted',          'Approved'),
    ('proposed',           'Proposed')),
  g as (select geo.zip_membership_boundary(p_zip) as geom),
  bb as (select geom, ST_XMin(geom) x0, ST_XMax(geom) x1, ST_YMin(geom) y0, ST_YMax(geom) y1
           from g where geom is not null),
  lim as (select 1000::int as n),
  -- every PUBLISHABLE canonical entity in the box (1e-4 deg margin so an identical-coordinate
  -- compatibility pairing on the box edge is still seen from both sides)
  canon as (
    select 'dc:' || e.canonical_entity_id::text as source_key,
           s.publisher as source_name, u.url as source_url, s.licence as source_licence,
           o.source_native_name as project_name,
           nullif(btrim(o.source_native_operator), '') as developer_or_operator,
           o.source_native_status as raw_status, o.source_native_status as normalized_status,
           lc.map_status, 'datacenter'::text as project_type, ge.lat, ge.lng,
           nullif(concat_ws(', ', o.source_native_address->>'street',
                                  o.source_native_address->>'city',
                                  o.source_native_address->>'state'), '') as location_text,
           case when ge.publisher_precision = 'exact' then 'precise_location'
                else 'approximate_campus_area' end as location_precision,
           o.observed_at as last_seen_at, e.canonical_entity_id,
           'canonical'::text as publication_basis, ge.quality_flags, e.source_count,
           ge.positional_uncertainty_m
      from bb
      join public.dc_entity_geography ge
        on ge.lat between bb.y0 - 1e-4 and bb.y1 + 1e-4
       and ge.lng between bb.x0 - 1e-4 and bb.x1 + 1e-4
      join public.dc_canonical_entity e on e.canonical_entity_id = ge.canonical_entity_id
      -- THE DESCRIPTOR (2026-09-24): name, operator, lifecycle, address and citation come from
      -- the entity's CURRENT observation that states a displayable lifecycle -- the location
      -- authority itself when it does (every single-source entity: behaviour unchanged), else
      -- another observation of the same entity. Location evidence and descriptive evidence are
      -- different facts; an entity placed by a derived address point (whose source states no
      -- lifecycle) is described by the source that does. Source-agnostic: no source is named.
      cross join lateral (
        select x.*
          from public.dc_entity_observation eo2
          join public.dc_current_observation cx
            on cx.home_signal_observation_id = eo2.home_signal_observation_id
          join public.dc_source_observation x
            on x.home_signal_observation_id = eo2.home_signal_observation_id
          join lifecycle lx on lx.v = x.source_native_status
         where eo2.canonical_entity_id = e.canonical_entity_id
         order by (x.home_signal_observation_id = ge.authority_observation_id) desc,
                  x.observed_at desc, x.home_signal_observation_id
         limit 1) o
      join public.dc_source s on s.source_key = o.source_key
      join lifecycle lc on lc.v = o.source_native_status
      cross join lateral (
        select x->>'url' as url
          from jsonb_array_elements(case when jsonb_typeof(o.raw_payload->'sources') = 'array'
                                         then o.raw_payload->'sources' else '[]'::jsonb end)
               with ordinality t(x, i)
         where x->>'url' ~ '^https?://'
         order by i limit 1) u
     where e.superseded_by is null
       and e.classification = 'CONFIRMED_DC'
       and ge.geography_status = 'RESOLVED'
       and ge.geometry_type = 'POINT'),
  -- TRANSITIONAL compatibility population (see header for its retirement condition)
  osm as (
    select r.source_key, r.source_name, r.source_url,
           'ODbL, © OpenStreetMap contributors'::text as source_licence,
           r.project_name, r.developer_or_operator, r.raw_status, r.normalized_status,
           lc.map_status, r.project_type, r.lat, r.lng, r.location_text, r.location_precision,
           r.last_seen_at, null::uuid as canonical_entity_id,
           'legacy_osm_compat'::text as publication_basis, '{}'::text[] as quality_flags,
           1 as source_count, null::double precision as positional_uncertainty_m
      from bb
      join public.national_dc_records r
        on r.lat between bb.y0 - 1e-4 and bb.y1 + 1e-4
       and r.lng between bb.x0 - 1e-4 and bb.x1 + 1e-4
      join lifecycle lc on lc.v = r.normalized_status
     where r.map_eligible),
  osm_kept as (
    select o.* from osm o
     where not (
       (select count(*) from canon c
         where ST_DistanceSphere(ST_MakePoint(c.lng, c.lat), ST_MakePoint(o.lng, o.lat)) <= 1) = 1
       and (select count(*) from osm o2, canon c
             where ST_DistanceSphere(ST_MakePoint(c.lng, c.lat), ST_MakePoint(o.lng, o.lat)) <= 1
               and ST_DistanceSphere(ST_MakePoint(c.lng, c.lat), ST_MakePoint(o2.lng, o2.lat)) <= 1) = 1)),
  pool as (select * from canon union all select * from osm_kept),
  judged as (
    select p.*, geo.zip_point_membership_in(bb.geom, p.lat, p.lng) as verdict,
           -- EDGE AMBIGUITY FAILS CLOSED (2026-09-24). Membership is boundary-inclusive, so a
           -- point exactly on an edge two ZCTAs share is a member of BOTH, and would publish on
           -- two ZIP pages. It is withheld instead: never the nearest, never an arbitrary pick.
           -- Measured when written: 0 of 3,497 candidate points touch more than one ZCTA.
           -- UNCERTAIN POINTS (2026-09-24): a point that carries a positional uncertainty (a
           -- derived address point: calibrated max error 2,000 m) is a member only when EVERY
           -- position it could truly occupy is in this ZCTA -- the whole disk within one ZCTA.
           -- Road centrelines are ZCTA edges: 5 of 35 geocoded Epoch addresses sat 6-26 m from
           -- one. The same rule as the edge guard above, with a radius; NULL radius = unchanged.
           case when p.positional_uncertainty_m is null then
             (select count(*) from geo.zcta_boundary z
               where z.geom is not null
                 and ST_Intersects(z.geom, ST_SetSRID(ST_MakePoint(p.lng, p.lat), 4269)))
           else
             (select count(*) from geo.zcta_boundary z
               where z.geom is not null
                 and z.geom && ST_Expand(ST_SetSRID(ST_MakePoint(p.lng, p.lat), 4269),
                                         p.positional_uncertainty_m / 25000.0)
                 and ST_DWithin(z.geom::geography,
                                ST_SetSRID(ST_MakePoint(p.lng, p.lat), 4269)::geography,
                                p.positional_uncertainty_m))
           end as zcta_hits
      from pool p, bb),
  members as (
    select * from judged where verdict = 'member' and zcta_hits <= 1
     order by source_key collate "C"
     limit (select n + 1 from lim)),
  counted as (select count(*) over () as total, members.* from members)
  select c.source_key, c.source_name, c.source_url, c.source_licence, c.project_name,
         c.developer_or_operator, c.raw_status, c.normalized_status, c.map_status,
         c.project_type, c.lat, c.lng, c.location_text, c.location_precision,
         null::numeric as distance_mi, c.last_seen_at,
         (c.total > (select n from lim)) as has_more, c.verdict as zip_membership,
         c.canonical_entity_id, c.publication_basis, c.quality_flags, c.source_count
    from counted c
   order by c.source_key collate "C"
   limit (select n from lim);
$function$;

revoke all on function public.map1_dc_zip_members(text) from public;

grant execute on function public.map1_dc_zip_members(text) to anon, authenticated, service_role;

comment on function public.map1_dc_zip_members(text) is
  'THE one Map 1 data-centre read for every ZIP page: CONFIRMED_DC canonical entities with '
  'RESOLVED point geography and a displayable lifecycle, plus the transitional legacy OSM '
  'compatibility population, each admitted only on geo.zip_point_membership_in = member. '
  'docs/map1-dc-publication.sql.';

commit;
