-- GENERATED by test/dc_osm_layer_pg/build_map1.py. Do not edit.

-- C3c ROLLBACK: withdraw the OSM layer check from the admission switch and restore the pre-C3c

-- Map 1 reader (both bodies proven to fingerprint to production before C3c). Applied only by

-- dc-osm-map1-apply.yml with confirm=ROLLBACK-OSM-MAP1-C3C.

begin;

do $guard$
declare bad text := '';
begin
  if (select md5(p.prosrc) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
        where n.nspname = 'public' and p.proname = 'dc_derived_address_admitted') is distinct from '2c05d65aba736fab7c79199e78614ab6' then bad := bad || ' dc_derived_address_admitted'; end if;
  if (select md5(p.prosrc) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
        where n.nspname = 'public' and p.proname = 'map1_dc_zip_members') is distinct from '2146b68afc2cda03948b1e1cd51b29b8' then bad := bad || ' map1_dc_zip_members'; end if;
  if (select md5(p.prosrc) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
        where n.nspname = 'public' and p.proname = 'dc_publisher_stated_address') is distinct from '7605c217d2d4d4fb0e36cff42015b0f1' then bad := bad || ' dc_publisher_stated_address'; end if;
  if to_regclass('public.dc_osm_derived_point') is null or to_regclass('public.dc_osm_address_check') is null then
    bad := bad || ' (the C3a OSM views are missing)';
  end if;
  if not public.dc_derived_address_admitted('openstreetmap', 'telecom_data_center')
     or not public.dc_derived_address_admitted('compute_atlas', 'facilities')
     or not public.dc_derived_address_admitted('epoch_ai', 'data_centers')
     or public.dc_derived_address_admitted('openstreetmap', 'other')
     or public.dc_derived_address_admitted('some_new_source', 'facilities') then
    bad := bad || ' (admission)';
  end if;
  if not has_function_privilege('anon', 'public.map1_dc_zip_members(text)', 'execute') then
    bad := bad || ' (anon cannot execute the Map 1 reader)';
  end if;
  if bad <> '' then
    raise exception 'DRIFT: production does not carry the C3c definitions this rollback reverses:%', bad;
  end if;
end $guard$;

-- ── ADMISSION: which extractions' derivations may reach canonical decisions ───────────────
-- Acquiring derived evidence and letting it change decisions are two deployments, not one. A new
-- extraction is admitted only after a national dry run of its consequences has been reviewed as a
-- system (docs/dc-atlas-dryrun-report.sql). Until then its derivations are written and reported
-- (dc_observation_derived_point.admitted = false) and change NOTHING: not the geography evidence,
-- not the geography provenance, not the identity candidates.
-- This is a deployment gate over an extraction, never an authority rank: an admitted derivation is
-- judged by the SAME class rules as every other, and a non-admitted one is simply absent.
-- Admitting an extraction = one reviewed edit to this function (the committed-switch pattern).
--   epoch_ai/data_centers   admitted 2026-09-24 (#1324, national dry run 36058486723)
--   compute_atlas/facilities admitted 2026-09-26 (stage 10), after the admission dry run on that
--                            day's production copy (dc-atlas-admission-dryrun.yml, run 36253526398:
--                            1 facility added, 26 withheld, 0 moved), reviewed by the founder.
--                            Applied by scripts/dc-atlas-admission-apply.sh.
--   openstreetmap/telecom_data_center admitted (C3c) -- the SEPARATE OSM layer's address check. It
--                            reaches no canonical decision (OSM is never a dc_source_observation);
--                            it lets map1_dc_zip_members withhold an OSM pin its own address
--                            contradicts and flag one it corroborates. Gated by
--                            scripts/dc-osm-map1-gate.sh on a replica of production; applied by
--                            scripts/dc-osm-map1-apply.sh.
create or replace function public.dc_derived_address_admitted(p_source_key text, p_distribution_key text)
returns boolean
language sql
immutable
set search_path to 'public', 'pg_temp'
as $$ select (p_source_key, p_distribution_key) in (('epoch_ai', 'data_centers'), ('compute_atlas', 'facilities')) $$;

comment on function public.dc_derived_address_admitted(text, text) is
'STEP 3D. Deployment gate: whether an extraction''s derivations may reach geography and identity.
Binary admission of a reviewed extraction, never a rank. See the header of this section.';

create or replace function public.map1_dc_zip_members(p_zip text)
returns table(source_key text, source_name text, source_url text, source_licence text,
              project_name text, developer_or_operator text, raw_status text,
              normalized_status text, map_status text, project_type text,
              lat double precision, lng double precision, location_text text,
              location_precision text, distance_mi numeric, last_seen_at timestamptz,
              has_more boolean, zip_membership text, canonical_entity_id uuid,
              publication_basis text, quality_flags text[], source_count integer)
language sql
stable
security definer
set search_path to 'public', 'geo', 'pg_temp'
as $function$
  with
  -- THE ONE LIFECYCLE MAP: source lifecycle word -> Map 1 permit-vocabulary pin status.
  lifecycle(v, map_status) as (values
    ('operational',        'Operating'),
    ('under_construction', 'Approved'),
    ('permitted',          'Approved'),
    ('proposed',           'Proposed')),
  g as (select geo.zip_membership_boundary(p_zip) as geom),
  bb as (select geom, ST_XMin(geom) x0, ST_XMax(geom) x1, ST_YMin(geom) y0, ST_YMax(geom) y1
           from g where geom is not null),
  lim as (select 1000::int as n),
  -- every PUBLISHABLE canonical entity in the box (1e-4 deg margin so an identical-coordinate
  -- compatibility pairing on the box edge is still seen from both sides)
  canon as (
    select 'dc:' || e.canonical_entity_id::text as source_key,
           s.publisher as source_name, o.cite as source_url, s.licence as source_licence,
           o.source_native_name as project_name,
           nullif(btrim(o.source_native_operator), '') as developer_or_operator,
           o.source_native_status as raw_status, o.source_native_status as normalized_status,
           coalesce(lc.map_status, 'Unknown') as map_status, 'datacenter'::text as project_type, ge.lat, ge.lng,
           nullif(concat_ws(', ', o.source_native_address->>'street',
                                  o.source_native_address->>'city',
                                  o.source_native_address->>'state'), '') as location_text,
           case when ge.publisher_precision = 'exact' then 'precise_location'
                else 'approximate_campus_area' end as location_precision,
           o.observed_at as last_seen_at, e.canonical_entity_id,
           'canonical'::text as publication_basis, ge.quality_flags, e.source_count,
           ge.positional_uncertainty_m
      from bb
      join public.dc_entity_geography ge
        on ge.lat between bb.y0 - 1e-4 and bb.y1 + 1e-4
       and ge.lng between bb.x0 - 1e-4 and bb.x1 + 1e-4
      join public.dc_canonical_entity e on e.canonical_entity_id = ge.canonical_entity_id
      -- THE DESCRIPTOR (2026-09-24): name, operator, lifecycle, address and citation come from
      -- the entity's CURRENT observation that states a displayable lifecycle -- the location
      -- authority itself when it does (every single-source entity: behaviour unchanged), else
      -- another observation of the same entity; only when NO observation states a lifecycle,
      -- an observation that states none (published as 'Unknown', see the header). Location
      -- evidence and descriptive evidence are different facts; an entity placed by a derived
      -- address point is described by the source that states its lifecycle. Source-agnostic.
      cross join lateral (
        select x.*, public.dc_record_citation(x.source_key, x.distribution_key, x.raw_payload) as cite
          from public.dc_entity_observation eo2
          join public.dc_current_observation cx
            on cx.home_signal_observation_id = eo2.home_signal_observation_id
          join public.dc_source_observation x
            on x.home_signal_observation_id = eo2.home_signal_observation_id
         where eo2.canonical_entity_id = e.canonical_entity_id
           and (x.source_native_status is null
                or x.source_native_status in (select lx.v from lifecycle lx))
         order by (x.source_native_status is not null) desc,
                  (x.home_signal_observation_id = ge.authority_observation_id) desc,
                  x.observed_at desc, x.home_signal_observation_id
         limit 1) o
      join public.dc_source s on s.source_key = o.source_key
      left join lifecycle lc on lc.v = o.source_native_status
     where e.superseded_by is null
       and e.classification = 'CONFIRMED_DC'
       and ge.geography_status = 'RESOLVED'
       and ge.geometry_type = 'POINT'
       and o.cite is not null
       -- a STATED lifecycle must be displayable; silence is 'Unknown' only when EVERY current
       -- observation of the entity is silent (a stated 'cancelled' is never outvoted by silence)
       and (lc.map_status is not null
            or not exists (
                 select 1 from public.dc_entity_observation eo3
                   join public.dc_current_observation c3
                     on c3.home_signal_observation_id = eo3.home_signal_observation_id
                  where eo3.canonical_entity_id = e.canonical_entity_id
                    and c3.source_native_status is not null))),
  -- TRANSITIONAL compatibility population (see header for its retirement condition)
  osm as (
    select r.source_key, r.source_name, r.source_url,
           'ODbL, © OpenStreetMap contributors'::text as source_licence,
           r.project_name, r.developer_or_operator, r.raw_status, r.normalized_status,
           lc.map_status, r.project_type, r.lat, r.lng, r.location_text, r.location_precision,
           r.last_seen_at, null::uuid as canonical_entity_id,
           'legacy_osm_compat'::text as publication_basis, '{}'::text[] as quality_flags,
           1 as source_count, null::double precision as positional_uncertainty_m
      from bb
      join public.national_dc_records r
        on r.lat between bb.y0 - 1e-4 and bb.y1 + 1e-4
       and r.lng between bb.x0 - 1e-4 and bb.x1 + 1e-4
      join lifecycle lc on lc.v = r.normalized_status
     where r.map_eligible),
  osm_kept as (
    select o.* from osm o
     where not (
       (select count(*) from canon c
         where ST_DistanceSphere(ST_MakePoint(c.lng, c.lat), ST_MakePoint(o.lng, o.lat)) <= 1) = 1
       and (select count(*) from osm o2, canon c
             where ST_DistanceSphere(ST_MakePoint(c.lng, c.lat), ST_MakePoint(o.lng, o.lat)) <= 1
               and ST_DistanceSphere(ST_MakePoint(c.lng, c.lat), ST_MakePoint(o2.lng, o2.lat)) <= 1) = 1)),
  pool as (select * from canon union all select * from osm_kept),
  judged as (
    select p.*, geo.zip_point_membership_in(bb.geom, p.lat, p.lng) as verdict,
           -- EDGE AMBIGUITY FAILS CLOSED (2026-09-24). Membership is boundary-inclusive, so a
           -- point exactly on an edge two ZCTAs share is a member of BOTH, and would publish on
           -- two ZIP pages. It is withheld instead: never the nearest, never an arbitrary pick.
           -- Measured when written: 0 of 3,497 candidate points touch more than one ZCTA.
           -- UNCERTAIN POINTS (2026-09-24): a point that carries a positional uncertainty (a
           -- derived address point: calibrated max error 2,000 m) is a member only when EVERY
           -- position it could truly occupy is in this ZCTA -- the whole disk within one ZCTA.
           -- Road centrelines are ZCTA edges: 5 of 35 geocoded Epoch addresses sat 6-26 m from
           -- one. The same rule as the edge guard above, with a radius; NULL radius = unchanged.
           case when p.positional_uncertainty_m is null then
             (select count(*) from geo.zcta_boundary z
               where z.geom is not null
                 and ST_Intersects(z.geom, ST_SetSRID(ST_MakePoint(p.lng, p.lat), 4269)))
           else
             (select count(*) from geo.zcta_boundary z
               where z.geom is not null
                 and z.geom && ST_Expand(ST_SetSRID(ST_MakePoint(p.lng, p.lat), 4269),
                                         p.positional_uncertainty_m / 25000.0)
                 and ST_DWithin(z.geom::geography,
                                ST_SetSRID(ST_MakePoint(p.lng, p.lat), 4269)::geography,
                                p.positional_uncertainty_m))
           end as zcta_hits
      from pool p, bb),
  members as (
    select * from judged where verdict = 'member' and zcta_hits <= 1
     order by source_key collate "C"
     limit (select n + 1 from lim)),
  counted as (select count(*) over () as total, members.* from members)
  select c.source_key, c.source_name, c.source_url, c.source_licence, c.project_name,
         c.developer_or_operator, c.raw_status, c.normalized_status, c.map_status,
         c.project_type, c.lat, c.lng, c.location_text, c.location_precision,
         null::numeric as distance_mi, c.last_seen_at,
         (c.total > (select n from lim)) as has_more, c.verdict as zip_membership,
         c.canonical_entity_id, c.publication_basis, c.quality_flags, c.source_count
    from counted c
   order by c.source_key collate "C"
   limit (select n from lim);
$function$;

revoke all on function public.map1_dc_zip_members(text) from public;

grant execute on function public.map1_dc_zip_members(text) to anon, authenticated, service_role;

comment on function public.map1_dc_zip_members(text) is
  'THE one Map 1 data-centre read for every ZIP page: CONFIRMED_DC canonical entities with '
  'RESOLVED point geography and a displayable lifecycle, plus the transitional legacy OSM '
  'compatibility population, each admitted only on geo.zip_point_membership_in = member. '
  'docs/map1-dc-publication.sql.';

do $post$
declare bad text := '';
begin
  if (select md5(p.prosrc) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
        where n.nspname = 'public' and p.proname = 'dc_derived_address_admitted') is distinct from '31cb6c9e7481311ab33042a8845c9276' then bad := bad || ' dc_derived_address_admitted'; end if;
  if (select md5(p.prosrc) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
        where n.nspname = 'public' and p.proname = 'map1_dc_zip_members') is distinct from '9fc1c9f51375f25db5658a14ca36937c' then bad := bad || ' map1_dc_zip_members'; end if;
  if (select md5(p.prosrc) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
        where n.nspname = 'public' and p.proname = 'dc_publisher_stated_address') is distinct from '7605c217d2d4d4fb0e36cff42015b0f1' then bad := bad || ' dc_publisher_stated_address'; end if;
  if to_regclass('public.dc_osm_derived_point') is null or to_regclass('public.dc_osm_address_check') is null then
    bad := bad || ' (the C3a OSM views are missing)';
  end if;
  if public.dc_derived_address_admitted('openstreetmap', 'telecom_data_center')
     or not public.dc_derived_address_admitted('compute_atlas', 'facilities')
     or not public.dc_derived_address_admitted('epoch_ai', 'data_centers')
     or public.dc_derived_address_admitted('openstreetmap', 'other')
     or public.dc_derived_address_admitted('some_new_source', 'facilities') then
    bad := bad || ' (admission)';
  end if;
  if not has_function_privilege('anon', 'public.map1_dc_zip_members(text)', 'execute') then
    bad := bad || ' (anon cannot execute the Map 1 reader)';
  end if;
  if bad <> '' then
    raise exception 'POST-CONDITION failed:%. Rolled back.', bad;
  end if;
end $post$;

commit;
