-- GENERATED by test/dc_osm_layer_pg/build_apply.py. Do not edit.

-- C3a ROLLBACK: remove the OpenStreetMap layer's address check, restoring the pre-C3a

-- extraction and queue. Tested offline; applied only by dc-osm-layer-apply.yml with

-- confirm=ROLLBACK-OSM-LAYER-C3A. Derivations already in dc_address_geocode are left in place

-- (append-only evidence; nothing reads an OSM query once the views are gone).

begin;

do $guard$
declare r record; bad text := '';
begin
  for r in select * from (values ('dc_derived_address_admitted', '31cb6c9e7481311ab33042a8845c9276'), ('dc_derived_point_verdict', '4cd5b97def7d6179900cd95ec452d9a7'), ('dc_geocodable_site_address', 'a5c2ef9940d63bc55dceeede44e28f95'), ('dc_geocode_input', '655ff9b7ade2234745669dae8d146bcf'), ('dc_geocode_ladder_version', 'cd0165b7560115198833980a6795b701'), ('dc_publisher_stated_address', '7605c217d2d4d4fb0e36cff42015b0f1'), ('dc_site_claims_conflict', '33d7d5e99f4cae4883e843e22bfd03da'), ('map1_dc_zip_members', '9fc1c9f51375f25db5658a14ca36937c')) x(fn, want) loop
    if (select md5(p.prosrc) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
         where n.nspname = 'public' and p.proname = r.fn) is distinct from r.want then bad := bad || ' ' || r.fn; end if;
  end loop;
  if not (to_regclass('public.dc_osm_derived_point') is not null
      and to_regclass('public.dc_osm_address_check') is not null) then
    bad := bad || ' (the OSM views: expected exists)';
  end if;
  if bad <> '' then
    raise exception 'DRIFT: production does not carry the C3a objects this rollback removes:%', bad;
  end if;
end $guard$;

drop view public.dc_osm_address_check;

-- ── WORK QUEUE for the writer ────────────────────────────────────────────────────────────
-- `admitted` (appended 2026-09-24): whether ANY current observation stating this address belongs to
-- an admitted extraction. The writer drains admitted work first, so a large not-yet-admitted
-- backlog can never delay a derivation that decisions are waiting for.
-- The OpenStreetMap layer's map-eligible addresses join the SAME queue (2026-09-26): one geocoder,
-- one ladder, one cache keyed by the address, whichever layer states it.
create or replace view public.dc_geocode_queue with (security_invoker = true) as
select p.geocoder_query, public.dc_geocode_ladder_version() as ladder_version,
       bool_or(p.admitted) as admitted
  from public.dc_observation_derived_point p
 where p.input_quality = 'GEOCODABLE'
   and p.derivation_id is null
 group by p.geocoder_query;

drop view public.dc_osm_derived_point;

-- ── INPUT RULE, TWO SEPARATE QUESTIONS (2026-09-24, Atlas address validation) ──────────────
-- The rule used to be one Epoch-only branch that both READ Epoch's payload and DECIDED whether
-- the result was a site address; every other source got NO_GEOCODE_RULE. So a publisher that
-- states a street address beside its own point (Compute Atlas: 876 of 2,187 current records carry
-- a `street`) was never checked against that address, and Lancaster was caught only because Epoch
-- happened to state the same address. The two questions are now two functions:
--
--   1. PUBLISHER SCHEMA EXTRACTION -- dc_publisher_stated_address. Where does this source's payload
--      state an address, and what does it say? Source-keyed, because payload schemas genuinely
--      differ (Epoch: one `Address` string + `Country`; Atlas: `location.street/city/state/
--      postalCode`). It returns the publisher's words as ONE line and decides nothing about them.
--   2. GEOCODABILITY POLICY -- dc_geocodable_site_address. Is that line specific enough to send to
--      the production ladder? ONE generic rule for every source, knowing no source name.
--
-- dc_geocode_input composes the two and keeps its signature, so every consumer is unchanged.
-- Neither function decides geography, ZIP or identity.

-- 1. EXTRACTION. Per source; returns (extraction, address_line, reason):
--      STATED       the publisher states an address; address_line is it, verbatim modulo whitespace
--      NOT_US       the publisher places the record outside the United States
--      NO_RULE      no extraction rule for this source (nothing is ever geocoded for it)
--    Atlas composes its structured fields in the SAME shape the 2026-09-24 calibration geocoded
--    (docs/dc-geocode-probe-inputs.sql, kind 'calib': "street, city, state zip"), so the measured
--    2,000 m bound applies to exactly this input. A field the publisher left empty is omitted,
--    never guessed; a blank street yields an empty line, which the policy rejects as BLANK.
create or replace function public.dc_publisher_stated_address(p_source_key text,
                                                              p_distribution_key text,
                                                              p_payload jsonb)
returns table(extraction text, address_line text, reason text)
language plpgsql
immutable
set search_path to 'public', 'pg_temp'
as $fn$
declare
    loc jsonb;
    st  text;
begin
    if p_source_key = 'epoch_ai' and p_distribution_key = 'data_centers' then
        if coalesce(p_payload->>'Country', '') <> 'United States' then
            return query select 'NOT_US'::text, null::text, 'the publisher places this record outside the United States'::text;
            return;
        end if;
        return query select 'STATED'::text,
            btrim(regexp_replace(coalesce(p_payload->>'Address', ''), '\s+', ' ', 'g')),
            'Epoch Address field'::text;
        return;
    end if;
    if p_source_key = 'compute_atlas' and p_distribution_key = 'facilities' then
        loc := coalesce(p_payload->'location', '{}'::jsonb);
        st := btrim(regexp_replace(coalesce(loc->>'street', ''), '\s+', ' ', 'g'));
        return query select 'STATED'::text,
            case when st = '' then ''
                 else concat_ws(', ', st,
                                nullif(btrim(regexp_replace(coalesce(loc->>'city', ''), '\s+', ' ', 'g')), ''),
                                nullif(btrim(concat_ws(' ',
                                    nullif(btrim(coalesce(loc->>'state', '')), ''),
                                    nullif(btrim(coalesce(loc->>'postalCode', '')), ''))), ''))
            end,
            'Atlas location.street, city, state postalCode'::text;
        return;
    end if;
    return query select 'NO_RULE'::text, null::text, 'no address extraction rule for this source'::text;
end;
$fn$;

do $post$
declare r record; bad text := '';
begin
  for r in select * from (values ('dc_derived_address_admitted', '31cb6c9e7481311ab33042a8845c9276'), ('dc_derived_point_verdict', '4cd5b97def7d6179900cd95ec452d9a7'), ('dc_geocodable_site_address', 'a5c2ef9940d63bc55dceeede44e28f95'), ('dc_geocode_input', '655ff9b7ade2234745669dae8d146bcf'), ('dc_geocode_ladder_version', 'cd0165b7560115198833980a6795b701'), ('dc_publisher_stated_address', '83675b5b646487fe1cc70041749232f5'), ('dc_site_claims_conflict', '33d7d5e99f4cae4883e843e22bfd03da'), ('map1_dc_zip_members', '9fc1c9f51375f25db5658a14ca36937c')) x(fn, want) loop
    if (select md5(p.prosrc) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
         where n.nspname = 'public' and p.proname = r.fn) is distinct from r.want then bad := bad || ' ' || r.fn; end if;
  end loop;
  if public.dc_derived_address_admitted('openstreetmap', 'telecom_data_center')
     or not public.dc_derived_address_admitted('compute_atlas', 'facilities')
     or not public.dc_derived_address_admitted('epoch_ai', 'data_centers') then
    bad := bad || ' (admission)';
  end if;
  if to_regclass('public.dc_osm_derived_point') is not null or to_regclass('public.dc_osm_address_check') is not null then
    bad := bad || ' (OSM views still present)';
  end if;
  if md5(pg_get_viewdef('public.dc_geocode_queue'::regclass)) is distinct from '4a52710c5a8b9cdb140314746896bfc3' then
    bad := bad || ' (dc_geocode_queue is not the pre-C3a view)';
  end if;
  if bad <> '' then
    raise exception 'POST-CONDITION failed:%. Rolled back.', bad;
  end if;
end $post$;

commit;
