-- GENERATED by test/dc_osm_layer_pg/build_apply.py from the DDL of record. Do not edit.

-- C3a: the OpenStreetMap layer's address check (separate layer; OSM NOT admitted; Map 1 untouched).

-- One transaction: drift guard, the changed Step 3D and 3B objects in dependency order, post-condition.

begin;

do $guard$
declare r record; bad text := '';
begin
  for r in select * from (values ('dc_derived_address_admitted', '31cb6c9e7481311ab33042a8845c9276'), ('dc_derived_point_verdict', '4cd5b97def7d6179900cd95ec452d9a7'), ('dc_geocodable_site_address', 'a5c2ef9940d63bc55dceeede44e28f95'), ('dc_geocode_input', '655ff9b7ade2234745669dae8d146bcf'), ('dc_geocode_ladder_version', 'cd0165b7560115198833980a6795b701'), ('dc_publisher_stated_address', '83675b5b646487fe1cc70041749232f5'), ('dc_site_claims_conflict', '33d7d5e99f4cae4883e843e22bfd03da'), ('map1_dc_zip_members', '9fc1c9f51375f25db5658a14ca36937c')) x(fn, want) loop
    if (select md5(p.prosrc) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
         where n.nspname = 'public' and p.proname = r.fn) is distinct from r.want then bad := bad || ' ' || r.fn; end if;
  end loop;
  if (to_regclass('public.dc_osm_derived_point') is not null
      or to_regclass('public.dc_osm_address_check') is not null) then
    bad := bad || ' (the OSM views: expected not exists)';
  end if;
  if md5(pg_get_viewdef('public.dc_geocode_queue'::regclass)) is distinct from '4a52710c5a8b9cdb140314746896bfc3' then
    bad := bad || ' dc_geocode_queue';
  end if;
  if bad <> '' then
    raise exception 'DRIFT: production no longer matches main@800b9a3 (or C3a is already applied):%', bad;
  end if;
end $guard$;

-- ===== STEP 3D  docs/dc-step3d-derived-location.sql (changed objects) =====

-- ── INPUT RULE, TWO SEPARATE QUESTIONS (2026-09-24, Atlas address validation) ──────────────
-- The rule used to be one Epoch-only branch that both READ Epoch's payload and DECIDED whether
-- the result was a site address; every other source got NO_GEOCODE_RULE. So a publisher that
-- states a street address beside its own point (Compute Atlas: 876 of 2,187 current records carry
-- a `street`) was never checked against that address, and Lancaster was caught only because Epoch
-- happened to state the same address. The two questions are now two functions:
--
--   1. PUBLISHER SCHEMA EXTRACTION -- dc_publisher_stated_address. Where does this source's payload
--      state an address, and what does it say? Source-keyed, because payload schemas genuinely
--      differ (Epoch: one `Address` string + `Country`; Atlas: `location.street/city/state/
--      postalCode`). It returns the publisher's words as ONE line and decides nothing about them.
--   2. GEOCODABILITY POLICY -- dc_geocodable_site_address. Is that line specific enough to send to
--      the production ladder? ONE generic rule for every source, knowing no source name.
--
-- dc_geocode_input composes the two and keeps its signature, so every consumer is unchanged.
-- Neither function decides geography, ZIP or identity.

-- 1. EXTRACTION. Per source; returns (extraction, address_line, reason):
--      STATED       the publisher states an address; address_line is it, verbatim modulo whitespace
--      NOT_US       the publisher places the record outside the United States
--      NO_RULE      no extraction rule for this source (nothing is ever geocoded for it)
--    Atlas composes its structured fields in the SAME shape the 2026-09-24 calibration geocoded
--    (docs/dc-geocode-probe-inputs.sql, kind 'calib': "street, city, state zip"), so the measured
--    2,000 m bound applies to exactly this input. A field the publisher left empty is omitted,
--    never guessed; a blank street yields an empty line, which the policy rejects as BLANK.
create or replace function public.dc_publisher_stated_address(p_source_key text,
                                                              p_distribution_key text,
                                                              p_payload jsonb)
returns table(extraction text, address_line text, reason text)
language plpgsql
immutable
set search_path to 'public', 'pg_temp'
as $fn$
declare
    loc jsonb;
    st  text;
begin
    if p_source_key = 'epoch_ai' and p_distribution_key = 'data_centers' then
        if coalesce(p_payload->>'Country', '') <> 'United States' then
            return query select 'NOT_US'::text, null::text, 'the publisher places this record outside the United States'::text;
            return;
        end if;
        return query select 'STATED'::text,
            btrim(regexp_replace(coalesce(p_payload->>'Address', ''), '\s+', ' ', 'g')),
            'Epoch Address field'::text;
        return;
    end if;
    if p_source_key = 'compute_atlas' and p_distribution_key = 'facilities' then
        loc := coalesce(p_payload->'location', '{}'::jsonb);
        st := btrim(regexp_replace(coalesce(loc->>'street', ''), '\s+', ' ', 'g'));
        return query select 'STATED'::text,
            case when st = '' then ''
                 else concat_ws(', ', st,
                                nullif(btrim(regexp_replace(coalesce(loc->>'city', ''), '\s+', ' ', 'g')), ''),
                                nullif(btrim(concat_ws(' ',
                                    nullif(btrim(coalesce(loc->>'state', '')), ''),
                                    nullif(btrim(coalesce(loc->>'postalCode', '')), ''))), ''))
            end,
            'Atlas location.street, city, state postalCode'::text;
        return;
    end if;
    -- OpenStreetMap (telecom=data_center), the SEPARATE ODbL layer in national_dc_records. The
    -- payload is the record's own OSM tags (raw_tags). Composed in the same "number street, city,
    -- state zip" shape as Atlas, so the same policy and the same calibrated bound apply. A missing
    -- house number or street yields an empty line (BLANK); an OSM country tag other than US is NOT_US.
    if p_source_key = 'openstreetmap' and p_distribution_key = 'telecom_data_center' then
        if nullif(upper(btrim(coalesce(p_payload->>'addr:country', ''))), '') not in ('US', 'USA') then
            return query select 'NOT_US'::text, null::text, 'the OSM record places this facility outside the United States'::text;
            return;
        end if;
        st := btrim(regexp_replace(concat_ws(' ', nullif(btrim(coalesce(p_payload->>'addr:housenumber', '')), ''),
                                                  nullif(btrim(coalesce(p_payload->>'addr:street', '')), '')), '\s+', ' ', 'g'));
        return query select 'STATED'::text,
            case when btrim(coalesce(p_payload->>'addr:housenumber', '')) = ''
                   or btrim(coalesce(p_payload->>'addr:street', '')) = '' then ''
                 else concat_ws(', ', st,
                                nullif(btrim(regexp_replace(coalesce(p_payload->>'addr:city', ''), '\s+', ' ', 'g')), ''),
                                nullif(btrim(concat_ws(' ',
                                    nullif(btrim(coalesce(p_payload->>'addr:state', '')), ''),
                                    nullif(btrim(coalesce(p_payload->>'addr:postcode', '')), ''))), ''))
            end,
            'OSM addr:housenumber addr:street, addr:city, addr:state addr:postcode'::text;
        return;
    end if;
    return query select 'NO_RULE'::text, null::text, 'no address extraction rule for this source'::text;
end;
$fn$;

comment on function public.dc_publisher_stated_address(text, text, jsonb) is
'STEP 3D. Publisher SCHEMA extraction only: where a source states its address, as one line. Keyed by
source because payload schemas differ; decides nothing about the line (dc_geocodable_site_address does).';

-- ── OPENSTREETMAP: THE SEPARATE LAYER'S ADDRESS CHECK (2026-09-26, founder: OSM stays separate) ──
-- OpenStreetMap is an approved source kept as its OWN ODbL layer (national_dc_records): it is never
-- merged into the canonical CC BY tables (docs/dc-osm-current-state-2026-09-26.md §2). This view
-- checks each OSM pin against the OSM record's own stated address WITHOUT that merge. It owns no
-- decision of its own; every one is the shared rule every source uses:
--   extraction + policy  dc_geocode_input('openstreetmap', 'telecom_data_center', raw_tags)
--   the geocoder         dc_address_geocode, filled by the one writer from dc_geocode_queue
--   the output rule      dc_derived_point_verdict
--   the gate             dc_derived_address_admitted -- false: acquired and reported, decides nothing
-- It is a separate view, not rows in dc_observation_derived_point, because that view feeds the
-- canonical identity and geography resolvers: an OSM row there would be the merge.
-- An OSM pin is a SITE claim when the loader recorded it as the facility's own mapped point
-- (precise_location) or its own mapped outline (approximate_campus_area); anything else makes no
-- site claim and is never judged. The JUDGEMENT (the shared conflict rule) is Step 3B's view
-- dc_osm_address_check; this view is acquisition only, which is all the writer's queue reads.
create or replace view public.dc_osm_derived_point with (security_invoker = true) as
select r.source_key, r.map_eligible, r.location_precision, r.lat as osm_lat, r.lng as osm_lng,
       gi.input_quality, gi.geocoder_query, gi.reason as input_reason,
       d.derivation_id, d.provider, d.match_type, d.lat, d.lng, d.matched_address,
       d.provider_candidates, d.derived_at, d.run_ref,
       case when gi.input_quality <> 'GEOCODABLE' then 'NOT_GEOCODABLE' else v.verdict end as verdict,
       v.positional_uncertainty_m,
       case when gi.input_quality <> 'GEOCODABLE' then gi.reason else v.reason end as verdict_reason,
       case when r.location_precision in ('precise_location', 'approximate_campus_area')
            then 'PUBLISHER_SITE' end as osm_claim_class,
       r.id as osm_record_id,
       public.dc_derived_address_admitted('openstreetmap', 'telecom_data_center') as admitted
  from public.national_dc_records r
 cross join lateral public.dc_geocode_input('openstreetmap', 'telecom_data_center', r.raw_tags) gi
  left join public.dc_address_geocode d
    on d.geocoder_query = gi.geocoder_query
   and d.ladder_version = public.dc_geocode_ladder_version()
  left join lateral public.dc_derived_point_verdict(d.match_type, d.provider_candidates,
                    gi.geocoder_query, d.matched_address, d.lat, d.lng) v on true;

revoke all on public.dc_osm_derived_point from anon, authenticated;

comment on view public.dc_osm_derived_point is
'STEP 3D. The OpenStreetMap layer''s address check: each national_dc_records row, its own stated
address through the shared extraction/policy, the shared geocoder''s derivation and the shared
verdict. Acquisition only: judged by dc_osm_address_check (Step 3B). Never merged into canonical
tables; never moves an OSM pin.';

-- ── WORK QUEUE for the writer ────────────────────────────────────────────────────────────
-- `admitted` (appended 2026-09-24): whether ANY current observation stating this address belongs to
-- an admitted extraction. The writer drains admitted work first, so a large not-yet-admitted
-- backlog can never delay a derivation that decisions are waiting for.
-- The OpenStreetMap layer's map-eligible addresses join the SAME queue (2026-09-26): one geocoder,
-- one ladder, one cache keyed by the address, whichever layer states it.
create or replace view public.dc_geocode_queue with (security_invoker = true) as
select q.geocoder_query, public.dc_geocode_ladder_version() as ladder_version,
       bool_or(q.admitted) as admitted
  from (select p.geocoder_query, p.admitted
          from public.dc_observation_derived_point p
         where p.input_quality = 'GEOCODABLE'
           and p.derivation_id is null
        union all
        select o.geocoder_query, o.admitted
          from public.dc_osm_derived_point o
         where o.map_eligible
           and o.input_quality = 'GEOCODABLE'
           and o.derivation_id is null) q
 group by q.geocoder_query;

revoke all on public.dc_geocode_queue from anon, authenticated;

comment on view public.dc_geocode_queue is
'STEP 3D. Geocodable source addresses with no derivation for the current ladder version: the
only input dc-geocode-observations.yml reads.';

-- ===== STEP 3B  docs/dc-step3b-canonical-geography.sql (new object) =====

-- ── THE OPENSTREETMAP LAYER'S ADDRESS CHECK (2026-09-26) ─────────────────────────────────
-- OpenStreetMap is a SEPARATE layer (founder, 2026-09-26): its records are never merged into the
-- canonical entity or geography tables. This view judges each OSM pin against its OWN stated
-- address with the SAME rule every canonical site claim is judged by, dc_site_claims_conflict
-- above, fed by Step 3D's dc_osm_derived_point (shared extraction, policy, geocoder, verdict).
-- The pin is a PUBLISHER_SITE claim (osm_claim_class); the geocode is a DERIVED_ADDRESS claim with
-- its calibrated bound. An OSM pin is never MOVED. The only outcomes:
--   CORROBORATED      the address places the facility within the allowance of its pin
--   SOURCES_DISAGREE  farther apart than the allowance
--   UNCHECKED_*       no usable check (absence of evidence is not evidence against the pin)
-- It decides nothing on Map 1: map1_dc_zip_members does not read it.
create or replace view public.dc_osm_address_check with (security_invoker = true) as
select o.osm_record_id, o.source_key, o.map_eligible, o.location_precision, o.osm_lat, o.osm_lng,
       o.input_quality, o.geocoder_query, o.derivation_id, o.lat, o.lng, o.verdict,
       o.positional_uncertainty_m, o.verdict_reason, o.osm_claim_class,
       case when o.lat is not null and o.osm_lat is not null
            then ST_DistanceSphere(ST_MakePoint(o.osm_lng, o.osm_lat), ST_MakePoint(o.lng, o.lat)) end as distance_m,
       case when o.input_quality <> 'GEOCODABLE' then 'UNCHECKED_' || o.input_quality
            when o.verdict <> 'ACCEPTED' then 'UNCHECKED_' || o.verdict
            when o.osm_claim_class is null or o.osm_lat is null then 'UNCHECKED_NO_SITE_CLAIM'
            when public.dc_site_claims_conflict(o.osm_claim_class, null, o.osm_lat, o.osm_lng,
                                                'DERIVED_ADDRESS', o.positional_uncertainty_m, o.lat, o.lng)
              then 'SOURCES_DISAGREE'
            else 'CORROBORATED' end as check_outcome,
       o.admitted
  from public.dc_osm_derived_point o;

revoke all on public.dc_osm_address_check from anon, authenticated;

comment on view public.dc_osm_address_check is
'STEP 3B. The OpenStreetMap layer''s address check: each OSM pin judged against its own stated
address by the shared conflict rule. CORROBORATED / SOURCES_DISAGREE / UNCHECKED_*. Never moves a
pin, never merged into canonical tables, not read by the Map 1 reader.';

do $post$
declare r record; bad text := '';
begin
  for r in select * from (values ('dc_derived_address_admitted', '31cb6c9e7481311ab33042a8845c9276'), ('dc_derived_point_verdict', '4cd5b97def7d6179900cd95ec452d9a7'), ('dc_geocodable_site_address', 'a5c2ef9940d63bc55dceeede44e28f95'), ('dc_geocode_input', '655ff9b7ade2234745669dae8d146bcf'), ('dc_geocode_ladder_version', 'cd0165b7560115198833980a6795b701'), ('dc_publisher_stated_address', '7605c217d2d4d4fb0e36cff42015b0f1'), ('dc_site_claims_conflict', '33d7d5e99f4cae4883e843e22bfd03da'), ('map1_dc_zip_members', '9fc1c9f51375f25db5658a14ca36937c')) x(fn, want) loop
    if (select md5(p.prosrc) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
         where n.nspname = 'public' and p.proname = r.fn) is distinct from r.want then bad := bad || ' ' || r.fn; end if;
  end loop;
  if public.dc_derived_address_admitted('openstreetmap', 'telecom_data_center')
     or not public.dc_derived_address_admitted('compute_atlas', 'facilities')
     or not public.dc_derived_address_admitted('epoch_ai', 'data_centers') then
    bad := bad || ' (admission)';
  end if;
  if to_regclass('public.dc_osm_derived_point') is null or to_regclass('public.dc_osm_address_check') is null
     or has_table_privilege('anon', 'public.dc_osm_derived_point', 'select')
     or has_table_privilege('authenticated', 'public.dc_osm_derived_point', 'select')
     or has_table_privilege('anon', 'public.dc_osm_address_check', 'select')
     or has_table_privilege('authenticated', 'public.dc_osm_address_check', 'select') then
    bad := bad || ' (OSM views missing or public)';
  end if;
  if bad <> '' then
    raise exception 'POST-CONDITION failed:%. Rolled back.', bad;
  end if;
end $post$;

commit;
