-- GENERATED by test/dc_verdict_pg/build_verdict.py. Do not edit.

-- C7 ROLLBACK: restore the derived-point verdict production carried before C7 (proven to

-- fingerprint to it). Applied only by dc-verdict-apply.yml with confirm=ROLLBACK-VERDICT-C7.

begin;

do $guard$
declare bad text := '';
begin
  if (select md5(p.prosrc) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
        where n.nspname = 'public' and p.proname = 'dc_derived_point_verdict') is distinct from '09bbb34f73aefe2e9c6bbefedbdd829e' then bad := bad || ' dc_derived_point_verdict'; end if;
  if (select md5(p.prosrc) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
        where n.nspname = 'public' and p.proname = 'dc_derived_address_admitted') is distinct from '2c05d65aba736fab7c79199e78614ab6' then bad := bad || ' dc_derived_address_admitted'; end if;
  if (select md5(p.prosrc) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
        where n.nspname = 'public' and p.proname = 'map1_dc_zip_members') is distinct from '2146b68afc2cda03948b1e1cd51b29b8' then bad := bad || ' map1_dc_zip_members'; end if;
  if (select verdict from public.dc_derived_point_verdict('range_interpolated', 1, '300 S Test Road, Testville, IL 60073', '300 N TEST RD, TESTVILLE, IL, 60073', 40.0, -90.0)) is distinct from 'REJECTED_MATCH_DIVERGES' then bad := bad || ' (direction case)'; end if;
  if (select verdict from public.dc_derived_point_verdict('range_interpolated', 1, '31st Avenue East, Testville, WI 54880', '31 E AVE, TESTVILLE, WI, 54880', 40.0, -90.0)) is distinct from 'REJECTED_MATCH_DIVERGES' then bad := bad || ' (ordinal case)'; end if;
  if (select verdict from public.dc_derived_point_verdict('range_interpolated', 1, '300 S Test Road, Testville, IL 60073', '300 S TEST RD, TESTVILLE, IL, 60073', 40.0, -90.0)) is distinct from 'ACCEPTED' then bad := bad || ' (agreeing control)'; end if;
  if bad <> '' then
    raise exception 'DRIFT: production does not carry the C7 verdict this rollback reverses:%', bad;
  end if;
end $guard$;

-- ── QUALITY RULE: may this derived point stand for a SITE? (fail closed) ──────────────────
-- ACCEPTED only when ALL hold; anything else is a named rejection:
--   * a point-grade match type: rooftop, parcel_centroid or range_interpolated
--     (zip_centroid / county_centroid are AREA answers; failed / unknown are nothing);
--   * exactly ONE provider candidate (two matches = the provider could not choose);
--   * the matched house number is the queried house number, and the matched state is the
--     queried state when the query names one (the provider answered the address we asked).
-- The positional uncertainty returned with an ACCEPTED point is the calibrated bound (header).
-- Unmeasured tiers (rooftop, parcel_centroid) get the SAME bound: they are at least as precise
-- by definition, and no Epoch record reaches them today, so no tighter number is invented.
create or replace function public.dc_derived_point_verdict(
    p_match_type text, p_provider_candidates integer, p_query text, p_matched text,
    p_lat double precision, p_lng double precision)
returns table(verdict text, positional_uncertainty_m double precision, reason text)
language plpgsql
immutable
set search_path to 'public', 'pg_temp'
as $fn$
declare
    q_no text := substring(coalesce(p_query, '') from '^(\d+)');
    m_no text := substring(coalesce(p_matched, '') from '^(\d+)');
    q_st text := substring(coalesce(p_query, '') from ',\s*([A-Z]{2})(?:\s+\d{5}(?:-\d{4})?)?\s*(?:,|$)');
    m_st text := substring(coalesce(p_matched, '') from ',\s*([A-Z]{2}),\s*\d{5}\s*$');
begin
    if p_match_type is null then
        return query select 'NOT_YET_GEOCODED'::text, null::double precision, 'no derivation for this address yet'::text;
    elsif p_match_type = 'failed' then
        return query select 'REJECTED_NO_MATCH'::text, null::double precision, 'the ladder matched nothing; no fallback point'::text;
    elsif p_match_type in ('zip_centroid', 'county_centroid') then
        return query select 'REJECTED_AREA_CENTROID'::text, null::double precision, 'an area centroid is not a site'::text;
    elsif p_match_type not in ('rooftop', 'parcel_centroid', 'range_interpolated') then
        return query select 'REJECTED_UNKNOWN_MATCH_TYPE'::text, null::double precision, 'unknown precision is not a site'::text;
    elsif p_lat is null or p_lng is null then
        return query select 'REJECTED_NO_MATCH'::text, null::double precision, 'no coordinates returned'::text;
    elsif p_provider_candidates is distinct from 1 then
        return query select 'REJECTED_AMBIGUOUS'::text, null::double precision,
            'the provider returned ' || coalesce(p_provider_candidates::text, 'an unknown number of') || ' candidates';
    elsif q_no is null or m_no is null or q_no <> m_no then
        return query select 'REJECTED_MATCH_DIVERGES'::text, null::double precision,
            'matched house number ' || coalesce(m_no, 'none') || ' is not the queried ' || coalesce(q_no, 'none');
    elsif q_st is not null and m_st is not null and q_st <> m_st then
        return query select 'REJECTED_MATCH_DIVERGES'::text, null::double precision,
            'matched state ' || m_st || ' is not the queried ' || q_st;
    else
        return query select 'ACCEPTED'::text, 2000::double precision,
            p_match_type || ', one candidate, house number agrees; uncertainty = calibrated max error (2,000 m)';
    end if;
end;
$fn$;

comment on function public.dc_derived_point_verdict(text, integer, text, text, double precision, double precision) is
'STEP 3D. Output-quality rule for a derived point. Area centroids, failures, unknown types,
ambiguous or divergent matches never become a site. ACCEPTED carries the calibrated 2,000 m
positional uncertainty that Map 1 membership must respect.';

do $post$
declare bad text := '';
begin
  if (select md5(p.prosrc) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
        where n.nspname = 'public' and p.proname = 'dc_derived_point_verdict') is distinct from '4cd5b97def7d6179900cd95ec452d9a7' then bad := bad || ' dc_derived_point_verdict'; end if;
  if (select md5(p.prosrc) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
        where n.nspname = 'public' and p.proname = 'dc_derived_address_admitted') is distinct from '2c05d65aba736fab7c79199e78614ab6' then bad := bad || ' dc_derived_address_admitted'; end if;
  if (select md5(p.prosrc) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
        where n.nspname = 'public' and p.proname = 'map1_dc_zip_members') is distinct from '2146b68afc2cda03948b1e1cd51b29b8' then bad := bad || ' map1_dc_zip_members'; end if;
  if (select verdict from public.dc_derived_point_verdict('range_interpolated', 1, '300 S Test Road, Testville, IL 60073', '300 N TEST RD, TESTVILLE, IL, 60073', 40.0, -90.0)) is distinct from 'ACCEPTED' then bad := bad || ' (direction case)'; end if;
  if (select verdict from public.dc_derived_point_verdict('range_interpolated', 1, '31st Avenue East, Testville, WI 54880', '31 E AVE, TESTVILLE, WI, 54880', 40.0, -90.0)) is distinct from 'ACCEPTED' then bad := bad || ' (ordinal case)'; end if;
  if (select verdict from public.dc_derived_point_verdict('range_interpolated', 1, '300 S Test Road, Testville, IL 60073', '300 S TEST RD, TESTVILLE, IL, 60073', 40.0, -90.0)) is distinct from 'ACCEPTED' then bad := bad || ' (agreeing control)'; end if;
  if bad <> '' then
    raise exception 'POST-CONDITION failed:%. Rolled back.', bad;
  end if;
end $post$;

commit;
