-- ============================================================================
-- MULTI-SOURCE EVIDENCE — PHASE 1 (SQL OF RECORD)
-- Applied 2026-08-10 to project qwnnmljucajnexpxdgxr as four migrations:
--   evidence_phase1_core_foundation
--   evidence_phase1_rls_and_vocabulary
--   evidence_phase1_read_model  (+ _enum_labels)
--   evidence_phase1_del_valle_pilot_ingest / _tdlr_projects_and_bridge
--   evidence_phase1_fix_cross_source_org_merge
--
-- ADDITIVE ONLY. Everything lives in the `evidence` schema except ONE function,
-- public.ev_parcel_report(). No existing table, view, function or read path was
-- altered. No production page reads any of this.
-- ============================================================================

create schema if not exists evidence;

-- ── enums ────────────────────────────────────────────────────────────────────
-- entity_kind      parcel | development | facility | organization | instrument
-- uniqueness_scope global | state | county | authority_dataset
-- currency_basis   point_in_time | as_of_certified_roll | continuously_updated | unknown
-- evidence_class   recorded_instrument | authoritative_filing | authoritative_roll
--                  | identifier_backed | source_reported | resolved_by_match | derived
-- authority_class  authoritative | official_secondary | republished | third_party | unknown
-- fact_kind        source | normalized | resolved | derived
-- claim_status     active | superseded_by_source | retracted_by_source | rejected_by_homesignal
-- check_status     success | success_empty | source_error | unavailable | partial | not_checked
--                  ^ §26: a failed fetch is a recorded state, never an absent fact.

-- ── SOURCE LAYER ─────────────────────────────────────────────────────────────
-- ev_source, ev_source_coverage, ev_source_capability
-- ev_source_authority(source_id, predicate, authority_class)
--     Authority is per (source, predicate). This is what lets TDLR be authoritative
--     about its own filing while never outranking TCAD about who owns the land —
--     without deleting either claim.
-- ev_source_role_map(source_id, source_vocab_field, source_vocab_value, predicate)
--     THE ROLE-COLLAPSE FIX AS DATA. 'OWNER block' -> project_owner_as_filed;
--     'ownerName' -> property_owner_of_record. Adding a source adds rows here,
--     never new predicates.

-- ── RAW PRESERVATION (§6) ────────────────────────────────────────────────────
-- ev_source_record(source_record_id, source_id, source_record_key, url, http_status,
--                  retrieved_at, parser_version, payload_hash, payload jsonb,
--                  payload_storage, as_of, superseded_by)
--     Every claim FKs to exactly one source_record. A source correction is a NEW
--     record + superseded_by; claims flip status. Nothing is deleted.
-- ev_source_check(...)  every attempt, including the ones that found nothing.

-- ── IDENTITY (§4) ────────────────────────────────────────────────────────────
-- ev_entity(entity_id uuid pk, kind, jurisdiction_state, jurisdiction_county)
--     Surrogate key. A source identifier is NEVER the primary key.
-- ev_identifier_type(id_type pk, identifies_kind, issuing_authority,
--                    uniqueness_scope, scope_state, scope_county, normalizer)
--     'tcad.prop_id' is county-scoped to TX/Travis and identifies a PARCEL.
--     'epa.frs_registry_id' is global and identifies a FACILITY.
-- ev_entity_identifier(entity_id, entity_kind, id_type, id_value,
--                      id_value_normalized, source_record_id, is_primary, status)
--     UNIQUE (id_type, id_value_normalized) WHERE status='active'
--     Scope lives in the TYPE, so PROP_ID 292354 in another county is a different
--     id_type and cannot collide. There is no global "APN".
--     TRIGGER ev_identifier_kind_guard: an id_type whose identifies_kind does not
--     match the entity's kind raises — a cross-kind false join is impossible.
-- ev_entity_resolution(entity_a, entity_b, kind, basis, evidence_url, decided_by)
--     Rows are NEVER merged. 'not_same_entity' is a first-class outcome.

-- ── TYPED CORES (thin) ───────────────────────────────────────────────────────
-- ev_parcel, ev_organization, ev_development, ev_facility, ev_recorded_instrument
--     Deliberately hold almost nothing. Even an organization's NAME is a claim.

-- ── EVIDENCE (§7) ────────────────────────────────────────────────────────────
-- ev_predicate(key pk, domain, consumer_label, definition, explicit_non_meaning,
--              object_kind, version)
--     Carries the EXPLICIT NON-MEANING. project_owner_as_filed is documented as
--     "NOT evidence of land ownership" in the database itself.
-- ev_claim(claim_id, source_record_id NOT NULL, subject_entity_id, subject_kind,
--          predicate, object_entity_id | object_value, object_unit,
--          source_predicate_raw NOT NULL, source_object_raw,
--          valid_from, valid_to, currency_basis, as_of, observed_at,
--          evidence_class, authority_class, fact_kind, status, status_reason)
--     CHECK ev_claim_one_object: exactly one of object_entity_id / object_value.
--     source_predicate_raw is NOT NULL — you may not write a claim without
--     recording what the source actually called the relationship.
-- ev_claim_relation(claim_a, claim_b, kind)  corroborates | contradicts | supersedes
-- ev_claim_geometry(claim_id pk, geom geometry(MultiPolygon,4326))
-- ev_display_precedence(predicate, authority_class, evidence_class, rank)
--     §22 — precedence is DATA. Storage never arbitrates; display does, at read time.
-- ev_legacy_property_report_link(report_address, parcel_entity_id, basis, evidence_class)
--     §18 — the non-destructive bridge. property_reports stays address-keyed and
--     unmodified; address is NOT the parcel entity's key.

-- ── SCALAR FACTS: DESIGN CHOICE (§7) ─────────────────────────────────────────
-- Acreage / legal description / values are stored as CLAIMS WITH LITERAL OBJECTS
-- (object_value + object_unit), not as entity columns and not as a separate
-- observation table. Three reasons:
--   1. every scalar carries the same provenance as every relationship — one path;
--   2. value history is temporal for free (one claim per year via as_of), so no
--      number is ever overwritten;
--   3. a second source contributing the same fact needs no schema change, and the
--      two claims coexist rather than one clobbering the other. Proven live: TCAD
--      publishes BOTH legalAcreage 36.4740 and landInfo.sizeAcres 28.4940 — two
--      different measurements, both retained, distinguished by source_predicate_raw.

-- ── SECURITY (§29) ───────────────────────────────────────────────────────────
-- The `evidence` schema is NOT in Supabase's exposed-schema list, so PostgREST
-- cannot reach it with the anon key at all. RLS is additionally ENABLED on all 22
-- tables with NO policies (deny by default), and USAGE on the schema is revoked
-- from anon/authenticated. Raw payloads — which contain owner mailing addresses —
-- are therefore unreachable from any browser client.
-- The only read path is public.ev_parcel_report(id_type, id_value), SECURITY
-- DEFINER, EXECUTE revoked from anon/authenticated, which selects owner NAME only
-- and never mailing data (§27).

-- ── CONSUMER READ MODEL (§23) ────────────────────────────────────────────────
-- public.ev_parcel_report(_id_type text, _id_value text) returns jsonb
--   Takes a SOURCE identifier, never a UUID, an address or a company name.
--   Returns: jurisdiction, identifiers[], property{}, ownership[], value_history[],
--            development[], deed_references[], sources_checked[].
--   Emits NO internal UUID and NO enum token — evidence.ev_label() maps each enum
--   to plain English once, so no frontend ever learns the vocabulary.

-- ============================================================================
-- PHASE 2 ADDITIONS (2026-08-10) — Travis County Clerk registration +
-- ownership resolution. Migration: evidence_phase2_clerk_source_and_ownership_resolution
--
-- ⛔ THE CLERK ADAPTER WAS NOT BUILT. Both official access paths prohibit
-- automated retrieval, with receipts:
--   * www.tccsearch.org/robots.txt  →  "User-agent: ClaudeBot / Disallow: /"
--                                      "Content-Signal: search=yes,ai-train=no,use=reference"
--     and the site returns HTTP 403 behind a Cloudflare challenge.
--   * travis.tx.publicsearch.us/robots.txt → "Allow: /$" + "Disallow: /"
--     no public API (every /api/* path 404s), results gated behind sign-in /
--     Kofile "timed access".
-- Nothing was scraped. Zero Clerk claims exist.
-- ============================================================================

-- ── new predicates: a deed party is NOT an owner ─────────────────────────────
-- grantee_on_recorded_instrument — "NOT automatically the current owner. A later
--   instrument may have conveyed the property onward."
-- grantor_on_recorded_instrument — "NOT 'former owner'. Being a grantor on one
--   instrument does not establish that the party ever held, or has since lost, title."
-- has_instrument_type, has_recording_date

-- ── ev_source 'travis_county_clerk' ──────────────────────────────────────────
--   access_mode = 'not_machine_accessible', status = 'blocked_by_source_terms'
--   AUTHORITATIVE for recorded instruments (outranks the appraisal roll for owner
--   of record); explicitly NOT authoritative for values, acreage or classification.
--   Authority + role map + precedence are declared NOW so a licensed feed slots in
--   with no schema change. Declaring authority is not the same as holding evidence.

-- ── ev_source_check: 4 rows, status 'unavailable' ────────────────────────────
--   One per TCAD-reported instrument (2008006779TR, 2010122587TR, 2012114190TR,
--   2021024697), each recording WHAT was attempted and WHY it failed.
--   'unavailable' is explicitly NOT "the instrument does not exist".

-- ── public.ev_current_owner(id_type, id_value) ───────────────────────────────
-- MINIMUM ownership-resolution policy (§18), documented rather than hardcoded:
--   1. Candidates are ownership-BEARING claims only: property_owner_of_record and
--      grantee_on_recorded_instrument.
--   2. Winner = latest `as_of`; ties broken by ev_display_precedence rank.
--      RECENCY FIRST — so an older recorded deed does NOT override a newer assessor
--      roll. "Clerk always wins" is deliberately not implemented.
--   3. state = 'disagreement' when another claim shares the winner's period AND
--      rank but names a different party. Both survive; neither is deleted.
--      state = 'corroborated_by_independent_county_records' only when more than one
--      SOURCE names the same party in the same period.
--      state = 'single_source' otherwise — a historical deed chain is NOT a conflict.
--   4. `supporting` always returns EVERY candidate claim. Resolution never deletes.
-- No score of any kind is produced (§19).

-- ============================================================================
-- PHASE 3 ADDITIONS (2026-08-10) — Denver, CO jurisdiction-independence proof.
-- Migrations: evidence_phase3_denver_sources_and_adapter,
--             evidence_phase3_adapter_helpers,
--             evidence_phase3_generalize_read_model
--
-- NO new core table. NO new predicate. Denver reused all 21 Phase 1/2 predicates.
-- ============================================================================

-- ── new identifier types (jurisdiction-scoped, §7) ──────────────────────────
-- denver.schednum      parcel      | Denver Assessor      | scope county CO/Denver
-- denver.reception_num instrument  | Denver Clerk+Recorder| scope county CO/Denver
-- The same digit string under tcad.prop_id is a DIFFERENT parcel: uniqueness lives in
-- the id_type, so a Denver SCHEDNUM can never collide with a Travis PROP_ID.

-- ── new sources ─────────────────────────────────────────────────────────────
-- denver_assessor_parcels        City and County of Denver Assessor, ArcGIS, first-party,
--                                authoritative for owner/situs/legal/area/class/value/geometry.
-- denver_odc_sales_transfers     Denver's real property sales and transfers index. Carries the
--                                Clerk and Recorder RECEPTION NUMBER, recording date, document
--                                type, and grantor/grantee AS RECORDED.
--                                Classified authority_class='official_secondary', NOT
--                                'authoritative': the publisher is the Assessor, not the Clerk
--                                and Recorder, which remains the system of record. It is also a
--                                SUBSET (87,862 rows) of all recordings, not a complete index.

-- ── authority stays PREDICATE-SPECIFIC ──────────────────────────────────────
-- The transfers index is official_secondary for grantee/grantor/instrument-type/recording-date
-- and for conveyed_by_instrument. It is deliberately given NO authority over
-- property_owner_of_record: a grantee is not an owner.
-- ev_display_precedence ranks: clerk recorded_instrument 10 < assessment roll 20 <
-- county-published recording index 30.

-- ── parcel <-> instrument linkage: DIRECT ───────────────────────────────────
-- The transfers rows publish PARID alongside RECEPTION_NUM, so the link is
-- evidence_class='identifier_backed' with source_predicate_raw='PARID' — the strongest class,
-- not an address match. Join rule: SCHEDNUM = lpad(PARID::text, 13, '0'), VALIDATED by control
-- (transfers PARID 225333015000 resolved to exactly one parcel SCHEDNUM '0225333015000').

-- ── idempotent adapter ──────────────────────────────────────────────────────
-- evidence.ev_ingest_denver_parcel(parcel_json, instr_json, parcel_url, instr_url)
--   Find-or-create on every entity, keyed on the AUTHORITATIVE identifier; source records
--   de-duplicated on (source_id, source_record_key, payload_hash); claims guarded by existence
--   checks. Proven: three consecutive runs left 26 entities / 135 claims / 11 source records /
--   15 identifiers / 2 geometries unchanged.
-- evidence.ev_find_or_create_org(name, source_id, source_record, field)
--   Organizations are SOURCE-SCOPED. Two sources naming the same string get two entities;
--   sameness is only ever an evidenced ev_entity_resolution row, never an implicit join.
--   This is why 'DENVER HEALTH AND HOSPITAL AUTHORITY' (2026 grantor) and
--   'DENVER HEALTH AND HOSPITALAUTHORITY' (2017 grantee) are NOT merged.

-- ── read-model fix (NOT a core-schema change) ───────────────────────────────
-- Phase 1's deed section hardcoded id_type='travis.instrument_no' — county-specific parsing,
-- which surfaced as instrument_number:null on the first Denver read. Replaced with
-- evidence.ev_instrument_number(), which resolves via identifier_type.identifies_kind =
-- 'instrument'. Added public.ev_recorded_instruments() returning number, document type,
-- recording date, grantor[], grantee[], and the parcel-link basis + evidence class.
-- public.ev_current_owner() now also walks parcel -> conveyed_by_instrument -> instrument ->
-- grantee, so an assessment roll and a recording index can corroborate ACROSS entity kinds.
-- Both functions are SECURITY DEFINER with EXECUTE revoked from anon/authenticated.
-- Owner MAILING address (OWNER_ADDRESS_LINE1/CITY/STATE/ZIP) is present in the raw Denver
-- payload and is deliberately never promoted to a claim and never returned by any read.

-- ============================================================================
-- PHASE 4 ADDITIONS (2026-08-10) — consumer property card, feature-flagged pilot.
-- Migration: evidence_phase4_pilot_flag_and_card_rpc
-- ============================================================================
-- evidence.ev_pilot_parcel(id_type, id_value, enabled)  — the allowlist is DATA, keyed on
--   the AUTHORITATIVE identifier, never an address. Two rows: tcad.prop_id 292354 and
--   denver.schednum 0015300060000. RLS on, revoked from anon.
-- public.ev_property_card(id_type, id_value) — the ONE RPC the browser calls. Returns
--   {pilot_enabled:false} for anything not on the allowlist, so the flag cannot be
--   bypassed client-side. EXECUTE granted to anon; ev_parcel_report / ev_current_owner /
--   ev_recorded_instruments remain revoked from anon.
-- evidence.ev_area_rank(basis) — §11 acreage arbitration, DECLARED not guessed:
--   'legalAcreage' and 'LAND_AREA' rank 1 (the parcel's own area);
--   'landInfo.sizeAcres' ranks 5 (an appraisal land-segment size, NOT the parcel).
--   The loser is retained and shown as "Other reported measurement", never substituted.
-- evidence.ev_doc_type_label(source, code) — SW/WD/QC/PS expanded using Denver's OWN
--   published convention (its ASAL_INSTR field reads e.g. "SW: SPECIAL WARRANTY").
-- Consumer status vocabulary is mapped in the RPC, so no internal enum ever reaches the
-- browser: corroborated / reported / disagree / unknown.

-- ============================================================================
-- PHASE 5 ADDITIONS (2026-08-10) — community.html discovery. Migration:
-- evidence_phase5_batch_availability. No new renderer, no new card RPC, no new flag.
-- ============================================================================
-- public.ev_evidence_available(zip) — ONE batched call per community page.
--   Returns [{id_type, id_value, label, evidence_available, evidence_domains,
--             linked_case_numbers}]. Deliberately GENERIC: it never returns
--   is_tcad_pilot / is_denver_pilot, and the frontend never learns WHY evidence exists.
--   Gated by the SAME evidence.ev_pilot_parcel allowlist — a non-pilot ZIP gets [] and
--   the page issues no further request and renders no heading.
--   linked_case_numbers lets a feed card be matched to a parcel by FILING NUMBER, never
--   by address or company name.
-- DISCOVERY ZIP IS DERIVED, NOT EVIDENCE: nearest modeled ZIP centroid to the parcel's
--   own authoritative geometry. It decides only where a teaser may appear, never enters a
--   claim, and is never shown as a fact. Measured: Del Valle -> 78617 (exact);
--   Denver 18581 E 50th Ave -> 80239, because its true ZIP 80249 is NOT modeled
--   (0 rows in development_reports) — an honest nearest-neighbour fallback, ~4 mi.
-- The full card still comes from public.ev_property_card() and loads only on user intent.

-- ============================================================================
-- PHASE 6 ADDITIONS (2026-08-10) — authoritative ZIP placement. Migrations:
-- evidence_phase6_authoritative_zip_assignment, evidence_phase6_evidence_only_zip_routing
-- ============================================================================
-- AUDIT: HomeSignal has NO ZIP/ZCTA polygon table. The only geometry tables are
--   evidence.ev_claim_geometry (2 parcel polygons) and public.resolved_project_parcels
--   (0 rows). So parcel-polygon vs ZIP-polygon containment could not be answered locally.
--   Containment is therefore answered by the boundary authority itself — the US Census
--   geocoder geographies endpoint — computed ONCE per parcel and stored, never per page
--   and never per feed card.
-- ⚠️ ZCTA IS NOT A USPS ZIP. A ZIP Code Tabulation Area is the Census Bureau's areal
--   approximation of a USPS delivery ZIP. Correct for "which community geography contains
--   this parcel"; it is never labelled "USPS verified".
--
-- PREDICATES (§9 — the two ZIPs stay separate facts, so they can corroborate):
--   located_in_zip    spatial containment, authoritative, fact_kind='resolved'
--   has_reported_zip  the ZIP the property source itself printed in its situs string
--
-- METHOD: ST_PointOnSurface of the parcel's OWN authoritative polygon (deterministic, and
--   guaranteed to lie inside the polygon) resolved against the boundary authority.
--   Boundary vintage stored on every claim (Census2020_Current). Recomputable.
-- CROSS-BOUNDARY RULE (§7): the ZCTA containing the representative point wins. It is
--   deterministic and never depends on row order. Area-overlap weighting is not possible
--   without a local ZIP polygon table and is NOT silently approximated.
-- FALLBACK HIERARCHY (§24), validated against the real pilot data:
--   1. located_in_zip   (both pilots have it)
--   2. has_reported_zip (Travis only — Denver's SITUS_ZIP is null, so none was invented)
--   3. otherwise unresolved. No nearest-neighbour tier at any level.
--
-- nearest-modeled-centroid is GONE as a placement rule. A parcel with no assignment is
--   simply not discoverable, rather than shown in a neighbouring ZIP as if that were fact.
--
-- MEASURED: Denver 0015300060000 -> ZCTA 80249 (was 80239). Travis 292354 -> ZCTA 78617
--   (unchanged control). ev_evidence_available('80239') now returns 0.
--
-- EVIDENCE-ONLY ZIP (§11): 80249 became routable as PURE DATA — one communities row, like
--   every other ZIP page. NO development_reports row is fabricated and no
--   app_community_meta is invented.
-- public.ev_zip_is_routable(zip) — GENERIC routability. No ZIP is named in code.
--   Returns routable + has_evidence + development_coverage ∈ {modeled, not_yet_available}.
--   §13: an unmodeled ZIP has UNKNOWN development coverage and must never render as a
--   verified negative ("no development found").

-- ============================================================================
-- PHASE 7 part 1 (2026-08-10) — facility/company VOCABULARY + DECLARATIVE ROLE MAPS.
-- Migration: evidence_phase7_facility_predicates_and_role_maps
-- SEMANTICS ONLY: 0 facility entities, 0 new claims. Data migration NOT performed.
-- ============================================================================
-- New predicates (each with an explicit does_not_mean):
--   facility_owner            NOT the property owner of record / deed owner / parcel owner
--   operates_facility         NOT the parcel owner, project owner as filed, or parent
--   former_operator           NOT current; a missing end date does NOT make a role current
--   regulated_customer_of     a regulator's responsible CUSTOMER, not automatically operator
--   parent_company            VERIFIED corporate parentage only
--   parent_company_candidate  never display, never track-record or ESG inheritance
--   facility_located_on_parcel  proximity is NOT location
-- New identifier types: tceq.rn (facility, TX), tceq.cn (organization, TX), sec.cik (org).
--   The kind guard therefore rejects a TCEQ RN on an organization and a CN on a facility.
--
-- ev_source_role_map gained `excluded boolean` + a CHECK that a row is either mapped or
-- explicitly excluded. An exclusion is a RECORDED DECISION, not a missing row.
-- Measured mapping over all 6 live FRS affiliation types (0 unhandled):
--   OPERATOR        -> operates_facility
--   OWNER           -> facility_owner            (never property_owner_of_record)
--   OWNER/OPERATOR  -> facility_owner            (+ operates_facility from ONE source record)
--   PARENT OWNER    -> parent_company_candidate  (never parent_company)
--   BILLING CONTACT -> EXCLUDED                  (not a role; contact data must not surface)
--   MAILING ADDRESS -> EXCLUDED                  (not a role; address data must not surface)
-- Verified: 0 non-SEC sources may map to parent_company.
--
-- Predicate-specific authority (no universal trust score):
--   tceq_central_registry  regulated_customer_of authoritative · operates_facility official_secondary
--   epa_frs_affiliations   facility_owner / operates_facility official_secondary;
--                          parent_company_candidate third_party
--   sec_exhibit21          parent_company authoritative
-- Precedence for operates_facility: TCEQ identifier-backed 10/20 < FRS name-based 40 —
-- so an identifier-backed state relationship outranks a name-based federal affiliation
-- for the same predicate, and neither deletes the other.

-- ============================================================================
-- PHASE 7 part 2 (2026-08-11) — the Del Valle FACILITY / OPERATOR / PARENT migration.
-- Migrations: evidence_phase7_migration_foundation,
--   evidence_phase7_ingest_frs_affiliations, evidence_phase7_ingest_tceq_del_valle,
--   evidence_phase7_zip_facilities_parent_and_conflicts,
--   evidence_phase7_facility_read_model, evidence_phase7_map_former_operator
-- Scope: ZIP 78617 / Del Valle only. No existing consumer read path changed.
-- ============================================================================
-- ORDER OF OPERATIONS (§: raw row -> source record -> identifiers/entities -> claims):
--   every claim below cites an ev_source_record that was written first, and every entity
--   was created from an AGENCY-ASSIGNED IDENTIFIER — never from a facility name, a street
--   address, a company name, or coordinates.
--
-- THE MIGRATION HARD-CODES NO SOURCE SEMANTICS. Each row is joined to
-- evidence.ev_source_role_map; a value with no map row raises outcome 'unmapped_role'
-- rather than being dropped. ev_source_role_map_uniq now includes the predicate, so ONE
-- source value can license MORE THAN ONE predicate — which is how FRS OWNER/OPERATOR emits
-- both facility_owner and operates_facility while citing ONE source record.
--
-- MEASURED — all 41 frs_org_affiliations rows accounted for, none silently dropped:
--   claim_created              38   (facility_owner 17 · operates_facility 21)
--   excluded_by_role_map        6   (1 BILLING CONTACT + 5 MAILING ADDRESS)
--   withheld_not_organization   2   (ONE row, JUDY TORRES ROMAN, x its 2 mapped predicates)
--   candidate_only              3   (PARENT OWNER -> parent_company_candidate)
--   row accounting: 31 role rows + 6 excluded + 1 withheld + 3 parent = 41
--
-- ORGANISATION GATE — FAIL CLOSED. evidence.ev_is_organization_name() requires POSITIVE
--   evidence of an organisation (a legal form, a governmental form, or a business-activity
--   word, from the evidence.ev_org_name_token table). Absence of a personal-name pattern is
--   NOT treated as evidence of a company. JUDY TORRES ROMAN therefore produced no entity and
--   no claim. Verified: 'NATIONAL ENERGY PRODUCTION', 'PERWEZ MOHEET, ACTING DIRECTOR' and
--   'JUDY TORRES ROMAN' appear in ZERO claims; positive controls 'CITY OF AUSTIN',
--   'TIC - THE INDUSTRIAL COMPANY' and 'CEMEX INC.' do appear.
-- EXCLUDED ROWS CARRY NO PAYLOAD. A BILLING CONTACT / MAILING ADDRESS row gets an
--   ev_source_record with payload NULL and a note saying why, so the exclusion is provable
--   without copying contact or mailing data into the evidence schema at all.
--
-- FACILITY IDENTITY:
--   epa.frs_registry_id  30 facilities (12 carrying affiliation rows + 18 more rendered on
--                        the 78617 page; CEMEX 110034344494 has affiliations but no page row)
--   tceq.rn              10 identifiers -> 4 TCEQ-only facilities + 6 attached to FRS facilities
--   34 facility entities total.
-- FRS -> TCEQ RECONCILIATION IS IDENTIFIER-BACKED OR IT DOES NOT HAPPEN. A tceq.rn is
--   attached to an FRS facility only when that registry id declares EXACTLY ONE TX-TCEQ ACR
--   program id. Two registry ids declare three RNs each (110008975804, 110039703611) and were
--   recorded as 'skipped_ambiguous' — picking one would have been a guess.
-- NAME/ADDRESS LINKS ARE CANDIDATES, NEVER MERGES. The legacy project_facility_refs rows
--   whose basis is "exact facility name AND exact address" became 3
--   ev_entity_resolution kind='same_facility_candidate' rows with status='candidate'. The
--   entities stay separate. The 4th (RN101723195) has no TCEQ source record in the pilot and
--   is recorded as outcome 'resolution_candidate' so "no match" is distinguishable from
--   "never looked at".
--
-- TCEQ — 14 claims, ALL regulated_customer_of, 0 operates_facility.
--   The legacy property_company_roles rows label these "Operator". TCEQ states an affiliated
--   CUSTOMER, so the role map's predicate governs and the legacy label does not. Where the
--   row carries both a CN and an RN the claim is identifier_backed; where it carries neither
--   (a name match inside a ZIP-scoped query) the claim is kept but classed resolved_by_match,
--   so precedence can never rank it above an identifier-backed statement.
--   FRS absence never weakened TCEQ: the 3 Del Valle TCEQ facilities have no FRS counterpart
--   and are full first-class facilities on their tceq.rn alone.
--
-- PARENT — exactly ONE parent_company claim in the whole graph:
--   Martin Marietta Materials Southwest, LLC -> Martin Marietta Materials, Inc.
--   (SEC EX-21.01, accession 0001193125-26-059193, as of 2025-12-31; parent carries sec.cik
--   0000916076). The 7 non-verified company_parents rows are outcome 'candidate_only' and
--   produced no claim. Republic Services was NOT created as a parent. The FRS PARENT OWNER
--   rows produced 3 parent_company_candidate claims, which the card renders under
--   "possible_parents" as "Reported, not verified".
--   THE ONE PERMITTED CROSS-SOURCE ORGANISATION BINDING: an SEC Exhibit 21 entry is bound to
--   an organisation already in the graph by evidence.ev_legal_name_key — case- and
--   punctuation-insensitive, but NOTHING is stripped, so corporate suffixes are load-bearing
--   ("River Bottoms Ranch" and "River Bottoms Ranch LLC" can never bind). Every binding is
--   written down as ev_entity_resolution kind='sec_parent_of_named_subsidiary'. 1 binding made.
--
-- COMPETING CLAIMS BOTH SURVIVE. All 4 legacy identity_conflicts rows became
--   ev_claim_relation kind='competing_role_claim' pairs. Neither claim is deleted or
--   suppressed in storage; ev_display_precedence decides what is shown.
--
-- THE CHAIN STOPS HONESTLY. facility_located_on_parcel claims: 0. The Del Valle FRS
--   facilities carry no parcel identifier, and proximity is not location, so parcel ->
--   development -> facility is UNRESOLVED and is left that way. Measured: 5 occurs_on_parcel
--   claims on TCAD 292354 (2200 Caldwell), 0 of the TDLR developments carries an FRS
--   reference, ATX1 (TABS2026011928) project owner as filed = Neuralink Corporation with no
--   parent. The chain that DOES complete is facility -> regulated party -> verified parent:
--   RN106540172 -> Martin Marietta Materials Southwest, LLC -> Martin Marietta Materials, Inc.
--
-- HISTORICAL ROLES: no FORMER OPERATOR row exists in the live data, so FORMER OPERATOR is
--   mapped and exercised by a SYNTHETIC fixture that is ROLLED BACK. Proven: the card renders
--   role "Former operator", since 1990-01-01, until 1999-12-31, current=false. Post-rollback
--   control: frs_org_affiliations back to 41 rows, 0 claims naming the fixture company.
--
-- READ MODEL: public.ev_facility_card(id_type, id_value) — SECURITY DEFINER, granted to anon.
--   Returns consumer labels only: no enum names, no tier ranks, no source/claim UUIDs, no
--   pilot flags, and no contact or mailing data (which never became claims). Roles are
--   de-duplicated to the strongest claim per (role, party) while both claims remain stored.
--
-- IDEMPOTENCE — every ingest re-run in a fresh statement, before/after identical:
--   entities 84 · claims 250 · identifiers 59 · source records 109 · outcomes 74 ·
--   resolutions 4 · claim relations 4 · legacy app-project links 29 · 0 new facilities.
--
-- DOWNSTREAM PROOFS (identifier-backed, no name search):
--   Track record — facility RN106540172 -> its regulated-party CNs -> company_track_events:
--     CN600125157 (TXI Operations, LP) 26 events 2010-10-08..2026-03-27;
--     CN606114726 (Martin Marietta Materials Southwest, LLC) 23 events 2014-09-02..2026-06-24.
--     Control: 61 events exist in total and NONE is keyed to a Del Valle RN — the track record
--     is a COMPANY record, reachable only through the organisation, never the facility.
--   ESG eligibility — the evidence graph is a strict SUPERSET of v_esg_eligible_company for
--     78617: all 22 legacy companies are reachable (0 lost), plus 3 the legacy view drops —
--     'tic the industrial company' and 't morales company l l c' (the conflict losers, which
--     the legacy view suppresses and the evidence layer keeps as competing claims) and
--     'cemex inc' (real FRS affiliation, no rendered page row).

-- ============================================================================
-- PHASE 8 (2026-08-11) — REGULATORY / ENFORCEMENT TRACK RECORD, WITH ATTRIBUTION.
-- Migrations: evidence_phase8_regulatory_event_kind,
--   evidence_phase8_regulatory_vocabulary, evidence_phase8_ingest_regulatory_events,
--   evidence_phase8_source_availability, evidence_phase8_facility_location_facts,
--   evidence_phase8_track_record_read_model,
--   evidence_phase8_attribution_class_follows_weakest_link,
--   evidence_phase8_track_record_basis_wording,
--   evidence_phase8_org_subject_sees_own_record,
--   evidence_phase8_bind_customer_numbers_idempotent,
--   evidence_phase8_read_model_vocabulary_leak, evidence_phase8_identifier_entity_index
-- Scope: ZIP 78617 / Del Valle only. No existing consumer read path changed.
--
-- THE GOVERNING RULE:
--   FACILITY RECORD != DIRECT-COMPANY RECORD != PARENT-COMPANY RECORD.
-- It is enforced by VOCABULARY, not by discipline: each level is a DIFFERENT PREDICATE
-- (event_occurred_at_facility · direct_company_regulatory_event ·
--  verified_parent_regulatory_event · unresolved_regulatory_event), so a query for one
-- level cannot return another, and a future consumer cannot collapse them by accident.
--
-- BASELINE RE-MEASURED BEFORE ANY WRITE (Phase 7's reported figures, all confirmed live):
--   entities 84 · claims 250 · identifiers 59 · source records 109 · outcomes 74 ·
--   resolutions 4 · claim relations 4 · legacy app-project links 29 · frs_org_affiliations 41 ·
--   company_parents 8 (1 verified) · Republic Services as a parent 0 ·
--   facility_located_on_parcel 0. Nothing had drifted.
--
-- ── SOURCE INVENTORY (measured, not assumed) ────────────────────────────────────────
-- public.company_track_events   61 rows — THE ONLY enforcement-event corpus HomeSignal holds.
--   3 TCEQ datasets: Notices of Violation (mwzi-gyw7, keyed rn_number), Notices of
--   Enforcement (rua3-iswk, keyed rn), enforcement orders (u66a-qggj, keyed case_no).
--   61 rows -> 53 DISTINCT AGENCY EVENTS: 8 events appear twice because the same agency
--   record was stored once as a direct-company row and once as a parent-company row.
--   status: 0 of 61 non-null. penalty: 2 of 61. agencies: TCEQ only. RNs: 33 distinct.
-- public.company_facilities     754 rows = 89 + 154 + 511, exactly the three company CNs.
--   EVERY event RN is present here for its own company_key (0 missing) — which is what makes
--   the company link agency-derived rather than a name search.
-- public.track_record_checks    17 rows — the availability record (§26).
-- public.echo_violation_counts  3 rows, 0 with count>0, and NONE of the 3 registry ids is a
--   Del Valle facility. HomeSignal therefore holds ZERO EPA enforcement events for any pilot
--   facility. (n_live_tup reported 0 for this table; the real count is 3. An estimate is not
--   a count — the CLAUDE.md rule, and it mattered here.)
-- public.tceq_affiliations_raw  9,617 rows but for WILLIAMSON-COUNTY ZIPs; 78617 is absent.
--   Out of pilot scope. POSITIVE CONTROL on that query: CN600125157 returns 16 rows and
--   CN606114726 returns 7, so the zero for CN600134696 is a real absence, not a broken filter.
-- public.tceq_resolved_operators 53 rows — also Williamson ZIPs. Not Del Valle.
-- public.app_environmental_risk  0 rows, and flood/wildfire/heat is not regulatory data.
-- No OSHA data. No TRI enforcement data. Nothing was created for a source that has no rows.
--
-- ── THE MIGRATION (61 rows, fully accounted for) ────────────────────────────────────
--   claim_created  direct_company_regulatory_event   49
--   claim_created  verified_parent_regulatory_event  12
--   accounting: 49 + 12 = 61. 0 unmapped_role, 0 silently dropped.
--   facility_not_stated 2 (the two enforcement orders — see below)
-- Evidence classes: 48 identifier_backed (TXI 26, MMM Southwest 22) ·
--   13 resolved_by_match (MMM Inc's 12, plus MMM Southwest's one order).
-- Entities 84 -> 170 (+53 regulatory_event, +33 facility). Identifiers 59 -> 146.
-- Source records 109 -> 257 (53 agency event records + 61 attribution + 1 CN binding +
--   33 facility-location). Claims 250 -> 731. Claim relations 4 -> 6. Source checks 23.
--
-- THE CLASS FOLLOWS THE WEAKEST LINK — the correction that mattered most. The chain is
--   agency: event -> RN | agency: CN -> RN | HomeSignal: CN -> which organisation.
-- Attribution was first written identifier_backed whenever the agency tied the CN to the
-- event's RN. That reads the chain one link short: for Martin Marietta Materials, Inc. the
-- last link is a LEGAL-NAME lookup, so all 12 parent claims are resolved_by_match. Without
-- this, a name resolution silently acquires the authority of an agency identifier.
--
-- THE PARENT'S CUSTOMER NUMBER IS NAME-RESOLVED, AND SAYS SO. CN600134696 has no
-- first-party row anywhere in this database. It is bound to Martin Marietta Materials, Inc.
-- by evidence.ev_legal_name_key (Phase 7's exact key — case- and punctuation-insensitive,
-- strips NOTHING, so suffixes stay load-bearing), cited to a source registered as NOT
-- first-party, and stored is_primary=false. The same rule REFUSED to bind Cinco J., Inc.:
-- two organisations share that legal name, so it was recorded 'attribution_unresolved'
-- rather than guessed. The gate fired on real data without being aimed at anything.
--
-- ORDERS ARE ATTRIBUTED BY CASE NUMBER, NEVER BY RESPONDENT NAME ALONE, AND CARRY NO
-- INVENTED LOCATION. The 2 enforcement orders name no facility. No facility was inferred
-- from the sibling notice, so neither carries event_occurred_at_facility and both are
-- recorded 'facility_not_stated'; the read model prints "The source record names no facility".
--
-- §18 CROSS-SOURCE DUPLICATES ARE RELATED, NEVER MERGED. The case number is deliberately
-- NOT an identifier type: making it one would force UNIQUE(id_type,id_value) to merge a
-- Notice of Enforcement with the Order that resolves it. It is a LITERAL claim, and 2
-- ev_claim_relation kind='same_enforcement_case' rows tie the pairs
-- (2019-0475-WR-E, 2020-1571-EAQ-E). Both events remain distinct entities — verified.
-- Nothing was ever deduplicated on company name, date, penalty or facility name.
--
-- §21 ONE EVENT IS COUNTED ONCE, AND THE OTHER PATHS ARE DISCLOSED. De-duplication happens
-- twice: at STORAGE (two legacy rows for one agency record collapse to one source record and
-- one event entity) and at READ (an event reachable by several paths is placed in the
-- STRONGEST section, and carries "also_reachable_as" so nothing is hidden). This is why
-- Garfield's parent section shows 4 and not 12: 8 of the parent's 12 events are the same
-- agency records already listed under the direct company.
--
-- ── GARFIELD (RN106540172) — THE THREE LEVELS, NEVER BLENDED ────────────────────────
--   THIS FACILITY                    0
--   DIRECT COMPANY — OTHER FACILITIES 49  (TXI Operations, LP 26 · MMM Southwest 23)
--   VERIFIED PARENT                   4  (Martin Marietta Materials, Inc.; 8 more of its 12
--                                        are already shown as direct-company events)
--   UNRESOLVED                        0
-- The facility zero is a MEASURED absence, not silence: both TCEQ datasets were queried by
-- RN106540172 and returned 0, recorded as checked_no_records with the query basis and URL.
-- Every one of the 49 says happened_at_this_facility=false and names its own facility, e.g.
-- "Another facility — HUNTER FACILITY, NEW BRAUNFELS, TX". The word "violation at this
-- property" is not constructible from this output.
-- Penalties are reported PER LEVEL and never summed across levels:
--   direct_company $6,750 over 49 events 2010-10-08..2026-06-24 (1 event carries a penalty)
--   verified_parent  $875 over  4 events 2011-01-27..2022-05-06 (1 event carries a penalty)
--
-- ── BFI (FRS 110005052085) — REPUBLIC SERVICES IS **NOT** INHERITED ─────────────────
--   0 / 0 / 0. direct-company eligibility FALSE: the FRS operator "BFI WASTE SYSTEMS OF
--   TEXAS LP" and owner "BROWNING-FERRIS INDUSTRIES INC" are NAME-ONLY organisations with no
--   customer number, so no company track record is attributable at all. Parent eligibility
--   FALSE. No Republic Services entity exists in the graph and none was created.
--   MUTATION-PROVEN, not merely observed: inserting a parent_company_candidate from the BFI
--   operator to a synthetic "Republic Services, Inc." left the parent count at 0 and
--   parent_eligible false. Rolled back; 0 claims and 0 Republic-named organisations remain.
--
-- ── CEMEX (FRS 110034344494 / RN104315775) — ISOLATED BY IDENTIFIER ─────────────────
--   0 / 0 / 0, and all three expected sources report not_checked. "CEMEX INC." is a
--   name-only FRS organisation with no CN, so nothing attaches. No event from any other
--   CEMEX-named entity, and none from the facility sharing its address, reached it.
--
-- ── §15 THE FOUR ABSENCE STATES ARE DISTINCT, IN ONE SUBJECT ────────────────────────
--   Ward & Burke's RN111954798: TCEQ NOV = checked_no_records (asked, nothing found),
--   TCEQ NOE = not_checked (never asked). Same facility, same page, two different states.
--   CEMEX = not_checked on all three. Garfield = checked_no_records on both.
--   ECHO is 'incomplete' by construction wherever it was run: its result counts FACILITIES
--   matched, not violations, so a hit of 1 can never be rendered as "no violations".
--   unresolved_identity is a third, separate state (BFI/CEMEX: eligibility false with reason).
--
-- ── §23/§24 THE PROPERTY GRAPH STOPS HONESTLY ──────────────────────────────────────
--   facility_located_on_parcel is still 0. Parcel 292354 and development TABS2026011928
--   (ATX1) each return 0 / 0 / 0 with an explicit graph_stop: "no facility is proven to be
--   located on this parcel ... A nearby or same-address facility was NOT attached. Proximity
--   is not location." Neuralink Corporation keeps its 2 project_owner_as_filed claims, has 0
--   operator/owner/customer claims, and 0 regulatory events. Track record does not cross the
--   missing edge, and the missing edge was not manufactured to let it.
--   The same-address pair proves the isolation is structural: FRS 110070182593 and
--   RN106540172 share an exact name AND address (3901 NORWOOD LN STE 1) and remain two
--   entities with a 'candidate' resolution between them.
--
-- ── TEMPORAL (§16) ─────────────────────────────────────────────────────────────────
--   These TCEQ datasets publish NO status field (0 of 61 rows) and no closure date. No
--   status claim was written, so nothing downstream can read a status we never had. The read
--   model states neither "currently violating" nor "resolved", and says so in the payload.
--
-- ── IDEMPOTENCE (§27) — run 1 vs run 2, every object identical ──────────────────────
--   source records 257/257 · regulatory_event entities 53/53 · claims 731/731 ·
--   claim relations 6/6 · facility-event links 51/51 · company-event links 61/61 ·
--   identifiers 146/146 · entities 170/170 · outcomes 138/138 · Garfield still 0/49/4.
--   Run 2 FAILED THE FIRST TIME — ev_bind_legacy_customer_numbers recorded its
--   "could not bind" outcome with an unguarded INSERT and hit ev_migration_outcome_uniq,
--   aborting the whole re-ingest. Found only because the migration was actually run twice.
--
-- ── SECURITY (§28) ─────────────────────────────────────────────────────────────────
--   evidence RLS 27/27 tables, 0 policies (deny by default) · anon and authenticated have
--   NO USAGE on the schema · public.ev_track_record is REVOKED from public/anon/authenticated
--   (Phase 8 is not wired to any UI) · Phase 7's ev_facility_card grant is untouched.
--   The RPC emits no raw payload, no attribution_note, no UUID and no schema vocabulary —
--   the field name "weaker_than_identifier_backed" was caught spelling an internal token in
--   the payload and renamed to "weaker_than_agency_identifiers".
--
-- ── PERFORMANCE (§29) ──────────────────────────────────────────────────────────────
--   One call returns every section; there is no per-event query. Garfield (the heaviest,
--   53 events) 213 ms / 5,305 shared hits / 70,599 bytes; BFI 22 ms / 3,035 bytes; parcel
--   292354 2,910 bytes. Added index ev_entity_identifier(entity_id,id_type) WHERE active.
--   Known cost: the read model resolves each event's scalar facts with correlated subqueries
--   over a CTE, which is fine at 731 claims and will not scale — Phase 9 should replace it
--   with a single grouped join before this is wired to a page.
--
-- ── BACKWARD COMPATIBILITY (§30) — before/after md5, unchanged ─────────────────────
--   property_company_roles 66  b3923c901be5923d7f47d0d0f5dc89c3
--   project_facility_refs  33  ade204ec6037025a291bec43dbf55b0b
--   identity_conflicts      4  25269d6f4b3dd885d50cdc64350206a7
--   company_parents         8  e951809e3dd5e640ba810b1d04cf2eac
--   company_track_events   61  9d501d166d52a5c9198a7be2e4c07c82
--   company_facilities 754 · track_record_checks 17 · app_projects 3,027,773 ·
--   development_reports 12,722 — all unchanged. Phase 8 wrote to no legacy table.
--
-- ── MUTATION TESTS (applied, measured, rolled back) ────────────────────────────────
--   M1 BFI given a parent_company_candidate -> Republic Services: parent count stays 0,
--      parent_eligible stays false.
--   M2 the ONE verified parent_company demoted to a candidate: Garfield 0/49/4 -> 0/49/0.
--      The parent section is gated by verification and by nothing else.
--   M3 MMM Southwest's tceq.cn withdrawn: Garfield direct 49 -> 26 (TXI only), companies
--      listed 2 -> 1. Attribution runs through the identifier, not the company name.
--   Post-rollback control: 1 parent_company, 3 candidates, 0 MUTATION claims, 0
--   Republic-named organisations, 4 active tceq.cn, 170 entities, 731 claims, Garfield 0/49/4.
--
-- ── WHAT PHASE 8 DID NOT DO ────────────────────────────────────────────────────────
--   No score of any kind. No ESG. No WikiRate. No UI change. No new parent researched. No
--   fuzzy matching. No nationwide migration. No change to the FRS recovery lane, MassDOT or
--   DeSoto. No EPA enforcement events exist to migrate, so none were invented.

-- ============================================================================
-- PHASE 9A (2026-08-11) — SEC ENFORCEMENT + PUBLICLY DISCLOSED INVESTIGATIONS.
-- Migrations: evidence_phase9a_regulatory_matter_kind, _sec_vocabulary,
--   _sec_probe_record, _sec_availability_and_identity,
--   _track_record_setbased_and_sec, _parent_history_and_respondent,
--   _matter_spans_event_classes, _sec_sections_respect_attribution_level,
--   _sec_ingest_function
-- The Phase 8 attribution model is EXTENDED, NOT REDESIGNED: SEC records reuse the same four
-- levels and the same predicates. SEC matters are ENTITY-level, so event_occurred_at_facility
-- is absent on every one of them — a facility link would require authoritative evidence tying
-- the conduct to that facility, and association with a property is not that evidence.
--
-- BASELINE BEFORE 9A: entities 170 · claims 731 · identifiers 146 · source records 257 ·
--   source checks 23 · claim relations 6 · outcomes 138 · predicates 43 · Garfield 0/49/4 ·
--   exactly ONE entity carrying a CIK (Martin Marietta Materials, Inc., 0000916076).
--
-- ── EGRESS ─────────────────────────────────────────────────────────────────────────────
-- The sandbox cannot reach sec.gov (proxy CONNECT 403). Acquisition ran through pg_net from
-- Postgres, the workaround already established for this repo. It works: data.sec.gov returned
-- HTTP 200 / 159,542 bytes for CIK 0000916076.
--
-- ── WHAT WAS ACQUIRED, AND WHAT COULD NOT BE ──────────────────────────────────────────
-- 12 probes are recorded in evidence.ev_sec_probe with URL, HTTP status, hit count and verdict.
--   ACQUIRED  data.sec.gov submissions — registrant identity confirmed by CIK:
--             MARTIN MARIETTA MATERIALS INC, ticker MLM. Stored as an identity claim, NOT as a
--             regulatory event: being a registrant is a status and must never enter an
--             enforcement count.
--   ACQUIRED  EDGAR full-text search, the company's own filings, for investigation language.
--   REJECTED  SEC litigation releases and administrative proceedings CANNOT be searched by
--             entity. The list pages IGNORE the search parameter — proven, not assumed: the
--             request returned the default unfiltered first page, 100 release links, ZERO
--             mentions of the company. SEC ENFORCEMENT IS THEREFORE RECORDED not_checked FOR
--             EVERY ENTITY. It is not zero, and the read model never says it is.
--   REJECTED  search.sec.gov returned no response at all (recorded, not silently dropped).
--   REJECTED  litigation-releases RSS: HTTP 404.
--
-- ── THE INVESTIGATION FINDING, AND WHY A COUNT WAS NOT ENOUGH ──────────────────────────
-- "SEC investigation" restricted to 10-K/10-Q/8-K returned ONE hit. Reading it disproved it:
-- accession 0000950157-18-001227, exhibit EX-10.1, is an employment agreement whose
-- whistleblower clause says the employee may cooperate "in an SEC investigation or proceeding
-- without notifying the Company". That is boilerplate about employee rights, not a disclosure
-- that this company is under investigation. Recorded as lead_only_not_evidence; NOTHING was
-- ingested from it. Wells Notice 0 · "subpoena from the SEC" 0 · "formal order of
-- investigation" 0 · "cease-and-desist" 0 · "enforcement action" 0.
-- POSITIVE CONTROLS RAN ON THE SAME INDEX AND RETURNED 30 AND 82, so those zeros are real
-- absences rather than a broken query. An earlier round of the identical queries returned
-- HTTP 500 INCLUDING the control; those were recorded unavailable and re-run, never as zeros.
-- ONE OPEN LEAD, DELIBERATELY NOT CHARACTERISED: "civil penalty" returns 62 hits in primary
-- filings. They were not read document by document, so they are evidence of nothing and were
-- not ingested. Recorded as a lead.
--
-- ── RESULT FOR THE PILOT ───────────────────────────────────────────────────────────────
-- SEC matters 0 · procedural events 0 · enforcement 0 · disclosed investigations 0 ·
-- Wells Notices 0 · monetary relief 0 in every one of the four separate buckets ·
-- entities matched by CIK 1 · matched by weaker means 0 · unresolved 0.
-- The pilot's one SEC registrant has no publicly disclosed SEC investigation that the sources
-- checked can identify, and its SEC ENFORCEMENT STATUS IS UNKNOWN because no first-party
-- entity-scoped enforcement search exists. Both are stated as such.
--
-- ── VOCABULARY (semantics as data, each value carrying its own does_not_mean) ──────────
-- evidence.ev_event_type_vocab 11 types · evidence.ev_status_vocab 10 statuses ·
-- 8 new predicates (51 total) · 5 SEC identifier types · 6 SEC sources.
-- The types are NOT collapsed into a generic "SEC violation": enforcement action, administrative
-- proceeding, final order, federal court judgment, trading suspension, disclosed investigation,
-- subpoena, inquiry, WELLS NOTICE, investigation concluded, registrant identity.
--   sec_investigation_disclosed  does_not_mean: NOT a violation, NOT a charge, NOT an
--     enforcement action, NOT a finding of wrongdoing. Many investigations close with no action.
--   sec_wells_notice             does_not_mean: NOT an SEC violation, NOT a finding, NOT a
--     charge, NOT a final enforcement action. It is a STAFF INTENTION TO RECOMMEND.
--   sec_investigation_concluded  does_not_mean: NOT an exoneration — the SEC states expressly
--     that closing an investigation must not be construed as a finding that no violation occurred.
--
-- ── MONEY IS NEVER BLENDED ─────────────────────────────────────────────────────────────
-- civil_money_penalty · disgorgement · prejudgment_interest · other_monetary_relief are four
-- separate predicates and four separate output buckets. Nothing adds them together, and no
-- amount is called a "fine".
--
-- ── MATTERS VS DOCUMENTS (§9) ──────────────────────────────────────────────────────────
-- A regulatory_matter is a first-class entity identified by the agency's own file or civil
-- action number; procedural records attach with event_part_of_matter. A matter's procedural
-- history SPANS CLASSES — the investigation and Wells Notice that precede an enforcement
-- matter are procedural events OF THAT MATTER — while the investigation-class records stay
-- listed in their own section, because §5 forbids destroying a Wells Notice by folding it into
-- the later enforcement event.
--
-- ── CONTROLS, PROVEN ON A SYNTHETIC FIXTURE THAT IS ROLLED BACK ────────────────────────
-- No pilot entity has an SEC enforcement matter, so the enforcement paths were exercised with a
-- fixture (the Phase 7 rolled-back-fixture precedent) rather than by inventing stored evidence.
-- One matter, five procedural records, a verified parent with its OWN separate matter, and a
-- similarly-named decoy company. Measured:
--   A/G  subsidiary view: matters 1 (NOT 5) · procedural events 5 ·
--        breakdown 3 enforcement + 2 investigation · civil penalty 2,500,000 ·
--        disgorgement 1,000,000 · prejudgment interest 150,000 — three separate figures.
--   B/C  investigations section 2 (disclosure + Wells Notice), never counted as enforcement.
--   §7   respondent_named_by_agency = "Testco Subsidiary LLC" rides on the matter.
--   D    viewing the PARENT: own matters 1 / penalty 750,000 / parent-block 0 — the
--        SUBSIDIARY's matter never became the parent's record.
--   E    the similarly-named company: 0 matters, 0 investigations.
--   F    the real pilot entity is the no-public-record control (see the sentence below).
--
-- ── DEFECT FOUND BY THE FIXTURE, NOT BY INSPECTION ─────────────────────────────────────
-- The first fixture run reported the subsidiary as "2 SEC matters, civil penalties $3,250,000".
-- It had silently added the VERIFIED PARENT's own $750,000 matter into the subsidiary's totals —
-- exactly the blending §7 forbids, and exactly the sentence §7 names as the wrong answer. Cause:
-- the SEC sections aggregated every SEC event in scope regardless of attribution level, while
-- the environmental sections had always been split by level. Fixed: SEC matters now carry a
-- level rank, an entity's own matters and its parent's matters are separate blocks, and the
-- parent block carries its own caveat and is excluded from the headline totals.
--
-- ── MUTATION TESTS (applied, measured, rolled back) ────────────────────────────────────
--   M1 verified parent edge demoted to a candidate -> inherited parent block 1 -> 0.
--   M2 event_part_of_matter links retracted -> matters 1 -> 3, i.e. the matter relationship is
--      the only thing preventing one matter from reading as several. (3, not 5: the two
--      investigation-class records are not enforcement matters and remain in their own section.)
--   M3 the respondent's CIK withdrawn -> the subject no longer resolves at all; no attribution.
--   Post-rollback control: 0 fixture identifiers, 0 fixture source records, 0 regulatory_matter
--   entities, 1 parent_company claim, Garfield 0/49/4.
--
-- ── §11 THE SENTENCE, GENERATED ONLY FROM WHAT THE EVIDENCE SUPPORTS ───────────────────
-- For the pilot registrant the read model emits exactly:
--   "No publicly disclosed SEC investigation was identified in the sources checked. This is not
--    a finding that no investigation exists — SEC investigations are frequently nonpublic."
-- It does NOT emit "No SEC investigations", and there is no code path that can.
--
-- ── §12 DATA COMPLETENESS, PER QUESTION ────────────────────────────────────────────────
--   SEC public investigation disclosures  no_public_disclosure_identified
--   SEC enforcement (litigation releases) not_checked
--   SEC enforcement (admin proceedings)   not_checked
--   TCEQ enforcement                      checked_no_records / checked_with_records per facility
--   EPA enforcement                       not_checked
-- The absence WORDING is carried as data on the expectation row, so an SEC absence cannot
-- render with the environmental phrasing by accident.
--
-- ── §16 PERFORMANCE: MEASURED BEFORE AND AFTER, AND IT IMPROVED ────────────────────────
-- The Phase 8 read model resolved each event's scalar facts with correlated subqueries over a
-- CTE. Replaced with grouped set-based maps (factmap / idmap / notemap) built once per call.
--   Garfield (53 events): 205.4 ms / 5,289 shared hits  ->  36.8 ms / 3,111 shared hits
--   BFI:                   21.9 ms / 2,356              ->  27.3 ms / 2,529
-- 5.6x faster on the heavy path WHILE ADDING the SEC sections. BFI is ~5 ms slower because the
-- payload now also answers the SEC availability questions; that is new work, not a regression
-- in the old work, and it is reported rather than hidden.
--
-- ── IDEMPOTENCE (§15) — ingest run twice, every object identical ───────────────────────
--   entities 170/170 · claims 732/732 · identifiers 146/146 · source records 258/258 ·
--   source checks 33/33 · claim relations 6/6 · outcomes 138/138 · Garfield 0/49/4.
--
-- ── SECURITY (§15) ─────────────────────────────────────────────────────────────────────
--   evidence RLS 30/30 tables, 0 policies · anon/authenticated have NO USAGE ·
--   public.ev_track_record REVOKED from public/anon/authenticated · Phase 7's ev_facility_card
--   grant untouched · the payload carries no raw source payload, no UUID and no schema enum.
--
-- ── BACKWARD COMPATIBILITY — before/after md5 identical to the Phase 8 baseline ────────
--   property_company_roles b3923c901be5923d7f47d0d0f5dc89c3 · project_facility_refs
--   ade204ec6037025a291bec43dbf55b0b · identity_conflicts 25269d6f4b3dd885d50cdc64350206a7 ·
--   company_parents e951809e3dd5e640ba810b1d04cf2eac · company_track_events
--   9d501d166d52a5c9198a7be2e4c07c82. Garfield's TCEQ answer is still 0/49/4. No legacy table
--   was modified. SEC events are partitioned out of the environmental sections BY AGENCY, so an
--   environmental section can never absorb a securities matter or vice versa.
--
-- ── EVIDENCE GAPS, STATED PLAINLY ──────────────────────────────────────────────────────
--   1. SEC enforcement is UNCHECKED for every entity — no first-party entity-scoped search
--      exists. Closing it needs a crawl of the SEC's release corpus, which Phase 9A did not do
--      because a partial crawl would produce an unreliable zero, which is worse than not_checked.
--   2. EDGAR full-text search starts in 2001; it cannot speak to earlier disclosure.
--   3. The 62 "civil penalty" hits are an unexamined lead.
--   4. Only ONE pilot entity carries a CIK, so real SEC coverage is one company deep.
--   5. Nothing was scored, weighted, or combined with TCEQ. That is deliberate.

-- ============================================================================
-- PHASE 9B (2026-08-11) — SEC IDENTITY COVERAGE + A COMPLETENESS-PROVEN ENFORCEMENT CORPUS.
-- Migrations: evidence_phase9b_sec_corpus_tables, _corpus_parser_fix,
--   _collect_failure_branch_fix2, _fire_timeout, _parser_release_ref_from_url,
--   _gap_resolution, _gap_title_parse_fix, _identity_and_availability, _enforcement_checks
-- Solves the two blockers Phase 9A left: SEC enforcement was not_checked for every entity, and
-- only one organisation carried a CIK. The Phase 9A architecture is unchanged.
--
-- ── A. THE ANSWER TO "NO ENTITY-SCOPED SEARCH" IS NOT TO SEARCH PER ENTITY ─────────────
-- Phase 9A proved SEC publishes no entity-scoped enforcement search. Phase 9B acquires the
-- WHOLE INDEX once, materializes it, and answers entity questions locally. The Property Card
-- never issues a live SEC request.
-- The index is enumerable and self-describing: 100 rows/page, each row carrying a publish date,
-- an SEC-labelled respondents string (the site's own class is release-view__respondents), the
-- release number, and links to the underlying complaints and judgments.
--
-- ── B. COVERAGE, WITH RECEIPTS (evidence.v_sec_corpus_coverage) ────────────────────────
--   index                litigation_releases
--   coverage             2017-04-13 .. 2026-08-10   (LR-23803 .. LR-26606)
--   pages acquired       28        pages failed 0
--   releases held        2,795
--   confirmed never published  9   (fetched individually, HTTP 404)
--   recovered by gap fill      4
--   unresolved numbers         0
--   COMPLETENESS IDENTITY  2,795 held + 9 never-published = 2,804 = the exact span. is_complete.
--
-- ── THREE DEFECTS THE ACQUISITION FOUND IN ITSELF ─────────────────────────────────────
-- 1. SILENT ROW DROP. The parser took the release number from the row's "Release No." subfield
--    and DISCARDED any row lacking one — ~2.5 rows per page, 64 real matters across 25 pages,
--    including LR-26606, which is NEWER than the maximum the corpus claimed to hold. Those rows
--    are ordinary enforcement matters. Fixed by taking the number from the DETAIL URL, which
--    every row carries and which is the agency's own canonical path.
-- 2. PAGINATION IS NOT COMPLETENESS. A date-ordered paginated list can drop rows between
--    fetches. Proven, not theorised: LR-25605 (SEC v. Cooper J. Morgen, 2023-01-04) is live at
--    its own URL and pagination never returned it. Four such releases were recovered.
--    Completeness is therefore established per RELEASE NUMBER, never per page: each missing
--    number is fetched individually, 200 recovers it and 404 proves it was never published.
-- 3. THE FAILURE BRANCH HAD NEVER RUN. The collector's non-200 path carried an ambiguous column
--    reference and only executed the first time a page actually failed — after ten successful
--    pages. That branch is load-bearing, because it is what makes a failed fetch degrade
--    coverage instead of quietly leaving a page uncounted. (9 pages died in DNS at pg_net's
--    5 s default; the timeout is now 20 s and batches are small.)
--
-- ── C. IDENTITY COVERAGE ──────────────────────────────────────────────────────────────
-- 37 organisation name-rows evaluated (36 distinct entities):
--   already bound by identifier        2 rows  -> Martin Marietta Materials, Inc. CIK 0000916076
--   corporate-family (verified parent) 1 row   -> Martin Marietta Materials Southwest, LLC,
--                                                 recorded as FAMILY, never as its own SEC identity
--   no SEC registrant identified      34 rows
--   ambiguous (multiple registrants)   0 rows
-- Matching is EXACT legal-name key against the SEC's own registrant index
-- (company_tickers.json, 10,387 registrants). Fuzzy similarity is never used. Most of the
-- remainder are municipal bodies, private LLCs and a private company — genuinely not registrants.
-- REJECTED SOURCE, with its defect recorded: browse-edgar's atom company search returns CIKs but
-- its company NAMES come back as unrendered Perl references — entry title="ARRAY(0x557db278f648)",
-- company-info name="ARRAY(0x...)". That is a defect in the SEC feed itself. Without names,
-- exact-name binding is impossible and binding on the search string would be fuzzy matching.
--
-- ── D. THE ENFORCEMENT RESULT ─────────────────────────────────────────────────────────
-- Every HomeSignal organisation was scanned against the complete corpus with a generous token
-- match. ZERO matched. The positive control on the same scan returned 21. The only near-miss is
-- LR-24050 "Commonwealth Advisors, Inc. and Walter A. Morales" surfacing for the token "morales"
-- — a different party entirely, and the similar-name negative control appearing unprompted in
-- real data rather than in a fixture.
-- SEC enforcement for CIK 0000916076 is therefore now checked_no_records — earned, not asserted:
-- absent from a corpus in which every release number in the window is either held locally or
-- proven never published. The recorded note states its own limits: nothing outside the window,
-- nothing nonpublic, and administrative proceedings remain a SEPARATE unchecked question.
--
-- ── E. THE 62 "CIVIL PENALTY" HITS — ALL RESOLVED, NONE AN SEC MATTER ─────────────────
-- 59 are EX-95 exhibits: Mine Safety Disclosures under Dodd-Frank section 1503, reporting MSHA
-- citations and the civil penalties MSHA proposes under the Federal Mine Safety and Health Act.
-- The remaining 3 (two 2011 10-Qs and one EX-99.01) were FETCHED AND READ; all three carry the
-- same Mine Act sentence: "Whenever MSHA issues a citation or order, it also generally proposes
-- a civil penalty". Zero of the 62 concern the SEC. Nothing was ingested from them.
-- SIDE FINDING: this registrant files quarterly structured MSHA mine-safety data. That is a real
-- regulatory feed for a quarry operator and a Phase 9C candidate — it is not an SEC record.
--
-- ── F. MUTATIONS (applied, measured, rolled back) ─────────────────────────────────────
--   BASE corpus complete=true, 2,795 releases, SEC availability = checked_no_records
--   M1 drop one acquired page      -> is_complete FALSE, releases 2,795 -> 2,695
--   M2 rescan while incomplete     -> availability degrades to INCOMPLETE, never to a zero
--   M3 withdraw the CIK            -> 0 active SEC identifiers, track record stops resolving
--   M4 demote the verified parent  -> corporate-family mappings 1 -> 0
--   Post-rollback: complete=true, 2,795 releases, 37 identity rows, 1 corporate-family,
--   1 active CIK, 1 parent_company claim, 0 MUTATION markers, Garfield still 0/49/4.
--
-- ── G. IDEMPOTENCE / PERFORMANCE / COMPATIBILITY ──────────────────────────────────────
-- Every routine re-run: releases 2,795 · pages 28 · gaps 13 · identity map 37 · source checks 36
-- · entities 170 · claims 732 · identifiers 146 · source records 258 — all identical.
-- Serving is local: the SEC-registrant track record answers in 32.6 ms / 2,778 buffers with no
-- outbound request. Acquisition (28 index pages + 13 gap probes + identity + scan) ran in
-- batches through pg_net; the Property Card request path performs none of it.
-- Legacy md5s unchanged (company_track_events 9d501d16…, property_company_roles b3923c90…),
-- Garfield still 0/49/4, and no Phase 8 or Phase 9A result moved.
--
-- ── REMAINING GAPS ────────────────────────────────────────────────────────────────────
--   1. Administrative proceedings are NOT yet acquired — still not_checked, deliberately.
--   2. Coverage starts 2017-04-13; earlier matters are outside the window and say so.
--   3. Respondent extraction is the index's own respondents string; per-document role parsing
--      (defendant vs officer vs adviser) is not built, because no pilot entity matched.
--   4. 34 organisations have no SEC identity — mostly municipal or private, correctly so.

-- ============================================================================
-- PHASE 9C (2026-08-11) — SEC ADMINISTRATIVE PROCEEDINGS CORPUS.
-- Migrations: evidence_phase9c_ap_corpus, _ap_fire_window, _ap_driver,
--   _ap_month_pagination2, _crosscorpus_and_availability
-- Phase 9A/9B architecture unchanged. Phase 9B's litigation-release corpus untouched.
--
-- ── 1. THE COMPLETENESS INSTRUMENT HAD TO CHANGE, AND IT GOT STRONGER ─────────────────
-- 9B proved completeness by contiguity of one LR-NNNNN sequence plus per-number gap fill.
-- NEITHER transfers to administrative proceedings:
--   * a row carries per-ACT release numbers (34-106046, IA-6988 — often several on one row)
--     which interleave with thousands of NON-enforcement releases, so no usable contiguity;
--   * the File Number (3-22112) identifies the PROCEEDING, not the document, and one file
--     number legitimately spans many documents (one here spans 14);
--   * there is no per-file-number endpoint — /litigation/apdocuments/ap-3-22112.htm and
--     /administrative-proceedings/3-22112 both 404, and ?fileNumber= is IGNORED exactly as
--     ?search= was in 9B (it returns the default unfiltered page).
-- What the index does support is ?year=YYYY&month=M, and a month returns its ENTIRE set in ONE
-- request. A self-bounding query has no pagination boundary to lose rows across — which is
-- precisely the failure that cost 9B four live releases. Completeness is therefore proven PER
-- MONTH: every month fetched 200, and every month proven un-truncated by returning fewer rows
-- than the page limit. A month AT the limit is never assumed complete.
--
-- ── 2. COVERAGE, WITH RECEIPTS (evidence.v_sec_ap_coverage) ───────────────────────────
--   coverage            2017-04-03 .. 2026-08-11   (pinned to 9B's window so the two corpora
--                       answer for the SAME period; a combined SEC statement over mismatched
--                       windows would be a lie of composition)
--   months expected     113      months complete 113      months incomplete 0
--   months at limit     0        unexplained gaps 0
--   documents           6,077    distinct matters (file numbers) 4,562
--   Acts represented    33, 34, IA, IC
--
-- THE TRUNCATION GUARD EARNED ITS KEEP. 11 months came back at EXACTLY 100 rows — the page
-- limit — and were refused as complete rather than accepted. They are mostly SEPTEMBER, the
-- SEC's fiscal year-end and its heaviest month for instituting proceedings. Each was paginated
-- until its final page returned under the limit. Without the guard those 11 months would have
-- silently lost every proceeding past the hundredth.
--
-- RECEIPT DEFECT FOUND AND FIXED: ev_sec_fire_ap_month cleared `note` on every re-fire, wiping
-- the 'AT THE PAGE LIMIT' marker the collector had written, so the coverage view reported
-- months_at_limit = 0 while 11 months were in exactly that state. is_complete stayed false
-- (months_missing carried it) so nothing unsafe shipped, but a receipt that loses its own reason
-- is a bad receipt. The view now derives the condition from rows_found, which no re-fire erases.
--
-- ── 3. WHAT WAS ACQUIRED, AND WHAT WAS NOT ───────────────────────────────────────────
-- ACQUIRED: the complete administrative-proceedings INDEX — per row, the publish date, the
--   SEC-labelled respondents string, the File Number, every release number on the row, and the
--   order document URL. 6,077 respondent strings extracted, 0 rows dropped.
-- NOT ACQUIRED: the CONTENTS of the order documents. They are PDFs whose text is FlateDecode-
--   compressed and not extractable in this environment. Therefore
--   Phase 9C does NOT deliver order-level event types (cease-and-desist vs bar vs suspension vs
--   censure), monetary relief, or findings-versus-allegations language. Those remain unbuilt,
--   and are reported as zero-extracted rather than as zero-existing.
-- Respondent composition, by a STATED HEURISTIC on the name string (not an authoritative role
--   field): 3,677 carry a corporate marker, 2,400 do not. The SEC's index gives respondents, not
--   roles; per-party role (issuer, adviser, broker-dealer, officer) lives in the documents.
--
-- ── 4. MATTERS VS DOCUMENTS ──────────────────────────────────────────────────────────
-- 673 file numbers carry more than one document; the largest carries 14
--   (file 3-20003: 33-10841, 34-90700, 34-92205, 34-93711, 34-94525, 34-96665, 34-97008,
--    34-97855, 34-99255, 34-99779, 34-100153, 34-100668, 34-102304, 34-104233).
-- Counted as documents that is 6,077; counted as matters it is 4,562. The File Number is what
-- makes the difference, and it is the SEC's own identifier — not one we invented.
--
-- ── 5. CROSS-CORPUS (§7) — CANDIDATES, DELIBERATELY NOT MERGED ────────────────────────
-- 50 respondent strings appear in BOTH corpora; 46 pairs fall within 365 days. Every one is
-- stored in evidence.ev_sec_cross_corpus_candidate as 'possible_same_matter' and NOTHING is
-- merged, because §7 forbids merging on name and date and the administrative order that would
-- confirm or refute the link is an unreadable PDF. The clearest example is genuine and arose
-- unprompted: LR-24050 (2018-02-15) and IA-4857 (2018-02-22), file 3-18377, both
-- "Commonwealth Advisors, Inc. and Walter A. Morales" — one week apart, the classic
-- civil-action-then-follow-on-bar pattern. It is recorded as a candidate, not a merge.
--
-- ── 6. THE HOMESIGNAL ENTITY SCAN ────────────────────────────────────────────────────
-- All 36 organisations scanned against the complete corpus with a generous token match:
--   direct-company matches 0 · verified-parent matches 0 · unresolved 0 · no match 36.
-- The positive control on the same scan returned 330. The only near-miss is again
-- "Commonwealth Advisors, Inc. and Walter A. Morales" surfacing for the token "morales" —
-- a different party from T. MORALES COMPANY, L.L.C., and the similar-name negative control
-- appearing in real data rather than in a fixture, now in BOTH corpora.
--
-- ── 7. AVAILABILITY (§11) — TWO QUESTIONS, ANSWERED SEPARATELY ────────────────────────
--   SEC Litigation Releases        checked_no_records   (9B, unchanged)
--   SEC Administrative Proceedings checked_no_records   (9C, earned here)
-- Each carries its own scope note. Neither is a statement about nonpublic matters, about
-- periods outside 2017-04 .. 2026-08, or about ALJ initial decisions — which returned 0 rows
-- from its index and remains a SEPARATE, UNCHECKED source.
--
-- ── 8. MUTATIONS (applied, measured, rolled back) ────────────────────────────────────
--   BASE  ap_complete=true 113/113 · 6,077 docs · 4,562 matters · LR and AP both checked_no_records
--   M1 remove a month              -> is_complete FALSE, months 113 -> 112
--   M2 rescan while incomplete     -> availability INCOMPLETE, never checked_no_records
--   M3 remove the entity binding   -> 0 direct identity rows; attribution impossible
--   M4 similar-name decoy          -> 0 hits
--   M5 remove a cross-corpus link  -> candidates 46 -> 45 (matter count would inflate)
--   M6 demote the verified parent  -> inherited parent block 4 -> 0
--   Post-rollback: ap_complete=true, 6,077 docs, 46 candidates, 1 active CIK, 1 parent_company
--   claim, LR corpus still 2,795, Garfield still 0/49/4.
--
-- ── 9. IDEMPOTENCE / PERFORMANCE / COMPATIBILITY ─────────────────────────────────────
-- Every routine re-run: documents 6,077 · matters 4,562 · months 113/113 · candidates 46 ·
-- identity map 37 · source checks 37 · entities 170 · claims 732 — all identical.
-- Entity Track Record latency is UNCHANGED at 33.8 ms / 2,778 buffers despite adding 6,077
-- documents, because the corpus is scanned at INGEST and never at read. No Property Card
-- request makes a live SEC call.
-- Legacy md5s unchanged (company_track_events 9d501d16…, property_company_roles b3923c90…);
-- Phase 9B's litigation-release corpus still 2,795 releases; Garfield still 0/49/4.
--
-- ── 10. REMAINING SEC GAPS ───────────────────────────────────────────────────────────
--   1. Order-document contents are unread: SEC administrative orders are PDF-ONLY. So there are
--      no event types, no monetary relief, and no findings-vs-allegations language from them.
--      CORRECTION TO THIS RECORD (re-verified after Phase 9C shipped): an earlier line said the
--      .htm variant "503s". That was a TRANSIENT status read once and written down as though it
--      were the answer. Re-probed, the real result is a stable 404 across three URL patterns and
--      two eras — /litigation/admin/2018/ia-4857.htm, /litigation/admin/2026/34-106074.htm and
--      /litigation/admin/2017/34-80365.htm all 404 — while the corresponding .pdf returns 200.
--      The conclusion is unchanged and now rests on a positive control instead of one 503: the
--      documents exist, they are simply PDF-only. A 503 is not evidence of absence, and it should
--      not have been recorded as if it were.
--   2. ALJ initial decisions: index returned 0 rows; unchecked, and reported as such.
--      ⚠️ SUPERSEDED IN PART BY PHASE 9D: this section's claim that "HTML variants definitively
--      return 404" is WRONG. A canonical HTML page exists at
--      /enforcement-litigation/administrative-proceedings/<release-no> (200, three eras). It is
--      a STUB carrying no order text, so the PDF-only conclusion stands — but see the Phase 9D
--      block for the corrected basis.
--   3. Coverage starts 2017-04; earlier matters are outside the window and say so.
--   4. 46 cross-corpus pairs remain candidates pending document-level confirmation.
--   5. MSHA was NOT ingested, per instruction — still a future-phase candidate only.

-- ============================================================================
-- PHASE 9D (2026-08-11) — SEC ADMINISTRATIVE ORDER PDF EXTRACTION.
-- OUTCOME: BLOCKED IN THIS ENVIRONMENT. NO EXTRACTION WAS PERFORMED, NO DATA WAS WRITTEN,
-- AND NOTHING FROM PHASES 8-9C WAS CHANGED except one Phase 9C receipt corrected below.
-- Phase 9D's substantive requirements (§4-§8: procedural posture, findings vs allegations,
-- statutes, monetary relief, non-monetary sanctions) all depend on reading the order text.
-- The order text could not be obtained. Rather than produce a partial or inferred extraction,
-- nothing was written.
--
-- ── A GENUINE PHASE 9C DEFECT, FOUND AND CORRECTED ───────────────────────────────────
-- Phase 9C recorded: "administrative order documents are PDF-only; HTML variants definitively
-- return 404." THE SECOND HALF IS WRONG. An HTML page DOES exist, at the canonical path that
-- mirrors the litigation-release pattern 9B had already proven working:
--     https://www.sec.gov/enforcement-litigation/administrative-proceedings/<release-no>
-- Verified 200 across three eras: 34-106074 (2026), ia-4857 (2018), 34-80365 (2017).
-- In 9C I tested only the LEGACY paths (/litigation/admin/YYYY/<rel>.htm) and the file-number
-- path, got 404s, and generalised from them. The canonical pattern — the one I had already
-- used successfully for litigation releases in 9B — was never tried. That is the same class of
-- error as testing one URL shape and concluding a source does not exist.
-- THE CONCLUSION SURVIVES, for a different reason than recorded: the page is a STUB. Measured
-- on 34-106074 — 66,436 bytes, of which the respondent name appears 3 times (title and heading),
-- the file number 0 times, "Release No" 0 times, "cease-and-desist" 0 times, and exactly ONE
-- .pdf link. There is no order text, no structured metadata and no cross-reference to a
-- litigation release. So administrative order CONTENT is still PDF-only.
-- ⚠️ A near-miss worth recording: an early keyword probe on that page reported
-- "cease-and-desist|respondent|disgorgement" as TRUE and I nearly took it as proof the HTML
-- carried the order. It did not — "respondent" occurs at byte 41,042 inside the SIDEBAR NAV
-- ("Information for Respondents in Administrative Proceedings"), and "cease-and-desist" does
-- not occur at all. A match is a lead, not a fact; the position had to be read.
--
-- ── WHY THE PDFs CANNOT BE READ HERE — THREE INDEPENDENT RECEIPTS ────────────────────
-- 1. pg_net DESTROYS PDF BINARY. net._http_response.content is a TEXT column; a PDF's first
--    NUL/invalid-UTF-8 byte truncates it. Measured against each response's own Content-Length:
--        34-106074.pdf     444 stored of 126,786 declared =  0.35% retained
--        ia-4857.pdf     1,433 stored of  89,991 declared =  1.59% retained
--        34-80365.pdf      747 stored of 104,929 declared =  0.71% retained
--    The bytes are gone before any parser could run. This is not a parsing problem.
-- 2. THE SANDBOX CANNOT FETCH THEM. Direct egress to sec.gov returns CONNECT tunnel 403 from
--    the agent proxy — an ORGANISATION POLICY DENIAL. The proxy's own README states such
--    denials must be reported, not retried or worked around. So it was reported, not evaded.
-- 3. NO TEXT ALTERNATIVE EXISTS. Legacy .htm paths 404 (three patterns, two eras). The
--    canonical HTML page is a stub (above). Drupal's JSON:API at /jsonapi returns 404.
--
-- ── WHAT WOULD UNBLOCK PHASE 9D (unchanged scope, one capability) ────────────────────
-- Any ONE of:
--   a. a runner with egress to sec.gov that can fetch the PDF and run a text extractor
--      (pdftotext / pdf.js), writing text + hash + provenance back — this is the same
--      "verification runs on a GitHub runner" pattern the ingest repo already uses for
--      government sources the sandbox cannot reach;
--   b. a Supabase Edge Function fetching the PDF and extracting text server-side, which has
--      egress today and is where get-address-report already runs;
--   c. a bytea-capable HTTP path in Postgres so the PDF survives storage intact.
-- None of these is a schema or architecture change to the evidence graph; Phase 9D's design
-- (source PDF -> text -> provenance -> matter -> materialize -> serve locally) stands ready.
--
-- ── WHAT REMAINS TRUE AFTER 9D ───────────────────────────────────────────────────────
-- Phase 9C's PRESENCE/ABSENCE coverage is untouched and still fully defensible:
--   administrative proceedings 113/113 months, 6,077 documents, 4,562 matters,
--   2017-04-03 .. 2026-08-11, 0 unexplained gaps, HomeSignal entity scan 0/36.
--   litigation releases 2,795, complete. Garfield 0/49/4.
-- DETAIL coverage is 0 of 6,077 documents — and Phase 9C's split of PRESENCE coverage from
-- DETAIL coverage is exactly what lets that be stated without invalidating anything.
-- The 46 cross-corpus candidate pairs remain candidates: resolving them needs the order text,
-- and the landing pages carry no cross-reference to resolve them from.
