-- ============================================================================
-- MULTI-SOURCE EVIDENCE — PHASE 1 (SQL OF RECORD)
-- Applied 2026-08-10 to project qwnnmljucajnexpxdgxr as four migrations:
--   evidence_phase1_core_foundation
--   evidence_phase1_rls_and_vocabulary
--   evidence_phase1_read_model  (+ _enum_labels)
--   evidence_phase1_del_valle_pilot_ingest / _tdlr_projects_and_bridge
--   evidence_phase1_fix_cross_source_org_merge
--
-- ADDITIVE ONLY. Everything lives in the `evidence` schema except ONE function,
-- public.ev_parcel_report(). No existing table, view, function or read path was
-- altered. No production page reads any of this.
-- ============================================================================

create schema if not exists evidence;

-- ── enums ────────────────────────────────────────────────────────────────────
-- entity_kind      parcel | development | facility | organization | instrument
-- uniqueness_scope global | state | county | authority_dataset
-- currency_basis   point_in_time | as_of_certified_roll | continuously_updated | unknown
-- evidence_class   recorded_instrument | authoritative_filing | authoritative_roll
--                  | identifier_backed | source_reported | resolved_by_match | derived
-- authority_class  authoritative | official_secondary | republished | third_party | unknown
-- fact_kind        source | normalized | resolved | derived
-- claim_status     active | superseded_by_source | retracted_by_source | rejected_by_homesignal
-- check_status     success | success_empty | source_error | unavailable | partial | not_checked
--                  ^ §26: a failed fetch is a recorded state, never an absent fact.

-- ── SOURCE LAYER ─────────────────────────────────────────────────────────────
-- ev_source, ev_source_coverage, ev_source_capability
-- ev_source_authority(source_id, predicate, authority_class)
--     Authority is per (source, predicate). This is what lets TDLR be authoritative
--     about its own filing while never outranking TCAD about who owns the land —
--     without deleting either claim.
-- ev_source_role_map(source_id, source_vocab_field, source_vocab_value, predicate)
--     THE ROLE-COLLAPSE FIX AS DATA. 'OWNER block' -> project_owner_as_filed;
--     'ownerName' -> property_owner_of_record. Adding a source adds rows here,
--     never new predicates.

-- ── RAW PRESERVATION (§6) ────────────────────────────────────────────────────
-- ev_source_record(source_record_id, source_id, source_record_key, url, http_status,
--                  retrieved_at, parser_version, payload_hash, payload jsonb,
--                  payload_storage, as_of, superseded_by)
--     Every claim FKs to exactly one source_record. A source correction is a NEW
--     record + superseded_by; claims flip status. Nothing is deleted.
-- ev_source_check(...)  every attempt, including the ones that found nothing.

-- ── IDENTITY (§4) ────────────────────────────────────────────────────────────
-- ev_entity(entity_id uuid pk, kind, jurisdiction_state, jurisdiction_county)
--     Surrogate key. A source identifier is NEVER the primary key.
-- ev_identifier_type(id_type pk, identifies_kind, issuing_authority,
--                    uniqueness_scope, scope_state, scope_county, normalizer)
--     'tcad.prop_id' is county-scoped to TX/Travis and identifies a PARCEL.
--     'epa.frs_registry_id' is global and identifies a FACILITY.
-- ev_entity_identifier(entity_id, entity_kind, id_type, id_value,
--                      id_value_normalized, source_record_id, is_primary, status)
--     UNIQUE (id_type, id_value_normalized) WHERE status='active'
--     Scope lives in the TYPE, so PROP_ID 292354 in another county is a different
--     id_type and cannot collide. There is no global "APN".
--     TRIGGER ev_identifier_kind_guard: an id_type whose identifies_kind does not
--     match the entity's kind raises — a cross-kind false join is impossible.
-- ev_entity_resolution(entity_a, entity_b, kind, basis, evidence_url, decided_by)
--     Rows are NEVER merged. 'not_same_entity' is a first-class outcome.

-- ── TYPED CORES (thin) ───────────────────────────────────────────────────────
-- ev_parcel, ev_organization, ev_development, ev_facility, ev_recorded_instrument
--     Deliberately hold almost nothing. Even an organization's NAME is a claim.

-- ── EVIDENCE (§7) ────────────────────────────────────────────────────────────
-- ev_predicate(key pk, domain, consumer_label, definition, explicit_non_meaning,
--              object_kind, version)
--     Carries the EXPLICIT NON-MEANING. project_owner_as_filed is documented as
--     "NOT evidence of land ownership" in the database itself.
-- ev_claim(claim_id, source_record_id NOT NULL, subject_entity_id, subject_kind,
--          predicate, object_entity_id | object_value, object_unit,
--          source_predicate_raw NOT NULL, source_object_raw,
--          valid_from, valid_to, currency_basis, as_of, observed_at,
--          evidence_class, authority_class, fact_kind, status, status_reason)
--     CHECK ev_claim_one_object: exactly one of object_entity_id / object_value.
--     source_predicate_raw is NOT NULL — you may not write a claim without
--     recording what the source actually called the relationship.
-- ev_claim_relation(claim_a, claim_b, kind)  corroborates | contradicts | supersedes
-- ev_claim_geometry(claim_id pk, geom geometry(MultiPolygon,4326))
-- ev_display_precedence(predicate, authority_class, evidence_class, rank)
--     §22 — precedence is DATA. Storage never arbitrates; display does, at read time.
-- ev_legacy_property_report_link(report_address, parcel_entity_id, basis, evidence_class)
--     §18 — the non-destructive bridge. property_reports stays address-keyed and
--     unmodified; address is NOT the parcel entity's key.

-- ── SCALAR FACTS: DESIGN CHOICE (§7) ─────────────────────────────────────────
-- Acreage / legal description / values are stored as CLAIMS WITH LITERAL OBJECTS
-- (object_value + object_unit), not as entity columns and not as a separate
-- observation table. Three reasons:
--   1. every scalar carries the same provenance as every relationship — one path;
--   2. value history is temporal for free (one claim per year via as_of), so no
--      number is ever overwritten;
--   3. a second source contributing the same fact needs no schema change, and the
--      two claims coexist rather than one clobbering the other. Proven live: TCAD
--      publishes BOTH legalAcreage 36.4740 and landInfo.sizeAcres 28.4940 — two
--      different measurements, both retained, distinguished by source_predicate_raw.

-- ── SECURITY (§29) ───────────────────────────────────────────────────────────
-- The `evidence` schema is NOT in Supabase's exposed-schema list, so PostgREST
-- cannot reach it with the anon key at all. RLS is additionally ENABLED on all 22
-- tables with NO policies (deny by default), and USAGE on the schema is revoked
-- from anon/authenticated. Raw payloads — which contain owner mailing addresses —
-- are therefore unreachable from any browser client.
-- The only read path is public.ev_parcel_report(id_type, id_value), SECURITY
-- DEFINER, EXECUTE revoked from anon/authenticated, which selects owner NAME only
-- and never mailing data (§27).

-- ── CONSUMER READ MODEL (§23) ────────────────────────────────────────────────
-- public.ev_parcel_report(_id_type text, _id_value text) returns jsonb
--   Takes a SOURCE identifier, never a UUID, an address or a company name.
--   Returns: jurisdiction, identifiers[], property{}, ownership[], value_history[],
--            development[], deed_references[], sources_checked[].
--   Emits NO internal UUID and NO enum token — evidence.ev_label() maps each enum
--   to plain English once, so no frontend ever learns the vocabulary.

-- ============================================================================
-- PHASE 2 ADDITIONS (2026-08-10) — Travis County Clerk registration +
-- ownership resolution. Migration: evidence_phase2_clerk_source_and_ownership_resolution
--
-- ⛔ THE CLERK ADAPTER WAS NOT BUILT. Both official access paths prohibit
-- automated retrieval, with receipts:
--   * www.tccsearch.org/robots.txt  →  "User-agent: ClaudeBot / Disallow: /"
--                                      "Content-Signal: search=yes,ai-train=no,use=reference"
--     and the site returns HTTP 403 behind a Cloudflare challenge.
--   * travis.tx.publicsearch.us/robots.txt → "Allow: /$" + "Disallow: /"
--     no public API (every /api/* path 404s), results gated behind sign-in /
--     Kofile "timed access".
-- Nothing was scraped. Zero Clerk claims exist.
-- ============================================================================

-- ── new predicates: a deed party is NOT an owner ─────────────────────────────
-- grantee_on_recorded_instrument — "NOT automatically the current owner. A later
--   instrument may have conveyed the property onward."
-- grantor_on_recorded_instrument — "NOT 'former owner'. Being a grantor on one
--   instrument does not establish that the party ever held, or has since lost, title."
-- has_instrument_type, has_recording_date

-- ── ev_source 'travis_county_clerk' ──────────────────────────────────────────
--   access_mode = 'not_machine_accessible', status = 'blocked_by_source_terms'
--   AUTHORITATIVE for recorded instruments (outranks the appraisal roll for owner
--   of record); explicitly NOT authoritative for values, acreage or classification.
--   Authority + role map + precedence are declared NOW so a licensed feed slots in
--   with no schema change. Declaring authority is not the same as holding evidence.

-- ── ev_source_check: 4 rows, status 'unavailable' ────────────────────────────
--   One per TCAD-reported instrument (2008006779TR, 2010122587TR, 2012114190TR,
--   2021024697), each recording WHAT was attempted and WHY it failed.
--   'unavailable' is explicitly NOT "the instrument does not exist".

-- ── public.ev_current_owner(id_type, id_value) ───────────────────────────────
-- MINIMUM ownership-resolution policy (§18), documented rather than hardcoded:
--   1. Candidates are ownership-BEARING claims only: property_owner_of_record and
--      grantee_on_recorded_instrument.
--   2. Winner = latest `as_of`; ties broken by ev_display_precedence rank.
--      RECENCY FIRST — so an older recorded deed does NOT override a newer assessor
--      roll. "Clerk always wins" is deliberately not implemented.
--   3. state = 'disagreement' when another claim shares the winner's period AND
--      rank but names a different party. Both survive; neither is deleted.
--      state = 'corroborated_by_independent_county_records' only when more than one
--      SOURCE names the same party in the same period.
--      state = 'single_source' otherwise — a historical deed chain is NOT a conflict.
--   4. `supporting` always returns EVERY candidate claim. Resolution never deletes.
-- No score of any kind is produced (§19).

-- ============================================================================
-- PHASE 3 ADDITIONS (2026-08-10) — Denver, CO jurisdiction-independence proof.
-- Migrations: evidence_phase3_denver_sources_and_adapter,
--             evidence_phase3_adapter_helpers,
--             evidence_phase3_generalize_read_model
--
-- NO new core table. NO new predicate. Denver reused all 21 Phase 1/2 predicates.
-- ============================================================================

-- ── new identifier types (jurisdiction-scoped, §7) ──────────────────────────
-- denver.schednum      parcel      | Denver Assessor      | scope county CO/Denver
-- denver.reception_num instrument  | Denver Clerk+Recorder| scope county CO/Denver
-- The same digit string under tcad.prop_id is a DIFFERENT parcel: uniqueness lives in
-- the id_type, so a Denver SCHEDNUM can never collide with a Travis PROP_ID.

-- ── new sources ─────────────────────────────────────────────────────────────
-- denver_assessor_parcels        City and County of Denver Assessor, ArcGIS, first-party,
--                                authoritative for owner/situs/legal/area/class/value/geometry.
-- denver_odc_sales_transfers     Denver's real property sales and transfers index. Carries the
--                                Clerk and Recorder RECEPTION NUMBER, recording date, document
--                                type, and grantor/grantee AS RECORDED.
--                                Classified authority_class='official_secondary', NOT
--                                'authoritative': the publisher is the Assessor, not the Clerk
--                                and Recorder, which remains the system of record. It is also a
--                                SUBSET (87,862 rows) of all recordings, not a complete index.

-- ── authority stays PREDICATE-SPECIFIC ──────────────────────────────────────
-- The transfers index is official_secondary for grantee/grantor/instrument-type/recording-date
-- and for conveyed_by_instrument. It is deliberately given NO authority over
-- property_owner_of_record: a grantee is not an owner.
-- ev_display_precedence ranks: clerk recorded_instrument 10 < assessment roll 20 <
-- county-published recording index 30.

-- ── parcel <-> instrument linkage: DIRECT ───────────────────────────────────
-- The transfers rows publish PARID alongside RECEPTION_NUM, so the link is
-- evidence_class='identifier_backed' with source_predicate_raw='PARID' — the strongest class,
-- not an address match. Join rule: SCHEDNUM = lpad(PARID::text, 13, '0'), VALIDATED by control
-- (transfers PARID 225333015000 resolved to exactly one parcel SCHEDNUM '0225333015000').

-- ── idempotent adapter ──────────────────────────────────────────────────────
-- evidence.ev_ingest_denver_parcel(parcel_json, instr_json, parcel_url, instr_url)
--   Find-or-create on every entity, keyed on the AUTHORITATIVE identifier; source records
--   de-duplicated on (source_id, source_record_key, payload_hash); claims guarded by existence
--   checks. Proven: three consecutive runs left 26 entities / 135 claims / 11 source records /
--   15 identifiers / 2 geometries unchanged.
-- evidence.ev_find_or_create_org(name, source_id, source_record, field)
--   Organizations are SOURCE-SCOPED. Two sources naming the same string get two entities;
--   sameness is only ever an evidenced ev_entity_resolution row, never an implicit join.
--   This is why 'DENVER HEALTH AND HOSPITAL AUTHORITY' (2026 grantor) and
--   'DENVER HEALTH AND HOSPITALAUTHORITY' (2017 grantee) are NOT merged.

-- ── read-model fix (NOT a core-schema change) ───────────────────────────────
-- Phase 1's deed section hardcoded id_type='travis.instrument_no' — county-specific parsing,
-- which surfaced as instrument_number:null on the first Denver read. Replaced with
-- evidence.ev_instrument_number(), which resolves via identifier_type.identifies_kind =
-- 'instrument'. Added public.ev_recorded_instruments() returning number, document type,
-- recording date, grantor[], grantee[], and the parcel-link basis + evidence class.
-- public.ev_current_owner() now also walks parcel -> conveyed_by_instrument -> instrument ->
-- grantee, so an assessment roll and a recording index can corroborate ACROSS entity kinds.
-- Both functions are SECURITY DEFINER with EXECUTE revoked from anon/authenticated.
-- Owner MAILING address (OWNER_ADDRESS_LINE1/CITY/STATE/ZIP) is present in the raw Denver
-- payload and is deliberately never promoted to a claim and never returned by any read.

-- ============================================================================
-- PHASE 4 ADDITIONS (2026-08-10) — consumer property card, feature-flagged pilot.
-- Migration: evidence_phase4_pilot_flag_and_card_rpc
-- ============================================================================
-- evidence.ev_pilot_parcel(id_type, id_value, enabled)  — the allowlist is DATA, keyed on
--   the AUTHORITATIVE identifier, never an address. Two rows: tcad.prop_id 292354 and
--   denver.schednum 0015300060000. RLS on, revoked from anon.
-- public.ev_property_card(id_type, id_value) — the ONE RPC the browser calls. Returns
--   {pilot_enabled:false} for anything not on the allowlist, so the flag cannot be
--   bypassed client-side. EXECUTE granted to anon; ev_parcel_report / ev_current_owner /
--   ev_recorded_instruments remain revoked from anon.
-- evidence.ev_area_rank(basis) — §11 acreage arbitration, DECLARED not guessed:
--   'legalAcreage' and 'LAND_AREA' rank 1 (the parcel's own area);
--   'landInfo.sizeAcres' ranks 5 (an appraisal land-segment size, NOT the parcel).
--   The loser is retained and shown as "Other reported measurement", never substituted.
-- evidence.ev_doc_type_label(source, code) — SW/WD/QC/PS expanded using Denver's OWN
--   published convention (its ASAL_INSTR field reads e.g. "SW: SPECIAL WARRANTY").
-- Consumer status vocabulary is mapped in the RPC, so no internal enum ever reaches the
-- browser: corroborated / reported / disagree / unknown.
