-- ============================================================================
-- SOURCE-KEY RECONCILER — EXECUTABLE DEFINITIONS ONLY. PARKED, NOT APPLIED.
--
-- GENERATED by scripts/gen_geo_reconciler_install.py from the canonical
-- implementation in scripts/n5_reconcile_sql.py. Do not hand-edit: regenerate.
--
-- ⛔ THIS REPLACES docs/geo-source-scoped-reconcile.sql IN THE INSTALL MANIFEST.
-- That file is NOT a definitions file and must never be applied as one:
--   (a) it carries four BARE, TOP-LEVEL resident-geography DML statements
--       against geo.zip_authoritative_membership and geo.zip_authoritative_marker,
--       so applying it would mutate the planes this workstream must not touch;
--   (b) they are parameterised with psql bind placeholders (:keys, :run), which
--       are not valid SQL in any driver, so it cannot execute as written; and
--   (c) it calls geo.n5_expected_marker(:keys), WHICH IS DEFINED NOWHERE IN THE
--       REPOSITORY - it defines only geo.n5_expected_membership.
-- Measured at dedb7db 2026-09-20. Keep that file as the design record; install this.
--
-- 🔑 DEFINING IS NOT RUNNING. Every DML statement below sits INSIDE a function
-- body. Creating the function compiles it and executes none of it. Reconciliation
-- happens only when something CALLS geo.n5_reconcile(_keys, _run), and after a
-- passive install nothing does: the lifecycle handoffs only ENQUEUE, no worker
-- exists, and no cron job references it. Installation therefore performs ZERO
-- reconciliation executions and touches ZERO resident geography.
--
-- BOUNDED BY CONSTRUCTION: _keys is the sole bound and appears in every stage, so
-- a caller cannot widen the blast radius by editing one stage. A NULL or empty
-- _keys does nothing.
--
-- STAGE ORDER IS LOAD-BEARING: geometry -> boundary -> membership -> markers.
-- Markers are reconciled AFTER membership because the marker build reads
-- membership. The order below is the order in scripts/n5_reconcile_sql.py::STAGES
-- and is not re-typed here.
--
-- OWNERSHIP / GRANTS / EXECUTION ROLE
--   owner:      postgres (the role applying the migration)
--   grants:     none. `revoke all ... from public` below is deliberate - no anon
--               or authenticated role may invoke the reconciler. The future worker
--               runs as the service role, which bypasses RLS.
--   RLS:        this function writes geo.* planes; it must be called by a role
--               that can, i.e. the owner or service_role. It is intentionally NOT
--               security definer: a definer-rights reconciler callable from
--               PostgREST would be a privilege-escalation surface.
-- ============================================================================

begin;

create or replace function geo.n5_reconcile_stage1(_keys text[], _run text)
returns void
language plpgsql
set search_path = pg_catalog, public, pg_temp
as $s1$
begin

with named as (select unnest(_keys::text[]) source_key),
fetched as (select distinct source_key from geo.n5_geom_incoming
             where source_key in (select source_key from named)),
fp_new as (
  select n.source_key,
         (select md5(coalesce(string_agg(f.feature_id || '|' || f.outcome::text || '|' || coalesce(encode(ST_AsBinary(f.geom),'hex'),'') || '|' || coalesce(f.invalid_reason,''), E'\n' order by f.feature_id collate "C"), '')) from geo.n5_geom_incoming f where f.source_key = n.source_key) fp
    from fetched n),
fp_old as (
  select n.source_key,
         (select md5(coalesce(string_agg(f.feature_id || '|' || f.outcome::text || '|' || coalesce(encode(ST_AsBinary(f.geom),'hex'),'') || '|' || coalesce(f.invalid_reason,''), E'\n' order by f.feature_id collate "C"), '')) from geo.n5_geom f where f.source_key = n.source_key) fp
    from fetched n),
changed as (
  select a.source_key from fp_new a join fp_old b using (source_key)
   where a.fp is distinct from b.fp)

delete from geo.n5_geom g where g.source_key in (select source_key from changed);

with named as (select unnest(_keys::text[]) source_key),
fetched as (select distinct source_key from geo.n5_geom_incoming
             where source_key in (select source_key from named)),
fp_new as (
  select n.source_key,
         (select md5(coalesce(string_agg(f.feature_id || '|' || f.outcome::text || '|' || coalesce(encode(ST_AsBinary(f.geom),'hex'),'') || '|' || coalesce(f.invalid_reason,''), E'\n' order by f.feature_id collate "C"), '')) from geo.n5_geom_incoming f where f.source_key = n.source_key) fp
    from fetched n),
fp_old as (
  select n.source_key,
         (select md5(coalesce(string_agg(f.feature_id || '|' || f.outcome::text || '|' || coalesce(encode(ST_AsBinary(f.geom),'hex'),'') || '|' || coalesce(f.invalid_reason,''), E'\n' order by f.feature_id collate "C"), '')) from geo.n5_geom f where f.source_key = n.source_key) fp
    from fetched n),
changed as (
  select a.source_key from fp_new a join fp_old b using (source_key)
   where a.fp is distinct from b.fp)

insert into geo.n5_geom (source_key, registry_id, feature_id, outcome, geom, invalid_reason,
                    first_z3, provenance, verdict_snapshot_id)
select i.source_key, i.registry_id, i.feature_id, i.outcome, i.geom, i.invalid_reason,
       i.first_z3, i.provenance, i.verdict_snapshot_id
  from geo.n5_geom_incoming i
 where i.source_key in (select source_key from changed);

end $s1$;
revoke all on function geo.n5_reconcile_stage1(text[], text) from public;

create or replace function geo.n5_reconcile(_keys text[], _run text)
returns void
language plpgsql
set search_path = pg_catalog, public, pg_temp
as $rec$
begin
  if _keys is null or cardinality(_keys) = 0 then return; end if;
  perform geo.n5_reconcile_stage1(_keys, _run);

with named as (select unnest(_keys::text[]) source_key),
expected as (
  select distinct b.zcta5, g.source_key, g.provenance
    from named n
    join geo.n5_geom g on g.source_key = n.source_key and g.outcome = 1 and g.geom is not null
    join geo.zcta_boundary b on ST_Intersects(ST_MakeValid(g.geom), b.geom)
   where b.zcta5 in (select zip from public.canonical_zip_registry)),
del as (
  delete from geo.n5_boundary_membership m
   where m.source_key in (select source_key from named)
     and not exists (select 1 from expected e
                      where e.zcta5 = m.zcta5 and e.source_key = m.source_key)
  returning 1)
insert into geo.n5_boundary_membership (zcta5, source_key, provenance, run_id)
select e.zcta5, e.source_key, e.provenance, _run from expected e
on conflict (zcta5, source_key) do update
   set provenance = excluded.provenance, run_id = excluded.run_id
 where geo.n5_boundary_membership.provenance is distinct from excluded.provenance;


with named as (select unnest(_keys::text[]) source_key),
pairs as (
  select distinct b.zcta5, g.source_key
    from named n
    join geo.n5_geom g on g.source_key = n.source_key and g.outcome = 1 and g.geom is not null
    join geo.zcta_boundary b on ST_Intersects(ST_MakeValid(g.geom), b.geom)
   where b.zcta5 in (select zip from public.canonical_zip_registry)),
expected as (
  select pr.zcta5, pr.source_key,
         case when p2.pt is null then null else ST_Y(p2.pt) end lat,
         case when p2.pt is null then null else ST_X(p2.pt) end lng,
         p2.rule point_rule, x2.dim clip_dim, x2.nfeat feature_count, x2.family geom_family
    from pairs pr
    join geo.zcta_boundary b2 on b2.zcta5 = pr.zcta5
    cross join lateral (
        select ST_Intersection(ST_MakeValid(ST_Union(g2.geom)), b2.geom) clip,
               count(*)::int nfeat, min(ST_GeometryType(g2.geom)) family
          from geo.n5_geom g2
         where g2.source_key = pr.source_key and g2.outcome = 1 and g2.geom is not null
           and ST_Intersects(ST_MakeValid(g2.geom), b2.geom)) f2
    cross join lateral (select f2.clip, f2.nfeat, f2.family,
                        case when f2.clip is null then null else ST_Dimension(f2.clip) end::smallint dim) x2
    cross join lateral geo.n5_rep_point(x2.clip) p2),
del as (
  delete from geo.zip_authoritative_membership m
   where m.source_key in (select source_key from named)
     and not exists (select 1 from expected e
                      where e.zcta5 = m.zcta5 and e.source_key = m.source_key)
  returning 1)
insert into geo.zip_authoritative_membership (zcta5, source_key, lat, lng, point_rule, clip_dim, feature_count, geom_family, run_id)
select e.zcta5, e.source_key, e.lat, e.lng, e.point_rule, e.clip_dim, e.feature_count, e.geom_family, _run
  from expected e
on conflict (zcta5, source_key) do update
   set lat = excluded.lat, lng = excluded.lng, point_rule = excluded.point_rule,
       clip_dim = excluded.clip_dim, feature_count = excluded.feature_count,
       geom_family = excluded.geom_family, run_id = excluded.run_id
 where geo.zip_authoritative_membership.lat is distinct from excluded.lat
    or geo.zip_authoritative_membership.lng is distinct from excluded.lng
    or geo.zip_authoritative_membership.point_rule is distinct from excluded.point_rule
    or geo.zip_authoritative_membership.clip_dim is distinct from excluded.clip_dim
    or geo.zip_authoritative_membership.feature_count is distinct from excluded.feature_count
    or geo.zip_authoritative_membership.geom_family is distinct from excluded.geom_family;


with named as (select unnest(_keys::text[]) source_key),
pairs as (
  select distinct b.zcta5, g.source_key
    from named n
    join geo.n5_geom g on g.source_key = n.source_key and g.outcome = 1 and g.geom is not null
    join geo.zcta_boundary b on ST_Intersects(ST_MakeValid(g.geom), b.geom)
   where b.zcta5 in (select zip from public.canonical_zip_registry)),
base as (
  select pr.zcta5, pr.source_key, x.family, x.clip
    from pairs pr
    join geo.zcta_boundary b on b.zcta5 = pr.zcta5
    cross join lateral (
        select ST_Intersection(ST_MakeValid(ST_Union(g.geom)), b.geom) clip,
               min(ST_GeometryType(g.geom)) family
          from geo.n5_geom g
         where g.source_key = pr.source_key and g.outcome = 1 and g.geom is not null
           and ST_Intersects(ST_MakeValid(g.geom), b.geom)) x),
comp as (
  select z.zcta5, z.source_key, z.family, 1 as dim, d.geom g,
         ST_Length(d.geom::geography) measure
    from base z
    cross join lateral ST_Dump(ST_LineMerge(ST_CollectionExtract(z.clip, 2))) d
   where not ST_IsEmpty(d.geom)
  union all
  select z.zcta5, z.source_key, z.family, 2, d.geom, ST_Area(d.geom::geography)
    from base z cross join lateral ST_Dump(ST_CollectionExtract(z.clip, 3)) d
   where not ST_IsEmpty(d.geom)
  union all
  select z.zcta5, z.source_key, z.family, 0, d.geom, 0
    from base z cross join lateral ST_Dump(ST_CollectionExtract(z.clip, 1)) d
   where not ST_IsEmpty(d.geom)),
keep as (
  select c.*,
         (c.dim = 0
          or (c.dim = 1 and (c.measure >= 250.0
                             or c.measure = max(case when c.dim=1 then c.measure end)
                                              over (partition by c.zcta5, c.source_key)))
          or (c.dim = 2 and (c.measure >= 1000.0
                             or c.measure = max(case when c.dim=2 then c.measure end)
                                              over (partition by c.zcta5, c.source_key)))) as keep_it
    from comp c),
placed as (
  select k.zcta5, k.source_key, k.family, k.dim, k.measure, k.g, gs.i,
         greatest(1, ceil(k.measure / 1000.0)::int) as n_on_comp
    from keep k
    cross join lateral generate_series(
        0, case when k.dim = 1 then greatest(1, ceil(k.measure / 1000.0)::int) - 1 else 0 end) gs(i)
   where k.keep_it),
pt as (
  select p.*,
         case when p.dim = 1 then ST_LineInterpolatePoint(p.g, (p.i + 0.5) / p.n_on_comp::float8)
              when p.dim = 2 then ST_PointOnSurface(p.g)
              else p.g end as mp
    from placed p),
expected as (
  select zcta5, source_key,
         row_number() over (partition by zcta5, source_key
                            order by dim desc, measure desc, ST_AsBinary(g) asc, i asc)::int marker_seq,
         ST_Y(mp) lat, ST_X(mp) lng,
         case when dim = 1 then 'LINE_MERGED_COMPONENT_INTERVAL_1000M'
              when dim = 2 then 'POLYGON_COMPONENT_POINT_ON_SURFACE'
              else 'POINT_AUTHORITATIVE' end marker_rule,
         family, dim::smallint dim
    from pt),
del as (
  delete from geo.zip_authoritative_marker kk
   where kk.source_key in (select source_key from named)
     and not exists (select 1 from expected e
                      where e.zcta5 = kk.zcta5 and e.source_key = kk.source_key
                        and e.marker_seq = kk.marker_seq)
  returning 1)
insert into geo.zip_authoritative_marker (zcta5, source_key, marker_seq, lat, lng, marker_rule, family, dim, run_id)
select e.zcta5, e.source_key, e.marker_seq, e.lat, e.lng, e.marker_rule, e.family, e.dim, _run
  from expected e
on conflict (zcta5, source_key, marker_seq) do update
   set lat = excluded.lat, lng = excluded.lng, marker_rule = excluded.marker_rule,
       family = excluded.family, dim = excluded.dim, run_id = excluded.run_id
 where geo.zip_authoritative_marker.lat is distinct from excluded.lat
    or geo.zip_authoritative_marker.lng is distinct from excluded.lng
    or geo.zip_authoritative_marker.marker_rule is distinct from excluded.marker_rule
    or geo.zip_authoritative_marker.family is distinct from excluded.family
    or geo.zip_authoritative_marker.dim is distinct from excluded.dim;

end $rec$;
revoke all on function geo.n5_reconcile(text[], text) from public;

comment on function geo.n5_reconcile(text[], text) is
  'Source-key scoped reconciler. Bounded by _keys, which appears in every stage. '
  'Generated from scripts/n5_reconcile_sql.py by scripts/gen_geo_reconciler_install.py; '
  'regenerate rather than hand-edit. Defining this function executes nothing - '
  'reconciliation happens only when it is called, and after a passive install '
  'nothing calls it.';

do $post$
begin
  -- ⚠️ FAIL CLOSED. An earlier draft made these warnings, reasoning by analogy with
  -- the coverage-state migration where an unreadable cron catalog must not roll back
  -- a correct VIEW. That analogy is wrong here: these are PRE-MUTATION SAFETY GATES
  -- for a production install, and "I could not check whether the scheduler is on" is
  -- not permission to proceed. The read is still WRAPPED so the failure NAMES which
  -- check could not run - an unevaluated check must say so rather than pass silently
  -- OR abort anonymously - but it aborts the transaction either way.
  begin
    if (select count(*) from cron.job where jobname ~* 'geo|reconcil|n5') <> 0 then
      raise exception 'A geography cron job exists. The scheduler must remain OFF.';
    end if;
  exception
    when insufficient_privilege or undefined_table or invalid_schema_name then
      raise exception 'STOP - SCHEDULER CHECK NOT EVALUATED: cron catalog unreadable (%). '
                      'An unevaluated safety check is NOT permission to proceed. Establish '
                      'that the scheduler is OFF and re-run.', sqlerrm;
  end;
  begin
    if (select count(*) from pg_trigger t
         where t.tgrelid = 'public.app_projects'::regclass and not t.tgisinternal) <> 0 then
      raise exception 'A trigger appeared on public.app_projects. None is authorised.';
    end if;
  exception
    when insufficient_privilege or undefined_table then
      raise exception 'STOP - TRIGGER CHECK NOT EVALUATED: public.app_projects unreadable (%). '
                      'An unevaluated safety check is NOT permission to proceed.', sqlerrm;
  end;
end $post$;

commit;
