-- GENERATED by scripts/geo_handoff_splice.py from
-- docs/geo-lifecycle-handoff-install.sql. Do not hand-edit: regenerate.
--
-- ROLLBACK for the lifecycle-handoff splice. Reverses every replacement and
-- asserts the result is md5-identical to the pre-install body, so a rollback
-- can never leave a third, half-reverted version behind.
--
-- It refuses to run unless the live body is EXACTLY the post-install one. If
-- another session amended app_refresh_zip after the install, this file is not
-- safe and the reversal must be re-derived against the new body.
begin;
do $rb$
declare _out text; _before text;
begin
  _out := pg_get_functiondef('public.app_refresh_zip(text)'::regprocedure);
  _before := md5(_out);
  if _before <> 'ba2e6f9d8932d08e4373bfe97ae25ffd' then
    raise exception 'ROLLBACK PRECONDITION FAIL: live md5 is %, expected the post-install %. '
                    'Re-derive the reversal against the current body.', _before, 'ba2e6f9d8932d08e4373bfe97ae25ffd';
  end if;
  _out := replace(_out, $q$    with geo_fence as (
    update public.app_projects set lat=null, lng=null
     where zip=_zip and lat is not null and (
       lat not between 17 and 72 or lng not between -180 and -60
       or (_lat is not null and 3959*acos(least(1::double precision, greatest(-1::double precision,
            cos(radians(_lat))*cos(radians(lat))*cos(radians(lng)-radians(_lng))
            + sin(radians(_lat))*sin(radians(lat))))) > 100)
     )
    returning source_key
    )
    select array_agg(distinct source_key) into _geo_keys from geo_fence;
    perform geo.enqueue_work(_geo_keys, 'geocode_nulled');$q$, $q$    update public.app_projects set lat=null, lng=null
     where zip=_zip and lat is not null and (
       lat not between 17 and 72 or lng not between -180 and -60
       or (_lat is not null and 3959*acos(least(1::double precision, greatest(-1::double precision,
            cos(radians(_lat))*cos(radians(lat))*cos(radians(lng)-radians(_lng))
            + sin(radians(_lat))*sin(radians(lat))))) > 100)
     );$q$);
  _out := replace(_out, $q$  with geo_del as (
  delete from public.app_projects p
   where p.zip=_zip
     and (p.last_seen_at is null or p.last_seen_at < _run)
     and not exists (select 1 from public.property_company_roles r where r.project_id = p.id)
     and not exists (select 1 from public.project_facility_refs  f where f.project_id = p.id)
     and not exists (select 1 from public.identity_conflicts     c where c.project_id = p.id)
  returning p.source_key
  )
  select count(*)::int,
         array_agg(distinct source_key) filter (where source_key is not null)
    into _stale, _geo_keys
    from geo_del;
  perform geo.enqueue_work(_geo_keys, 'stale_removed');$q$, $q$  delete from public.app_projects p
   where p.zip=_zip
     and (p.last_seen_at is null or p.last_seen_at < _run)
     and not exists (select 1 from public.property_company_roles r where r.project_id = p.id)
     and not exists (select 1 from public.project_facility_refs  f where f.project_id = p.id)
     and not exists (select 1 from public.identity_conflicts     c where c.project_id = p.id);
  get diagnostics _stale = row_count;$q$);
  _out := replace(_out, $q$      source_key_basis=excluded.source_key_basis, last_seen_at=excluded.last_seen_at
      returning source_key
    )
    select array_agg(distinct source_key) into _geo_keys from geo_up_fac;
    perform geo.enqueue_work(_geo_keys, 'project_upsert');
  end if;$q$, $q$      source_key_basis=excluded.source_key_basis, last_seen_at=excluded.last_seen_at;
  end if;$q$);
  _out := replace(_out, $q$      source_key_basis=excluded.source_key_basis, last_seen_at=excluded.last_seen_at
      returning source_key
    )
    select array_agg(distinct source_key) into _geo_keys from geo_up_dev;
    perform geo.enqueue_work(_geo_keys, 'project_upsert');

    with geo_up_fac as (
    insert into public.app_projects (community_id, zip, name, type, status, developer, lat, lng, impact_score, source_ref, record_kind, registry_id, facility_env,$q$, $q$      source_key_basis=excluded.source_key_basis, last_seen_at=excluded.last_seen_at;

    insert into public.app_projects (community_id, zip, name, type, status, developer, lat, lng, impact_score, source_ref, record_kind, registry_id, facility_env,$q$);
  _out := replace(_out, $q$    with geo_up_dev as (
    insert into public.app_projects (community_id, zip, name, type, status, stage, developer, size, investment, submitted_at, lat, lng, impact_score, source_ref, record_kind, registry_id, date_kind, type_raw,$q$, $q$    insert into public.app_projects (community_id, zip, name, type, status, stage, developer, size, investment, submitted_at, lat, lng, impact_score, source_ref, record_kind, registry_id, date_kind, type_raw,$q$);
  _out := replace(_out, $q$        _run timestamptz; _stale int; _kept int;
        _geo_keys text[];$q$, $q$        _run timestamptz; _stale int; _kept int;$q$);
  if md5(_out) <> '6591d7f79f9a6cd0b476bbcfc2065b9a' then
    raise exception 'ROLLBACK DID NOT RECONSTRUCT THE ORIGINAL: got %, expected %.',
      md5(_out), '6591d7f79f9a6cd0b476bbcfc2065b9a';
  end if;
  execute _out;
  if md5(pg_get_functiondef('public.app_refresh_zip(text)'::regprocedure)) <> '6591d7f79f9a6cd0b476bbcfc2065b9a' then
    raise exception 'ROLLBACK POST-CHECK FAILED.';
  end if;
  raise notice 'app_refresh_zip rolled back to %', '6591d7f79f9a6cd0b476bbcfc2065b9a';
end $rb$;
commit;

-- The passive core is NOT dropped here. geo.n5_reconcile_queue and
-- geo.enqueue_work are inert once the handoffs are gone: nothing calls the
-- function and nothing reads the table. Dropping them is a separate, deliberate
-- act - see docs/geo-lifecycle-handoff-rollback-core.sql.
