-- GENERATED by test/n5_generation_pg/build_part_h.py - never hand-edited.
-- ROLLBACK for Part H (docs/n5-generation-publish-part-h.sql).
--
-- Puts geo.n5_generation_activate back to the body production carried before Part H: D12's
-- activate with the D14 lines cut out. The generator proves that cut equals the pre-Part-H
-- production fingerprint before writing this. geo.n5_generation_proof and its rows are KEPT
-- (the evidence of every proof stays), as are the two proof functions; the old activate does
-- not call them.
--
-- When to use it: the proof is refusing activation of a generation that is right, and Map 1
-- must move before the check is fixed. After running it, also revert D12's activate in
-- docs/n5-generation-publish-part-d.sql, or the DDL of record no longer describes production.
--
-- ONE transaction. Fail-closed on both sides:
--   before: the live activate must be exactly Part H's (6e7ce8ade5d6718e06d366f82d5a6f7c);
--   after:  it must be exactly the pre-Part-H body (2ccb4d4d25439d786d66c3dfbc384d30).
begin;
set local lock_timeout = '10s';
do $h$
declare m text;
begin
  select md5(p.prosrc) into m from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'geo' and p.proname = 'n5_generation_activate';
  if m is distinct from '6e7ce8ade5d6718e06d366f82d5a6f7c' then
    raise exception 'part H rollback: live n5_generation_activate is % - not Part H; refusing', m;
  end if;
end $h$;

create or replace function geo.n5_generation_activate(p_generation_id text, p_expected_chunks text[])
returns geo.n5_generation
language plpgsql
set search_path to 'geo', 'public', 'pg_temp'
as $function$
declare
  g            geo.n5_generation;
  prev         geo.n5_generation;
  n_chunks     int;
  n_missing    int;
  rc           record;
  integ        record;
  prob         record;
begin
  select * into g from geo.n5_generation where generation_id = p_generation_id for update;
  if not found then
    raise exception 'activate: unknown generation %', p_generation_id using errcode = '22023';
  end if;

  if g.state <> 'READY' then
    raise exception 'activate: generation % is %, not READY', p_generation_id, g.state using errcode = '22023';
  end if;

  if p_expected_chunks is null or array_length(p_expected_chunks, 1) is null then
    raise exception 'activate: no expected chunk set declared' using errcode = '22023';
  end if;
  n_chunks := array_length(p_expected_chunks, 1);
  select count(*) into n_missing
    from unnest(p_expected_chunks) c(k)
   where not exists (select 1 from geo.n5_generation_reconcile r
                      where r.generation_id = p_generation_id and r.chunk_key = c.k);
  if n_missing > 0 then
    raise exception 'activate: % of % declared chunks have no reconciliation row', n_missing, n_chunks using errcode = '22023';
  end if;

  -- RECOMPUTED, never trusted: reconcile rows are an ordinary table, so the answer the
  -- switch acts on is derived here, inside the switching transaction.
  select * into rc from geo.n5_reconcile_chunks(p_generation_id, p_expected_chunks);
  if rc.unaccounted > 0 then
    raise exception 'activate: INV-1 violated — % of % expected source_keys have no accounted outcome', rc.unaccounted, rc.expected_keys using errcode = '22023';
  end if;

  if rc.expected_keys = 0 then
    raise exception 'activate: reconciliation covered 0 expected records — refusing a vacuous pass' using errcode = '22023';
  end if;

  for prob in select * from geo.n5_generation_publish_problems(p_generation_id, p_expected_chunks) loop
    raise exception 'activate: generation % is incomplete — % = %', p_generation_id, prob.check_name, prob.n
      using errcode = '22023';
  end loop;

  for integ in select * from public.n5_expected_input_integrity() loop
    if not integ.ok then
      raise exception 'activate: source integrity check % failed — %', integ.check_name, integ.detail using errcode = '22023';
    end if;
  end loop;

  select * into prev from geo.n5_generation
   where state in ('ACTIVE','ACTIVE_LEGACY') and generation_id <> p_generation_id
   for update;

  update geo.n5_generation
     set superseded_from_state = state, state = 'SUPERSEDED', superseded_at = now()
   where state in ('ACTIVE','ACTIVE_LEGACY') and generation_id <> p_generation_id;

  update geo.n5_generation
     set state = 'ACTIVE', activated_at = now(),
         predecessor_generation_id = coalesce(predecessor_generation_id, prev.generation_id)
   where generation_id = p_generation_id
  returning * into g;

  return g;
end
$function$;
revoke all on function geo.n5_generation_activate(text, text[]) from public;

do $h$
declare m text;
begin
  select md5(p.prosrc) into m from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'geo' and p.proname = 'n5_generation_activate';
  if m is distinct from '2ccb4d4d25439d786d66c3dfbc384d30' then
    raise exception 'part H rollback post-condition failed: live n5_generation_activate is % - not the pre-Part-H body', m;
  end if;
end $h$;
commit;
