-- GENERATED by test/n5_generation_pg/build_part_g.py - never hand-edited.
-- ROLLBACK for Part G (docs/n5-generation-publish-part-g.sql, applied 2026-09-29 23:56Z).
--
-- Puts geo.n5_generation_publish_problems back to the body production carried before Part G:
-- Part D's D11 with the canonical_zip_status_disagrees_with_boundary block removed. The
-- generator proves that cut equals the pre-Part-G production fingerprint before writing this.
--
-- When to use it: the check is refusing READY or ACTIVATE for a generation whose status rows
-- are right, for example because geo.zcta_boundary was reloaded with a different TIGER vintage
-- than the loader's pinned file. After running it, also revert the D11 block in
-- docs/n5-generation-publish-part-d.sql, or the DDL of record no longer describes production.
--
-- ONE transaction. Fail-closed on both sides:
--   before: the live body must be exactly Part G's (66f5995db01c5bb8d6c9d88f9a217234);
--   after:  it must be exactly the pre-Part-G body (611926736840a6b43847978d2ec9e9d6).
begin;
set local lock_timeout = '10s';
do $g$
declare m text;
begin
  select md5(p.prosrc) into m from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'geo' and p.proname = 'n5_generation_publish_problems';
  if m is distinct from '66f5995db01c5bb8d6c9d88f9a217234' then
    raise exception 'part G rollback: live n5_generation_publish_problems is % - not Part G; refusing', m;
  end if;
end $g$;

create or replace function geo.n5_generation_publish_problems(p_generation_id text, p_expected_chunks text[])
returns table (check_name text, n bigint)
language sql stable
set search_path = geo, public, pg_temp
as $$
  with g as (select * from geo.n5_generation where generation_id = p_generation_id),
  checks as (
    select 'shards_not_done'::text c,
           (select count(*) from geo.n5_shard s where s.generation_id = p_generation_id and s.state <> 'done') n
    union all
    select 'no_shards', case when exists (select 1 from geo.n5_shard s where s.generation_id = p_generation_id) then 0 else 1 end
    union all
    select 'not_prepared', (select case when g.publish_prepared_at is null then 1 else 0 end from g)
    union all
    select 'prefixes_unpublished',
           (select count(*) from geo.n5_generation_publish_scope(p_generation_id) sc
             where not exists (select 1 from geo.n5_generation_publish p
                                where p.generation_id = p_generation_id and p.z3 = sc.z3))
    union all
    select 'unresolved_not_recorded_after_last_publish',
           (select case when g.unresolved_recorded_at is null
                          or g.unresolved_recorded_at < coalesce((select max(p.completed_at) from geo.n5_generation_publish p
                                                                   where p.generation_id = p_generation_id), '-infinity')
                        then 1 else 0 end from g)
    union all
    select 'membership_without_marker',
           (select count(*) from geo.zip_authoritative_membership m
             where m.generation_id = p_generation_id
               and not exists (select 1 from geo.zip_authoritative_marker k
                                where k.generation_id = m.generation_id and k.zcta5 = m.zcta5 and k.source_key = m.source_key))
    union all
    select 'marker_without_membership',
           (select count(*) from geo.zip_authoritative_marker k
             where k.generation_id = p_generation_id
               and not exists (select 1 from geo.zip_authoritative_membership m
                                where m.generation_id = k.generation_id and m.zcta5 = k.zcta5 and m.source_key = k.source_key))
    union all
    select 'canonical_zip_without_status',
           (select count(*) from public.canonical_zip_registry r
             where not exists (select 1 from geo.maps_zip_geography_status st
                                where st.generation_id = p_generation_id and st.zip = r.zip))
    union all
    select 'boundary_scratch_residue',
           (select count(*) from geo.n5_gen_zcta z where z.generation_id = p_generation_id)
    union all
    -- the declared chunk set must cover every expected key, or reconciliation could pass
    -- while a slice of the expected set was never evaluated at all. Evaluated once per
    -- distinct ZIP (a ZIP is covered or not regardless of how many rows carry it).
    select 'expected_keys_outside_declared_chunks',
           (select coalesce(sum(z.n), 0) from (
              select e.zip, count(*) n
                from public.n5_expected_captured((select snapshot_id from g)) e
               group by e.zip) z
             where p_expected_chunks is null
                or not exists (select 1 from unnest(p_expected_chunks) c(k)
                                where z.zip >= rpad(c.k, 5, '0') and z.zip <= rpad(c.k, 5, '9'))))
  select c, n from checks where n > 0;
$$;
revoke all on function geo.n5_generation_publish_problems(text, text[]) from public;

do $g$
declare m text;
begin
  select md5(p.prosrc) into m from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'geo' and p.proname = 'n5_generation_publish_problems';
  if m is distinct from '611926736840a6b43847978d2ec9e9d6' then
    raise exception 'part G rollback post-condition failed: n5_generation_publish_problems md5 %', m;
  end if;
end $g$;
commit;
