-- RESIDENTIAL QUALIFICATION — the national measurement, over the population Map 1 can actually
-- show. Read-only.
--
-- WHY THIS IS SCOPED TO THE ELIGIBLE POPULATION, NOT ALL OF app_projects: there is no index on
-- (record_kind, type), so selecting the 635k residential rows out of 3.2M is a full scan that
-- exceeds BOTH the 60s MCP budget and the 120s Management-API budget (measured 2026-09-05:
-- three timeouts). Driving from geo.zip_authoritative_membership instead uses
-- zip_authoritative_membership_pkey and then app_projects_source_key_kind_idx, so the work is
-- index lookups rather than a scan. It is also the RIGHT population: eligibility for Map 1 ZIP
-- mode IS membership on a boundary_complete ZIP, exactly as public.app_zip_projects_markers
-- defines it. Objects with no authoritative ZIP geography yet cannot render either way and are
-- reported separately as a coverage limit.
--
-- The CASE is GENERATED by scripts/residential-qualify-sql.mjs from lib/residential-qualify.js's
-- own exported vocabulary — never hand-written, so the measured rule and the shipped rule are
-- the same rule. Parity pinned by test/residential-qualify-sql-parity.test.mjs.
-- Every count is paired with a control.
with m as (
  select mm.zcta5, mm.source_key
  from geo.zip_authoritative_membership mm
  join geo.maps_zip_geography_status s on s.zip = mm.zcta5 and s.status = 'boundary_complete'),
k as (select distinct source_key from m),
p as (
  select k.source_key, a.registry_id, a.type, a.type_raw, a.name, a.status, a.submitted_at
  from k cross join lateral (
    select registry_id, type, type_raw, name, status, submitted_at
    from public.app_projects
    where source_key = k.source_key and record_kind = 'development'
    order by id limit 1) a),
n as (select source_key, registry_id, type, status, submitted_at, name, (' ' || btrim(regexp_replace(lower(coalesce(type_raw,'')), '[^a-z0-9]+', ' ', 'g')) || ' ') as tr, (' ' || btrim(regexp_replace(lower(coalesce(name,'')), '[^a-z0-9]+', ' ', 'g')) || ' ') as nm from p),
v as (select source_key, registry_id, type, status, submitted_at, name, case when (tr || nm) ~ ' (subdivision|resubdivision|subdivisions|plat|plats|replat|preliminary plat|final plat|site plan|site development plan|sitedevelopment|planned development|planned unit development|master plan|land development) ' then 'DEVELOPMENT' when nm ~ '^ (hvac|electric|electrical|plumbing|plumb|mechanical|gas piping|gas appliances|venting|boiler|furnace|water heater|photovoltaic|solar|trade|trades|ele|mec|plu|sprinkler|irrigation|low voltage|alter|alters|alteration|alterations|remodel|remodeling|renovation|renovations|repair|repairs|replace|replacing|replacement|reroof|re roof|roofing|roof|siding|window|windows|deck|decks|porch|porches|fence|fencing|pool|pools|spa|shed|carport|garage|accessory|maintenance|demolition|demo|tear off|tear down|teardown|interior|finish basement|basement finish|addition|additions|relocation|move|sign|signs|fire damage|retaining wall|driveway|patio|awning|generator|ev charger|antenna|alt|air conditioning|ductwork|tree|trees) ' then 'ROUTINE' when tr ~ '^ (new construction|new residential|new single family|new multi family|new multifamily|new apartment|new home|new homes|new house|new dwelling|new building|new bldg|new sfr|new sfd|residential new|construction residential|residential construction|site dev|sfd devel|ground up) ' or nm ~ '^ (new construction|new residential|new single family|new multi family|new multifamily|new apartment|new home|new homes|new house|new dwelling|new building|new bldg|new sfr|new sfd|residential new|construction residential|residential construction|site dev|sfd devel|ground up) ' then 'DEVELOPMENT' when tr ~ '^ (new|nb|dsp) ' and tr ~ ' (construction|home|homes|house|dwelling|dwellings|residence|residences|residential|duplex|apartment|apartments|townhome|townhomes|townhouse|condo|condominium|sfr|sfd|building|bldg|units|unit) ' then 'DEVELOPMENT' when nm ~ '^ (new|nb|dsp) ' and nm ~ ' (construction|home|homes|house|dwelling|dwellings|residence|residences|residential|duplex|apartment|apartments|townhome|townhomes|townhouse|condo|condominium|sfr|sfd|building|bldg|units|unit) ' then 'DEVELOPMENT' when (tr || nm) ~ ' (hvac|electric|electrical|plumbing|plumb|mechanical|gas piping|gas appliances|venting|boiler|furnace|water heater|photovoltaic|solar|trade|trades|ele|mec|plu|sprinkler|irrigation|low voltage|alter|alters|alteration|alterations|remodel|remodeling|renovation|renovations|repair|repairs|replace|replacing|replacement|reroof|re roof|roofing|roof|siding|window|windows|deck|decks|porch|porches|fence|fencing|pool|pools|spa|shed|carport|garage|accessory|maintenance|demolition|demo|tear off|tear down|teardown|interior|finish basement|basement finish|addition|additions|relocation|move|sign|signs|fire damage|retaining wall|driveway|patio|awning|generator|ev charger|antenna|alt|air conditioning|ductwork|tree|trees) ' then 'ROUTINE' when (registry_id = 'denton-county-dev-permits' and tr in (' house ', ' duplex ', ' mobile home ')) or (registry_id = 'dekalb-county-building-permits' and tr in (' new homes ')) then 'DEVELOPMENT' else 'UNRESOLVED' end as verdict from n),
z as (select m.zcta5, v.type, v.verdict from m join v on v.source_key = m.source_key)
select 'A_control_eligible_objects_all_types' as metric, count(*)::text as value from v
union all select 'B_residential_typed_total', count(*)::text from v where type='Residential'
union all select 'C_residential_' || verdict, count(*)::text from v where type='Residential' group by verdict
union all select 'D_generic_typed_total', count(*)::text from v where type in ('Development','unclassified')
union all select 'E_generic_' || verdict, count(*)::text from v where type in ('Development','unclassified') group by verdict
union all select 'F_zips_with_residential_before', count(distinct zcta5)::text from z where type='Residential'
union all select 'G_zips_with_residential_after', count(distinct zcta5)::text from z where type='Residential' and verdict='DEVELOPMENT'
union all select 'H_zips_losing_residential_entirely',
  (select count(*)::text from (select zcta5 from z where type='Residential' group by zcta5
     having count(*) filter (where verdict='DEVELOPMENT') = 0) q)
union all select 'I_control_zips_boundary_complete', (select count(*)::text from geo.maps_zip_geography_status where status='boundary_complete')
union all select 'J_kept_stage_' || coalesce(status,'null'), count(*)::text from v where type='Residential' and verdict='DEVELOPMENT' group by status
union all select 'K_kept_undated', count(*)::text from v where type='Residential' and verdict='DEVELOPMENT' and submitted_at is null
union all select 'L_kept_label_has_street_number', count(*)::text from v where type='Residential' and verdict='DEVELOPMENT' and name ~ '[0-9]{2,6}[ ]+[A-Za-z]'
union all select 'M_removed_label_has_street_number', count(*)::text from v where type='Residential' and verdict<>'DEVELOPMENT' and name ~ '[0-9]{2,6}[ ]+[A-Za-z]'
union all select 'N_family_' || registry_id, (count(*) filter (where verdict='DEVELOPMENT'))::text || ' kept of ' || count(*)::text
  from v where type='Residential' group by registry_id having count(*) >= 2500
order by 1;
