-- Generated by scripts/gov-feeds/build-candidate-sql.mjs
-- source: /workspace/results/gov-feed-discovery.json
-- at: 2026-07-19T20:40:50.982Z
-- SAFETY: candidates insert with active=false. Run golive separately.

-- candidate insert for wake-county-nc-granicus-meetings (idempotent; never deactivates production)
insert into public.feeds (feed_id, community_id, county, source, source_type, category, pipeline_type, agency_name, geographic_reference, impact_level, active, sort_order, target_table, filter_expr, dedupe_on, status_notes)
values ('wake-county-nc-granicus-meetings', 'c2d081a4-db8d-46d1-8ebe-4cd8b091fcf4', 'Wake County', 'https://wake.granicus.com/ViewPublisherRSS.php?view_id=18&mode=agendas', 'rss', 'County Commission & county business', 'government_notice', 'Wake County Board of Commissioners', 'Wake County, NC', 'medium', false, 0, 'meetings', '', '', '')
on conflict (feed_id) do nothing;
