#!/usr/bin/env python3
"""Generates docs/dev-change-copy-conflicts-apply.sql — the migration that upgrades the LIVE change ledger to the
copy-conflict rule (option (b)) — from the SQL of record, never by hand (a hand copy of 600 lines of SQL is an
unreviewed edit to production).

The migration is: a GUARD, the whole of docs/dev-change-ledger.sql (idempotent: create or replace / if not exists),
and a POST-CONDITION.
  guard ........... refuses unless the live writer is EITHER the version the upgrade was built against (OLD) or the
                    version it installs (NEW), so a writer someone else changed is never silently overwritten
  post-condition .. refuses (rolling the whole migration back) unless the writer now has the NEW body, the new
                    function and table exist, and the new table is closed to every public role
OLD is read from test/dev_change_ledger_pg/as_applied.sql — the exact file that was applied to production on
2026-09-29 (live md5(prosrc) 17b45b9c4b93855b0ed3ee7d2ada09e1, 8,074 characters, read from production 2026-10-01).
NEW is computed here from the SQL of record.

Usage: build_apply.py            -> writes docs/dev-change-copy-conflicts-apply.sql
       build_apply.py --check    -> exit 1 unless the committed file is exactly what would be written
"""
import hashlib, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
LEDGER = os.path.join(ROOT, 'docs', 'dev-change-ledger.sql')
APPLIED = os.path.join(HERE, 'as_applied.sql')
OUT = os.path.join(ROOT, 'docs', 'dev-change-copy-conflicts-apply.sql')
LIVE_OLD_MD5 = '17b45b9c4b93855b0ed3ee7d2ada09e1'   # read from production 2026-10-01; asserted equal to as_applied.sql below


def body_md5(text):
    a = text.index('create or replace function public.dev_change_observe_zip')
    s = text.index('as $fn$', a) + len('as $fn$')
    e = text.index('\n$fn$;', s)
    b = text[s:e + 1]                       # prosrc: everything between the dollar quotes
    return hashlib.md5(b.encode('utf-8')).hexdigest()


def build():
    ledger = open(LEDGER, encoding='utf-8').read()
    old = body_md5(open(APPLIED, encoding='utf-8').read())
    new = body_md5(ledger)
    if old != LIVE_OLD_MD5:
        sys.exit('as_applied.sql does not hash to the writer that is live in production (%s vs %s)' % (old, LIVE_OLD_MD5))
    if old == new:
        sys.exit('the SQL of record has the same writer as the one in production: nothing to upgrade')
    head = f"""-- =====================================================================================
-- ORDER C, OPTION (b): UPGRADE THE LIVE CHANGE LEDGER TO THE COPY-CONFLICT RULE
-- GENERATED by test/dev_change_ledger_pg/build_apply.py from docs/dev-change-ledger.sql — do not edit by hand.
-- (build_apply.py --check, and test/dev-change-ledger-structure.test.mjs, fail if this file is not exactly that.)
--
-- Apply as ONE migration (a migration runs its file in one transaction). It is idempotent.
--   old writer  md5(prosrc) {old}   (live in production since 2026-09-29)
--   new writer  md5(prosrc) {new}
-- What changes: dev_change_observe_zip gains the copy-conflict hold (rule 8); one new pure function
-- (dev_change_record_facts) and one new table (dev_change_copy_conflict, closed to every public role) are
-- created. No existing row, event, project or run is touched, and no existing table is altered.
-- Rollback: the ROLLBACK block at the foot of the ledger file below drops the new objects; restoring the old
-- writer is `create or replace` of test/dev_change_ledger_pg/as_applied.sql's function.
-- =====================================================================================

do $guard$
declare _live text;
begin
  if to_regprocedure('public.dev_change_observe_zip(text, uuid)') is null then
    raise exception 'the change ledger (docs/dev-change-ledger.sql) is not installed — refusing: this file upgrades a ledger that exists';
  end if;
  select md5(p.prosrc) into _live from pg_proc p where p.oid = to_regprocedure('public.dev_change_observe_zip(text, uuid)');
  if _live not in ('{old}', '{new}') then
    raise exception 'live dev_change_observe_zip has md5 %, which is neither the version this upgrade was built against ({old}) nor the version it installs ({new}) — refusing to overwrite a writer it has not seen', _live;
  end if;
end
$guard$;

-- ---- the SQL of record, verbatim ------------------------------------------------------
"""
    tail = f"""

-- ---- post-condition: roll the whole migration back unless the upgrade took --------------
do $post$
begin
  if (select md5(p.prosrc) from pg_proc p where p.oid = to_regprocedure('public.dev_change_observe_zip(text, uuid)')) is distinct from '{new}' then
    raise exception 'the upgrade did not install the writer it was built for ({new})';
  end if;
  if to_regclass('public.dev_change_copy_conflict') is null or to_regprocedure('public.dev_change_record_facts(jsonb)') is null then
    raise exception 'the upgrade did not create dev_change_copy_conflict / dev_change_record_facts';
  end if;
  if not (select relrowsecurity from pg_class where oid = 'public.dev_change_copy_conflict'::regclass) then
    raise exception 'dev_change_copy_conflict has no row level security';
  end if;
  if exists (select 1 from (values ('anon'), ('authenticated'), ('public')) r(role),
                          (values ('select'), ('insert'), ('update'), ('delete'), ('truncate')) p(priv)
              where has_table_privilege(r.role, 'public.dev_change_copy_conflict', p.priv)) then
    raise exception 'dev_change_copy_conflict is open to a public role';
  end if;
  if exists (select 1 from (values ('anon'), ('authenticated'), ('public')) r(role)
              where has_function_privilege(r.role, 'public.dev_change_record_facts(jsonb)', 'execute')
                 or has_function_privilege(r.role, 'public.dev_change_observe_zip(text, uuid)', 'execute')) then
    raise exception 'a dev_change_ function is executable by a public role';
  end if;
end
$post$;
"""
    return head + ledger.rstrip('\n') + '\n' + tail


def main():
    text = build()
    if len(sys.argv) > 1 and sys.argv[1] == '--check':
        cur = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else None
        if cur != text:
            sys.stderr.write('docs/dev-change-copy-conflicts-apply.sql is not what build_apply.py writes\n')
            return 1
        print('docs/dev-change-copy-conflicts-apply.sql is exactly what build_apply.py writes')
        return 0
    open(OUT, 'w', encoding='utf-8').write(text)
    print('wrote', OUT, len(text), 'chars; new writer md5', body_md5(open(LEDGER, encoding='utf-8').read()))
    return 0


if __name__ == '__main__':
    sys.exit(main())
