#!/usr/bin/env python3
"""Generate docs/n5-generation-publish-part-g.sql from Part D's D11 function, verbatim.

Part G is the production apply file for one change to geo.n5_generation_publish_problems:
the added check `canonical_zip_status_disagrees_with_boundary`. Its body is sliced from
docs/n5-generation-publish-part-d.sql (the DDL of record the executable suite runs), never
retyped, the same way Part F was sliced from Part D's D9.

  python3 test/n5_generation_pg/build_part_g.py          write both files
  python3 test/n5_generation_pg/build_part_g.py --check  exit 1 if either file is not what this writes

It also writes docs/n5-generation-publish-part-g.rollback.sql, which puts the previous body
back. That body is Part D's D11 with the Part G block cut out, and the cut is proven: its md5
must equal BEFORE_MD5, the fingerprint read from production before Part G was applied. So the
rollback can only restore exactly what was live before, never a retyped approximation.

The BEFORE fingerprint is the live md5(prosrc) read on 2026-09-29, which equals Part D's D11
body before this change (3,223 characters). The AFTER fingerprint is computed here from the
new body, so the post-condition can only pass on exactly the text in Part D.
"""
import hashlib
import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
PART_D = os.path.join(ROOT, "docs", "n5-generation-publish-part-d.sql")
OUT = os.path.join(ROOT, "docs", "n5-generation-publish-part-g.sql")
ROLLBACK = os.path.join(ROOT, "docs", "n5-generation-publish-part-g.rollback.sql")

BEFORE_MD5 = "611926736840a6b43847978d2ec9e9d6"
HEAD = "create or replace function geo.n5_generation_publish_problems(p_generation_id text, p_expected_chunks text[])"
TAIL = "revoke all on function geo.n5_generation_publish_problems(text, text[]) from public;"
CHECK = "canonical_zip_status_disagrees_with_boundary"
# The Part G block in D11: from its comment to the "union all" before the next check.
BLOCK_START = "    -- A status row that EXISTS can still be the wrong one."
BLOCK_END = "    select 'boundary_scratch_residue',"


def slice_d11(text):
    i = text.index(HEAD)
    j = text.index(TAIL, i) + len(TAIL)
    fn = text[i:j]
    s = fn.index("as $$") + len("as $$")
    e = fn.index("$$;", s)
    return fn, fn[s:e]


def previous(fn):
    """D11 with the Part G block removed, proven equal to the body production carried before."""
    i = fn.index(BLOCK_START)
    j = fn.index(BLOCK_END, i)
    if fn.count(BLOCK_START) != 1:
        raise SystemExit("STOP: the Part G block start appears more than once in D11")
    old_fn = fn[:i] + fn[j:]
    s = old_fn.index("as $$") + len("as $$")
    old_body = old_fn[s:old_fn.index("$$;", s)]
    if CHECK in old_body:
        raise SystemExit(f"STOP: the cut left {CHECK} in the previous body")
    got = hashlib.md5(old_body.encode()).hexdigest()
    if got != BEFORE_MD5:
        raise SystemExit(f"STOP: the cut body is {got}, not the pre-Part-G production body {BEFORE_MD5}")
    return old_fn


def build_rollback():
    fn, body = slice_d11(open(PART_D).read())
    after = hashlib.md5(body.encode()).hexdigest()
    old_fn = previous(fn)
    return f"""-- GENERATED by test/n5_generation_pg/build_part_g.py - never hand-edited.
-- ROLLBACK for Part G (docs/n5-generation-publish-part-g.sql, applied 2026-09-29 23:56Z).
--
-- Puts geo.n5_generation_publish_problems back to the body production carried before Part G:
-- Part D's D11 with the canonical_zip_status_disagrees_with_boundary block removed. The
-- generator proves that cut equals the pre-Part-G production fingerprint before writing this.
--
-- When to use it: the check is refusing READY or ACTIVATE for a generation whose status rows
-- are right, for example because geo.zcta_boundary was reloaded with a different TIGER vintage
-- than the loader's pinned file. After running it, also revert the D11 block in
-- docs/n5-generation-publish-part-d.sql, or the DDL of record no longer describes production.
--
-- ONE transaction. Fail-closed on both sides:
--   before: the live body must be exactly Part G's ({after});
--   after:  it must be exactly the pre-Part-G body ({BEFORE_MD5}).
begin;
set local lock_timeout = '10s';
do $g$
declare m text;
begin
  select md5(p.prosrc) into m from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'geo' and p.proname = 'n5_generation_publish_problems';
  if m is distinct from '{after}' then
    raise exception 'part G rollback: live n5_generation_publish_problems is % - not Part G; refusing', m;
  end if;
end $g$;

{old_fn}

do $g$
declare m text;
begin
  select md5(p.prosrc) into m from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'geo' and p.proname = 'n5_generation_publish_problems';
  if m is distinct from '{BEFORE_MD5}' then
    raise exception 'part G rollback post-condition failed: n5_generation_publish_problems md5 %', m;
  end if;
end $g$;
commit;
"""


def build():
    fn, body = slice_d11(open(PART_D).read())
    if CHECK not in body:
        raise SystemExit(f"STOP: Part D's D11 does not carry {CHECK}")
    after = hashlib.md5(body.encode()).hexdigest()
    return f"""-- GENERATED from docs/n5-generation-publish-part-d.sql by slicing its D11 function
-- (geo.n5_generation_publish_problems) verbatim - never hand-edited. Part G (2026-09-29).
-- Regenerate: python3 test/n5_generation_pg/build_part_g.py
--
-- Fix 3: ZIPs 94128, 95219 and 99128 have a Census ZCTA boundary and had NO row in the
-- generation that served until 2026-09-27 (legacy-phase1-2026-09-01: 12,013 boundary_complete
-- + 706 not_measured = 12,719 of 12,722). Each is the only canonical ZIP of its ZIP3 prefix
-- (941, 952, 991), and the legacy writer (scripts/n5_unit_a_shadow.py) built only prefixes that
-- had a phase-1 shard. None of the three did. The generation path already repaired the
-- PRESENCE half: publication scope = shard prefixes + every canonical prefix, and READY /
-- ACTIVATE refuse on canonical_zip_without_status. Both national generations since carry all
-- 12,722 rows, and the three have served since 2026-09-27 15:00Z.
--
-- This adds the CORRECTNESS half. A row can exist and still be wrong: publish writes
-- boundary_complete only where the loader made a polygon resident, so a shape the loader
-- skipped would publish a ZIP that has a boundary as not_measured, and every existing check
-- would pass. The new check compares each canonical ZIP's status with geo.zcta_boundary (the
-- same pinned TIGER 2025 file) and blocks READY and ACTIVATE on any disagreement.
-- Measured 2026-09-29 before applying: 0 disagreements in every generation that has rows.
--
-- ONE transaction. Fail-closed on both sides:
--   before: the live body must be exactly the previous DDL of record (md5(prosrc) {BEFORE_MD5});
--   after:  it must be exactly the new DDL of record ({after}).
begin;
set local lock_timeout = '10s';
do $g$
declare m text;
begin
  select md5(p.prosrc) into m from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'geo' and p.proname = 'n5_generation_publish_problems';
  if m is distinct from '{BEFORE_MD5}' then
    raise exception 'part G: live n5_generation_publish_problems is % - not the previous DDL of record; refusing', m;
  end if;
end $g$;

{fn}

do $g$
declare m text;
begin
  select md5(p.prosrc) into m from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'geo' and p.proname = 'n5_generation_publish_problems';
  if m is distinct from '{after}' then
    raise exception 'part G post-condition failed: n5_generation_publish_problems md5 %', m;
  end if;
end $g$;
commit;
"""


if __name__ == "__main__":
    files = ((OUT, build()), (ROLLBACK, build_rollback()))
    if "--check" in sys.argv:
        bad = [p for p, text in files
               if (open(p).read() if os.path.exists(p) else "") != text]
        for p in bad:
            print(f"{os.path.relpath(p, ROOT)} is NOT what build_part_g.py writes - regenerate it", file=sys.stderr)
        if bad:
            sys.exit(1)
        print("part G and its rollback match Part D's D11")
    else:
        for p, text in files:
            open(p, "w").write(text)
            print("wrote", p)
